// All user-visible copy of the /new site (EN / DE / 中文).
// Facts about David Brainin come from the live site; facts about Philip Kügler from his CV (released by him, 2026-09).

export const LANGS = [["en", "EN"], ["de", "DE"], ["cn", "中文"]];
export const HTML_LANG = { en: "en", de: "de", cn: "zh-Hans" };

export const TX = {
// ─────────────────────────────────────────────────────────────── EN
en: {
  meta: {
    home: "InVentures — Company Building, Legal, Capital & Technology",
    tech: "Tech & AI — InVentures",
    re: "Real Estate & Hospitality — InVentures",
    notFound: "Page not found — InVentures",
  },
  ui: {
    entity: "A project of Inside Holding & Real Estate GmbH",
    entityLong: "InVentures, a project of Inside Holding & Real Estate GmbH",
    back: "Back to overview",
    menu: "Menu",
    since06: "Since 2006", since15: "Since 2015",
    imprint: "Imprint", privacy: "Privacy Policy", cookies: "Cookie Settings",
    trackTech: "Tech & AI", trackRe: "Real Estate",
    switchTrack: "Close track",
    notFoundTitle: "Page not found.",
    notFoundText: "The page you are looking for does not exist or has moved.",
  },
  homeNav: [["team", "Management"], ["regulated", "Regulated Ventures"], ["track-record", "Track Record"], ["kontakt", "Contact"]],
  home: {
    brandSub: "Venture Building in AI & Real Estate",
    brandP: "Company building, legal structuring, capital and technology from a single team — for ventures and transformations in regulated markets. From first concept to measurable impact.",
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "Two disciplines. One venture platform.",
    selectSub: "Select your area of interest",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI Transformation · Regulated Platforms · Company Building", tags: ["AI Transformation", "GDPR / AI Act", "Health & Education", "Company Building"], cta: "Explore Tech & AI" },
      re: { label: "Real Estate &\nHospitality", sub: "Sale & Acquisition · Transactions · Project Leadership", tags: ["Sale & Acquisition", "Transactions", "Project Mgmt", "Hospitality"], cta: "Explore Real Estate" },
    },
  },
  team: {
    label: "Management",
    title: "Two partners. One well-rehearsed team.",
    intro: "InVentures is led by two managing partners who have worked together for years. David Brainin is responsible for legal, capital and company building; Philip Kügler for technology, architecture and delivery. Together we cover what ventures in regulated markets need — from the first structure to the platform in operation.",
    people: [
      {
        key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
        role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        bio: "Lawyer, startup founder and serial CEO with more than 25 years of operational responsibility. Transaction record exceeding EUR 600 million across six sectors, founder of Geolad GmbH, commissioned by Deutsche Telekom and A1 in 2015 to build new digital revenue streams. Hands-on practice in GDPR and the EU AI Act.",
        facts: [{ v: "€600m+", l: "transaction volume advised" }, { v: "€45m+", l: "VC & growth capital mobilised" }, { v: "€12m+", l: "research grants secured" }],
      },
      {
        key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver",
        role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        bio: "Enterprise architect, programme manager and CTO with more than 25 years in large-scale IT and transformation projects. Platforms for the public sector, health, education, finance and telecom — from the IT build-up of a national health insurance to the customs systems of the Austrian Ministry of Finance. IT security, data protection and high availability as architecture principles.",
        facts: [{ v: "4", l: "national government programmes" }, { v: "100+", l: "mobile operators integrated in 15 countries" }, { v: "30+", l: "systems integrated into one national platform" }],
      },
    ],
    bondsLabel: "What we bring together",
    bonds: [
      { t: "Regulated markets", d: "Health, education, public sector, finance, real estate: we know the rules of these markets — legally and technically." },
      { t: "Sensitive data", d: "GDPR including special categories of data, data protection impact assessments, EU AI Act, ISO 27001 and BSI requirements — built into architecture and business model from day one." },
      { t: "From concept to operation", d: "Incorporation, governance, funding, architecture, rollout and operations — one team, no friction between strategy and implementation." },
    ],
    cta: "Discuss a project",
  },
  regulated: {
    label: "Regulated Ventures",
    title: "Platforms for sensitive data need more than good software.",
    intro: "Anyone working with health, education or public-sector data needs a robust legal basis, a secure architecture, funding beyond the pilot phase — and partners who have done it before. This is exactly where our experience overlaps.",
    pillars: [
      { t: "Company Building & Capital", who: "David Brainin", d: "Incorporation, governance, shareholder structures and go-to-market — plus more than EUR 45 million in venture and growth capital mobilised and more than EUR 12 million in research grants secured." },
      { t: "Legal & Compliance", who: "David Brainin", d: "GDPR for special categories of personal data, data protection impact assessments, processor agreements and EU AI Act risk classification — legally sound before the first line of code." },
      { t: "Security by Design", who: "Philip Kügler", d: "ISO 27001, BSI and GDPR requirements implemented together with data protection and security officers; identity and access management and single sign-on (Keycloak, OIDC/SAML); secure international data transfer." },
      { t: "Architecture & Operations", who: "Philip Kügler", d: "Highly available platforms for public authorities, health and education: integration of 30+ surrounding systems, backup and failover concepts, rollout and handover to operations." },
    ],
    fieldsLabel: "Where we have delivered",
    fields: [
      { t: "Health & Science", items: ["IT build-up of a national health insurance (Qatar, with McKinsey)", "European Stroke Organisation", "Sigmund Freud University Vienna"] },
      { t: "Education", items: ["Untis — federal, state and school integration, identity management & SSO", "Danube University Krems", "TU Wien — teaching and guest lectures"] },
      { t: "Public Sector", items: ["Austrian Federal Ministry of Finance / Customs — import stream under the Union Customs Code (> EUR 10m, 30+ systems)", "National ePassport, ID card and border-control systems", "City of Vienna"] },
      { t: "Society", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    closing: "The result: platforms that professionals, institutions and public authorities can trust with their data.",
  },
  timeline: { label: "Track Record", title: "20 Years. One Through-Line.", sub: "From Vienna real estate to global telecom data platforms to AI advisory — a deliberate journey across the industries that matter." },
  clients: { label: "Selected clients & partners", fo: "+ undisclosed family offices" },
  groups: { telecom: "Telecom & Data", public: "Public Sector & Health", edu: "Education & Science", finance: "Finance & Payments", industry: "Industry & Technology", re: "Real Estate & Hospitality", legal: "Legal, Media & Society" },
  contact: {
    label: "Contact", title: "Get in touch.",
    p: "For strategic enquiries, projects in regulated markets, partnerships or accelerator applications.",
    web: "Web", mail: "E-mail", loc: "Location", locV: "Vienna, Austria", entity: "Legal entity",
    form: {
      name: "Name", company: "Company", email: "E-mail address", topic: "Area of interest", message: "Message",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulated markets / joint venture", "Other"],
      namePh: "Your name", companyPh: "Company (optional)", emailPh: "you@company.com", messagePh: "Briefly describe your enquiry or project…",
      submit: "Send enquiry", sending: "Sending…",
      privacy: "Your data is processed in accordance with our", privacyLink: "privacy policy",
      success: "Thank you — your enquiry has been sent. We will be in touch shortly.",
      fallbackTitle: "Your enquiry could not be sent automatically.",
      fallbackText: "Please send it by e-mail instead — we have prepared the message for you.",
      fallbackBtn: "Open e-mail", fallbackOr: "or write directly to",
      required: "Please enter your name and a valid e-mail address.",
    },
  },
  insights: { label: "Research & Insights", title: "News & Publications", sub: "Curated articles, reports and market analyses.", all: "All", more: "Show more", read: "Read article" },
  tech: {
    nav: [["team", "Management"], ["compliance", "Compliance"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    h1: ["Deep Analysis.", "Fast Execution.", "High Impact."],
    heroP: "Strategic sparring, AI-driven enterprise transformation and Agentic AI implementation — and digital platforms for regulated markets, where data protection is a precondition, not an option. OPEX reduction and new revenue streams, measurable within 6 to 9 months.",
    ctaA: "Our services", ctaB: "Meet the team",
    stats: [{ v: "€45m+", l: "VC & growth capital mobilised" }, { v: "€12m+", l: "Research grants secured" }, { v: "4", l: "National government programmes" }, { v: "100+", l: "Mobile operators integrated in 15 countries" }, { v: "40+", l: "Projects in DACH & MENA" }, { v: "50+", l: "Years of combined experience" }],
    partnerTitle: "Clients & Partners",
    teamLabel: "Management",
    teamTitle: "Law, capital and technology — from one team.",
    teamIntro: "Two managing partners who have worked together for years — and who are jointly accountable for what they recommend.",
    profiles: [
      {
        key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
        role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        paras: [
          "Lawyer, startup founder and serial CEO with over 25 years of operational experience. Transaction record exceeding EUR 600 million across six sectors — from telecom to real estate, hospitality, science and social impact.",
          "Commissioned in 2015 as a pioneer by Deutsche Telekom and A1 Group to develop new digital revenue streams. Founder and CEO of Geolad GmbH — a multinational telecom data platform with 30+ employees and partners across EU and Asia.",
          "In-depth knowledge of GDPR and EU AI Act in theory and enterprise practice.",
        ],
        quote: "Thinking like a lawyer. Acting like an entrepreneur. Executing with high impact.",
        cards: [
          ["Telecom & Data", "Deutsche Telekom, A1 Group, Orange, Zain, Viettel, Huawei, Ericsson"],
          ["Science & Education", "European Stroke Organisation, Sigmund Freud University Vienna, Danube University Krems"],
          ["Real Estate", "Wiener Privatbank SE, EPI Immobilien Group, Uniqa Versicherung"],
          ["Legal", "Lansky & Partner RAe, Herbst Kinsky"],
          ["Hospitality", "EPI Hospitality, Ibis Group, Arcotel Hotels"],
          ["Social Impact", "Integrationshaus Wien, ORF, Red Bull, Verein vidid"],
        ],
      },
      {
        key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver",
        role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        paras: [
          "Enterprise architect, programme manager and CTO with more than 25 years of experience in large-scale IT and transformation projects. Recent focus: public sector, finance and education — large-scale programmes in which IT security, data protection and high availability are non-negotiable.",
          "IT build-up of a national health insurance (Qatar, with McKinsey), product owner for imports in the customs system of the Austrian Federal Ministry of Finance, national ePassport and border-control systems, and the integration of more than 100 mobile operators in 15 countries with a team of 50+ across three continents.",
          "Identity and access management (Keycloak, OIDC/SAML) for federal, state and school administrations; ISO 27001, BSI and GDPR requirements implemented together with data protection and security officers. CTO & co-founder of OptInk, managing director of Merkit Consulting FlexCo. MSc in Media Informatics (TU Wien, with distinction), IPMA Level C, iREB.",
        ],
        quote: "Thinking in systems. Building pragmatically. Running reliably.",
        cards: [
          ["Public Sector", "Austrian Ministry of Finance / Customs, ePassport & border control, central civil registry"],
          ["Health", "National health insurance Qatar (McKinsey / Supreme Council of Health)"],
          ["Education", "Untis — federal, state and school integration, IAM & SSO; TU Wien"],
          ["Finance & Payments", "Global Blue, Arthur D. Little (m-payment), core-banking integration"],
          ["Telecom & Platforms", "Telekom Austria, VeriSign / 3united — 100+ mobile operators in 15 countries"],
          ["Ventures & Industry", "OptInk, Merkit Consulting, Porsche Informatik (Volkswagen), RISE, Match Maker Ventures"],
        ],
      },
    ],
    comp: {
      label: "Data Protection, Security & AI Regulation",
      title: "GDPR, EU AI Act, ISO 27001 — from day one.",
      p: "Since the GDPR came into force in 2018 we have advised on and implemented data protection compliance across several industries — and built platforms whose architecture has to meet the requirements of authorities, insurers and schools. Legal assessment and technical implementation come from one team.",
      cols: [
        { t: "Legal & Regulatory", who: "David Brainin", items: [
          "8 years of hands-on GDPR implementation across telecom, real estate, hospitality and science",
          "Special categories of personal data (Art. 9 GDPR): legal basis, consent and processing concepts",
          "Data protection impact assessments (DPIAs) for AI systems and automated decision-making",
          "EU AI Act readiness: risk classification, conformity assessments, documentation obligations",
          "Cross-border data transfer structuring (EU, MENA, ASEAN) under Schrems II requirements",
        ] },
        { t: "Security & Architecture", who: "Philip Kügler", items: [
          "Security requirements under ISO 27001, BSI and ITIL — implemented with data protection and security officers",
          "Identity and access management and SSO rollouts (Keycloak, OIDC/SAML) in grown public-sector environments",
          "Secure international data transfer and IT compliance process models",
          "High-availability, backup and failover architectures for critical national systems",
          "Privacy by design and AI governance in the data architecture — including team enablement",
        ] },
      ],
    },
    tLabel: "AI Transformation & Implementation", tTitle: "OPEX Reduction & New Revenue Streams",
    tP: "We don't transform enterprises in theory — we implement measurable results. Three levers: reduce operational costs, unlock new revenue streams — and pioneer Agentic AI implementation that acts autonomously within your organisation. All demonstrable within 6 to 9 months.",
    opexT: "OPEX Reduction",
    opex: ["AI-driven automation of repetitive processes", "Reduction of manual error rates and rework costs", "Intelligent document management and contract analysis", "Consolidation of fragmented data sources and systems", "Predictive maintenance replacing reactive cost drivers"],
    revT: "New Revenue Streams",
    rev: ["Data monetisation from existing enterprise assets", "AI-driven product and service development", "Digital platform and marketplace models", "Cross-selling through intelligent customer analytics", "Scalable SaaS components from internal solutions"],
    kpis: [{ v: "6–9", u: " months", l: "to measurable results" }, { v: "30%+", l: "typical OPEX savings in target processes" }, { v: "Net New", l: "revenue streams from existing assets", gold: true }],
    sLabel: "Services", sTitle: "What we do",
    serv: [
      { t: "Strategic Sparring & Advisory", d: "C-level strategic reflection with cross-sector perspective. Transaction support in complex stakeholder environments. Interim management.", tags: ["CEO Sparring", "Transactions", "Interim"] },
      { t: "AI & Data Consulting", d: "Industry-specific AI advisory from readiness assessment to operational implementation. AI agents, data platforms, predictive analytics — GDPR and EU AI Act compliant.", tags: ["AI Agents", "Data Strategy", "EU AI Act"] },
      { t: "AI Transformation & Implementation", d: "End-to-end AI transformation. Workflow automation, intelligent document management, change management for AI-driven work processes.", tags: ["Automation", "Implementation", "Dashboards"] },
      { t: "Agentic AI — Pioneer & Deploy", d: "Design and deploy autonomous multi-agent systems within your organisation or partnership network. From orchestration architecture to production: AI that acts independently, eliminates bottlenecks and creates compounding operational value.", tags: ["Agentic AI", "Multi-Agent", "Autonomous"] },
      { t: "Platforms for Regulated Markets", d: "Conception, build and operation of digital platforms for health, education and the public sector: legal basis, security architecture, identity management, funding strategy and rollout — from one team.", tags: ["Health & Education", "Public Sector", "Security by Design"] },
      { t: "Company Building, Joint Ventures & Accelerator", d: "Building ventures with founder experience: ideation, incorporation, joint-venture structures, fundraising and grants, international scaling — plus a fast-track programme for early-stage teams.", tags: ["Company Building", "Joint Ventures", "Fundraising"] },
    ],
    netLabel: "Network & Execution", netTitle: "The right team for every challenge.",
    netP: "We don't just advise — we execute. With the right experts, assembled project-specifically from a proven network spanning legal, technology, real estate, finance and industry.",
    clusters: [
      ["Legal", "Corporate, IP & regulatory — Lansky & Partner RAe, Herbst Kinsky"],
      ["Tech & AI", "Enterprise architects, security & IAM specialists, AI and data engineers, product builders"],
      ["Public & Health", "Experience with ministries, national registries, health insurers and universities"],
      ["Finance", "Raiffeisen Bank International, Wiener Privatbank SE, VCs, family offices"],
      ["Industry", "Telecom operators, enterprise transformation leaders, Uniqa Versicherung"],
    ],
    netBar: "Project-specific team assembly — the right experts for every phase, every industry, every challenge.", netBadge: "Consulting & Execution",
    pLabel: "Process", pTitle: "From analysis to results in 6–9 months",
    proc: [
      { t: "Initial Meeting", sub: "Week 1", d: "Identify scope, objectives and quick-win potential" },
      { t: "Case Analysis", sub: "Week 2–3", d: "Deep-dive: processes, data, stakeholders, bottlenecks" },
      { t: "Strategy Plan", sub: "Week 4–5", d: "Action plan with KPIs, responsibilities, milestones" },
      { t: "Execution", sub: "Month 2–6", d: "Operational implementation, AI integration, change management" },
      { t: "Revenue Impact", sub: "Month 6–9", d: "Measurable OPEX reduction and activated revenue streams" },
    ],
    pBar: ["Total duration:", "6–9 months", "from first meeting to measurable revenue impact"], pBadge: "Committed Timeline",
  },
  re: {
    nav: [["profil", "Profile"], ["expertise", "Expertise"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    h1: ["Sound Analysis.", "Precise Structuring.", "Secure Closing."],
    heroP: "Over EUR 600M in transactions across residential, commercial and hospitality. Deal structuring, project leadership and hands-on execution — from sale to acquisition.",
    ctaA: "Our services", ctaB: "Profile",
    stats: [{ v: "€600m+", l: "Transaction volume advised" }, { v: "25+", l: "Years of real estate & hospitality" }, { v: "3", l: "Asset classes: residential, commercial, hotel" }, { v: "AT · CEE · ES", l: "Transaction markets" }],
    partnerTitle: "Clients & Partners",
    profileLabel: "Founder & Managing Partner",
    profile: {
      key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
      role: "Founder & Managing Partner", focus: "Legal · Transactions · Real Estate",
      paras: [
        "Lawyer and serial CEO with over 25 years of real estate and hospitality experience. Transaction record exceeding EUR 600 million across residential, commercial and hotel portfolios.",
        "Trusted advisor and project lead for institutional investors, family offices and developers across Austria, CEE, Canary Islands and beyond. Active network partner with EPI Immobilien Group and leading Austrian hospitality operators.",
      ],
      quote: "Thinking like a lawyer. Acting like an entrepreneur. Executing with high impact.",
      cards: [
        ["Residential", "EPI Immobilien Group, Trimmobilien Gruppe, Conwert AG, Akkadia Immobilien"],
        ["Commercial & Office", "Strategic advisory on commercial acquisitions and disposals"],
        ["Hotel & Hospitality", "EPI Hospitality, Ibis Group, Arcotel Hotels — hotel transactions & advisory"],
        ["Retail & Mixed Use", "Mixed-use project advisory and transaction structuring"],
        ["Development Projects", "Project development advisory, feasibility, regulatory coordination"],
        ["Sale & Acquisition", "End-to-end buy-side and sell-side transaction management"],
      ],
    },
    tLabel: "Real Estate Expertise", tTitle: "From first analysis to successful closing.",
    tP: "Deep market knowledge, legal precision and operational execution. We structure and lead real estate transactions — always with the goal of a clean, timely, value-maximising result.",
    opexT: "Transaction & Advisory",
    opex: ["Strategic market and feasibility analysis", "Full due diligence process: legal, financial, technical and commercial", "Financing and equity structuring advisory", "Stakeholder management and negotiation leadership", "Regulatory and zoning process coordination"],
    revT: "Sale, Acquisition & Project Leadership",
    rev: ["Buy-side and sell-side mandate management", "Project development oversight from concept to handover", "Hospitality repositioning and brand advisory", "Cross-border deal sourcing (CEE, Spain)", "Distressed asset advisory and restructuring"],
    kpis: [{ v: "EUR 600M+", l: "transaction record across asset classes" }, { v: "25+", l: "years of real estate advisory & execution" }, { v: "CEE & Spain", l: "transaction reach across markets" }],
    sLabel: "Services", sTitle: "What we do in Real Estate & Hospitality",
    serv: [
      { t: "Transaction Advisory", d: "Buy-side and sell-side mandate execution. Market analysis, full due diligence (legal, financial, technical) and structuring.", tags: ["Acquisitions", "Sales", "Due Diligence"] },
      { t: "Project Management & Leadership", d: "Hands-on project leadership for development, refurbishment and repositioning. Budget, timeline, contractor and authority management.", tags: ["Project Mgmt", "Development", "Execution"] },
      { t: "Hospitality Advisory", d: "Strategic advisory for hotel and F&B assets: repositioning, brand selection, operator negotiations and value-add identification.", tags: ["Hotels", "F&B", "Repositioning"] },
      { t: "RE Structuring & Legal", d: "Transaction structuring, corporate law, financing coordination and closing documentation. Cross-border execution.", tags: ["Structuring", "Legal", "Cross-Border"] },
      { t: "Sparring & Negotiating", d: "Strategic sparring for complex negotiation situations. Positioning, counter-party analysis and deal dynamics — we prepare and lead negotiations to protect and maximise your outcome.", tags: ["Sparring", "Negotiation", "Advisory"] },
      { t: "Closing Deals", d: "One goal: the deal closes. We drive transactions to completion — managing stakeholders, timelines and final documentation. Because the only result that counts is a signed deal.", tags: ["Closing", "Execution", "Results"] },
    ],
    netLabel: "Network & Execution", netTitle: "The right team for every challenge.",
    netP: "We don't just advise — we execute. With the right experts, assembled project-specifically from a proven network spanning legal, real estate, finance, industry and technology.",
    clusters: [
      ["Legal", "DSC Rechtsanwälte, Herbst Kinsky RAe — RE, corporate & transaction law. Small specialised boutiques."],
      ["Real Estate", "EPI Immobilien Group, Akkadia Immobilien, Arcotel Hotels, Plaza Group"],
      ["Finance", "Raiffeisen Bank International, Wiener Privatbank SE, family offices"],
      ["Industry", "Uniqa Versicherung, City of Vienna, construction & development partners"],
      ["Tech & AI", "PropTech, digital asset management, AI process automation"],
    ],
    netBar: "Project-specific team assembly — the right experts for every phase, every asset class, every negotiation.", netBadge: "Consulting & Execution",
    pLabel: "Process", pTitle: "From first brief to successful closing",
    proc: [
      { t: "Initial Brief", sub: "Week 1", d: "Define mandate, objectives, timeline and key constraints" },
      { t: "Market & Asset Analysis", sub: "Week 2–3", d: "Deep analysis: market data, legal framework, risk assessment" },
      { t: "Strategy & Structuring", sub: "Week 3–5", d: "Transaction structure, financing approach, negotiation strategy" },
      { t: "Execution & Negotiation", sub: "Month 2–4", d: "Active deal management, stakeholder negotiation, authority coordination" },
      { t: "Closing & Handover", sub: "Month 3–6", d: "Successful closing, documentation, post-closing integration" },
    ],
    pBar: ["Typical transaction timeline:", "3–6 months", "from mandate to successful closing"], pBadge: "Hands-On Execution",
  },
},

// ─────────────────────────────────────────────────────────────── DE
de: {
  meta: {
    home: "InVentures — Company Building, Recht, Kapital & Technologie",
    tech: "Tech & AI — InVentures",
    re: "Real Estate & Hospitality — InVentures",
    notFound: "Seite nicht gefunden — InVentures",
  },
  ui: {
    entity: "Ein Projekt der Inside Holding & Real Estate GmbH",
    entityLong: "InVentures, ein Projekt der Inside Holding & Real Estate GmbH",
    back: "Zurück zur Übersicht",
    menu: "Menü",
    since06: "Seit 2006", since15: "Seit 2015",
    imprint: "Impressum", privacy: "Datenschutz", cookies: "Cookie-Einstellungen",
    trackTech: "Tech & AI", trackRe: "Real Estate",
    switchTrack: "Bereich schließen",
    notFoundTitle: "Seite nicht gefunden.",
    notFoundText: "Die gesuchte Seite existiert nicht oder wurde verschoben.",
  },
  homeNav: [["team", "Management"], ["regulated", "Regulated Ventures"], ["track-record", "Track Record"], ["kontakt", "Kontakt"]],
  home: {
    brandSub: "Venture Building in AI & Real Estate",
    brandP: "Company Building, rechtliche Strukturierung, Kapital und Technologie aus einem Team – für Ventures und Transformationen in regulierten Märkten. Von der ersten Idee bis zum messbaren Impact.",
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "Zwei Disziplinen. Eine Venture-Plattform.",
    selectSub: "Wählen Sie Ihren Bereich",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI-Transformation · Regulierte Plattformen · Company Building", tags: ["AI-Transformation", "DSGVO / AI Act", "Gesundheit & Bildung", "Company Building"], cta: "Tech & AI entdecken" },
      re: { label: "Real Estate &\nHospitality", sub: "Verkauf & Ankauf · Transaktionen · Projektleitung", tags: ["Verkauf & Ankauf", "Transaktionen", "Projektleitung", "Hospitality"], cta: "Real Estate entdecken" },
    },
  },
  team: {
    label: "Management",
    title: "Zwei Partner. Ein eingespieltes Team.",
    intro: "InVentures wird von zwei geschäftsführenden Partnern geführt, die seit Jahren zusammenarbeiten. David Brainin verantwortet Recht, Kapital und Company Building, Philip Kügler Technologie, Architektur und Delivery. Zusammen decken wir ab, was Ventures in regulierten Märkten brauchen – von der ersten Struktur bis zur Plattform im Betrieb.",
    people: [
      {
        key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
        role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        bio: "Jurist, Startup-Founder und Mehrfach-CEO mit über 25 Jahren operativer Verantwortung. Transaction Record von über EUR 600 Mio. in sechs Branchen, Gründer der Geolad GmbH, 2015 von Deutscher Telekom und A1 mit dem Aufbau neuer digitaler Revenue Streams beauftragt. Fundierte Praxis in DSGVO und EU AI Act.",
        facts: [{ v: "€600m+", l: "beratenes Transaktionsvolumen" }, { v: "€45m+", l: "mobilisiertes VC- & Wachstumskapital" }, { v: "€12m+", l: "eingeworbene Forschungsförderungen" }],
      },
      {
        key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver",
        role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Delivery",
        bio: "Enterprise Architect, Programm-Manager und CTO mit über 25 Jahren in IT-Groß- und Transformationsprojekten. Plattformen für öffentliche Hand, Gesundheit, Bildung, Finanz und Telekom – vom IT-Aufbau einer nationalen Krankenversicherung bis zu den Zollsystemen des österreichischen Finanzministeriums. IT-Sicherheit, Datenschutz und Hochverfügbarkeit als Architekturprinzip.",
        facts: [{ v: "4", l: "nationale Regierungsprogramme" }, { v: "100+", l: "integrierte Mobilfunkbetreiber in 15 Ländern" }, { v: "30+", l: "Systeme in eine nationale Plattform integriert" }],
      },
    ],
    bondsLabel: "Was wir zusammenbringen",
    bonds: [
      { t: "Regulierte Märkte", d: "Gesundheit, Bildung, öffentliche Hand, Finanz, Immobilien: Wir kennen die Spielregeln dieser Märkte – rechtlich wie technisch." },
      { t: "Sensible Daten", d: "DSGVO inklusive besonderer Datenkategorien, Datenschutz-Folgenabschätzung, EU AI Act, ISO-27001- und BSI-Anforderungen – vom ersten Tag an in Architektur und Geschäftsmodell verankert." },
      { t: "Vom Konzept bis zum Betrieb", d: "Gründung, Governance, Finanzierung, Architektur, Rollout und Betrieb – ein Team, keine Reibungsverluste zwischen Strategie und Umsetzung." },
    ],
    cta: "Projekt besprechen",
  },
  regulated: {
    label: "Regulated Ventures",
    title: "Plattformen für sensible Daten brauchen mehr als gute Software.",
    intro: "Wer mit Gesundheits-, Bildungs- oder Behördendaten arbeitet, braucht eine belastbare Rechtsgrundlage, eine sichere Architektur, Finanzierung über die Pilotphase hinaus – und Partner, die das schon gemacht haben. Genau hier überschneiden sich unsere Erfahrungen.",
    pillars: [
      { t: "Company Building & Kapital", who: "David Brainin", d: "Gründung, Governance, Beteiligungsstrukturen und Go-to-Market – dazu über EUR 45 Mio. mobilisiertes Venture- und Wachstumskapital und über EUR 12 Mio. eingeworbene Forschungsförderungen." },
      { t: "Recht & Compliance", who: "David Brainin", d: "DSGVO für besondere Kategorien personenbezogener Daten, Datenschutz-Folgenabschätzung, Auftragsverarbeitung und Risikoklassifizierung nach EU AI Act – rechtlich tragfähig vor der ersten Zeile Code." },
      { t: "Security by Design", who: "Philip Kügler", d: "ISO-27001-, BSI- und DSGVO-Anforderungen gemeinsam mit Datenschutz- und Sicherheitsverantwortlichen umgesetzt; Identity- und Access-Management und Single Sign-on (Keycloak, OIDC/SAML); sichere internationale Datenübertragung." },
      { t: "Architektur & Betrieb", who: "Philip Kügler", d: "Hochverfügbare Plattformen für Behörden, Gesundheit und Bildung: Integration von 30+ Umfeldsystemen, Backup- und Failover-Konzepte, Rollout und Betriebsübergabe." },
    ],
    fieldsLabel: "Wo wir geliefert haben",
    fields: [
      { t: "Gesundheit & Wissenschaft", items: ["IT-Aufbau einer nationalen Krankenversicherung (Katar, mit McKinsey)", "European Stroke Organisation", "Sigmund Freud PrivatUniversität Wien"] },
      { t: "Bildung", items: ["Untis – Integration Bund–Land–Schule, Identity-Management & SSO", "Donau-Universität Krems", "TU Wien – Lehre und Gastvorträge"] },
      { t: "Öffentliche Hand", items: ["Bundesministerium für Finanzen / Zoll – Import-Stream im Unionszollkodex (> EUR 10 Mio., 30+ Systeme)", "Nationale ePassport-, ID-Karten- und Grenzkontrollsysteme", "Stadt Wien"] },
      { t: "Gesellschaft", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    closing: "Das Ergebnis: Plattformen, denen Fachkräfte, Institutionen und Behörden ihre Daten anvertrauen können.",
  },
  timeline: { label: "Track Record", title: "20 Jahre. Ein roter Faden.", sub: "Von Wiener Immobilientransaktionen über globale Telekom-Datenplattformen bis zur KI-Advisory – ein gezielter Weg durch die relevanten Industrien." },
  clients: { label: "Ausgewählte Kunden & Partner", fo: "+ nicht genannte Family Offices" },
  groups: { telecom: "Telekom & Data", public: "Öffentliche Hand & Gesundheit", edu: "Bildung & Wissenschaft", finance: "Finanz & Payments", industry: "Industrie & Technologie", re: "Immobilien & Hospitality", legal: "Recht, Medien & Gesellschaft" },
  contact: {
    label: "Kontakt", title: "Sprechen wir.",
    p: "Für strategische Anfragen, Projekte in regulierten Märkten, Partnerschaften oder Accelerator-Bewerbungen.",
    web: "Web", mail: "E-Mail", loc: "Standort", locV: "Wien, Österreich", entity: "Rechtsträger",
    form: {
      name: "Name", company: "Unternehmen", email: "E-Mail-Adresse", topic: "Interessensbereich", message: "Nachricht",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulierte Märkte / Joint Venture", "Sonstiges"],
      namePh: "Ihr Name", companyPh: "Unternehmen (optional)", emailPh: "sie@unternehmen.at", messagePh: "Beschreiben Sie kurz Ihr Anliegen oder Projekt …",
      submit: "Anfrage senden", sending: "Wird gesendet …",
      privacy: "Ihre Daten werden verarbeitet gemäß unserer", privacyLink: "Datenschutzerklärung",
      success: "Vielen Dank – Ihre Anfrage wurde versendet. Wir melden uns in Kürze.",
      fallbackTitle: "Ihre Anfrage konnte nicht automatisch versendet werden.",
      fallbackText: "Bitte senden Sie sie stattdessen per E-Mail – wir haben die Nachricht für Sie vorbereitet.",
      fallbackBtn: "E-Mail öffnen", fallbackOr: "oder direkt an",
      required: "Bitte geben Sie Ihren Namen und eine gültige E-Mail-Adresse an.",
    },
  },
  insights: { label: "Forschung & Insights", title: "News & Publikationen", sub: "Kuratierte Artikel, Berichte und Marktanalysen.", all: "Alle", more: "Mehr anzeigen", read: "Artikel lesen" },
  tech: {
    nav: [["team", "Management"], ["compliance", "Compliance"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    h1: ["Tiefe Analyse.", "Schnelle Umsetzung.", "Hoher Impact."],
    heroP: "Strategisches Sparring, AI-gestützte Unternehmenstransformation und Agentic-AI-Implementierung – und digitale Plattformen für regulierte Märkte, in denen Datenschutz Voraussetzung ist, nicht Option. OPEX-Reduktion und neue Revenue Streams, messbar innerhalb von 6 bis 9 Monaten.",
    ctaA: "Unsere Leistungen", ctaB: "Das Team",
    stats: [{ v: "€45m+", l: "Mobilisiertes VC- & Wachstumskapital" }, { v: "€12m+", l: "Eingeworbene Forschungsförderungen" }, { v: "4", l: "Nationale Regierungsprogramme" }, { v: "100+", l: "Integrierte Mobilfunkbetreiber in 15 Ländern" }, { v: "40+", l: "Projekte in DACH & MENA" }, { v: "50+", l: "Jahre gemeinsame Erfahrung" }],
    partnerTitle: "Kunden & Partner",
    teamLabel: "Management",
    teamTitle: "Recht, Kapital und Technologie – aus einem Team.",
    teamIntro: "Zwei geschäftsführende Partner, die seit Jahren zusammenarbeiten – und gemeinsam verantworten, was sie empfehlen.",
    profiles: [
      {
        key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
        role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        paras: [
          "Jurist, Startup-Founder und Mehrfach-CEO mit über 25 Jahren operativer Erfahrung. Transaction Record von über EUR 600 Mio. über sechs Branchen hinweg – von Telekom über Immobilien und Hospitality bis Wissenschaft und Social Impact.",
          "Bereits 2015 als Pionier von der Deutschen Telekom und A1 Group beauftragt, neue digitale Revenue Streams zu entwickeln. Gründer und CEO der Geolad GmbH – Telekom-Datenplattform mit 30+ Mitarbeitern und Partnern in EU und Asien.",
          "Fundierte Kenntnisse in DSGVO sowie EU AI Act in Theorie und Enterprise-Praxis.",
        ],
        quote: "Juristisch denkend. Unternehmerisch handelnd. Mit hohem Impact umsetzend.",
        cards: [
          ["Telekom & Data", "Deutsche Telekom, A1 Group, Orange, Zain, Viettel, Huawei, Ericsson"],
          ["Wissenschaft & Bildung", "European Stroke Organisation, Sigmund Freud PrivatUniversität Wien, Donau-Universität Krems"],
          ["Immobilien", "Wiener Privatbank SE, EPI Immobilien Group, Uniqa Versicherung"],
          ["Legal", "Lansky & Partner RAe, Herbst Kinsky"],
          ["Hospitality", "EPI Hospitality, Ibis Group, Arcotel Hotels"],
          ["Social Impact", "Integrationshaus Wien, ORF, Red Bull, Verein vidid"],
        ],
      },
      {
        key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver",
        role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Delivery",
        paras: [
          "Enterprise Architect, Programm-Manager und CTO mit über 25 Jahren Erfahrung in IT-Groß- und Transformationsprojekten. Schwerpunkt der letzten Jahre: öffentliche Hand, Finanz und Bildung – Großprojekte, in denen IT-Sicherheit, Datenschutz und Hochverfügbarkeit nicht verhandelbar sind.",
          "IT-Aufbau einer nationalen Krankenversicherung (Katar, mit McKinsey), Product Owner Import im Zollsystem des Bundesministeriums für Finanzen, nationale ePassport- und Grenzkontrollsysteme sowie die Integration von über 100 Mobilfunkbetreibern in 15 Ländern mit einem Team von 50+ auf drei Kontinenten.",
          "Identity- und Access-Management (Keycloak, OIDC/SAML) für Bund, Länder und Schulen; ISO-27001-, BSI- und DSGVO-Anforderungen gemeinsam mit Datenschutz- und Sicherheitsverantwortlichen umgesetzt. CTO & Co-Founder von OptInk, Geschäftsführer der Merkit Consulting FlexCo. MSc Medieninformatik (TU Wien, mit Auszeichnung), IPMA Level C, iREB.",
        ],
        quote: "Systemisch denkend. Pragmatisch bauend. Verlässlich betreibend.",
        cards: [
          ["Öffentliche Hand", "BMF / Zoll (Unionszollkodex), ePassport & Grenzkontrolle, zentrales Melderegister"],
          ["Gesundheit", "Nationale Krankenversicherung Katar (McKinsey / Supreme Council of Health)"],
          ["Bildung", "Untis – Integration Bund–Land–Schule, IAM & SSO; TU Wien"],
          ["Finanz & Payments", "Global Blue, Arthur D. Little (m-Payment), Core-Banking-Integration"],
          ["Telekom & Plattformen", "Telekom Austria, VeriSign / 3united – 100+ Mobilfunkbetreiber in 15 Ländern"],
          ["Ventures & Industrie", "OptInk, Merkit Consulting, Porsche Informatik (Volkswagen), RISE, Match Maker Ventures"],
        ],
      },
    ],
    comp: {
      label: "Datenschutz, Sicherheit & AI-Regulierung",
      title: "DSGVO, EU AI Act, ISO 27001 – von Anfang an.",
      p: "Seit Inkrafttreten der DSGVO 2018 beraten und implementieren wir Datenschutz-Compliance über mehrere Branchen hinweg – und bauen Plattformen, deren Architektur den Anforderungen von Behörden, Versicherern und Schulen standhalten muss. Rechtliche Bewertung und technische Umsetzung kommen aus einem Team.",
      cols: [
        { t: "Recht & Regulierung", who: "David Brainin", items: [
          "8 Jahre hands-on DSGVO-Implementierung in Telekom, Immobilien, Hospitality und Science",
          "Besondere Kategorien personenbezogener Daten (Art. 9 DSGVO): Rechtsgrundlage, Einwilligung, Verarbeitungskonzepte",
          "Datenschutz-Folgenabschätzungen für AI-Systeme und automatisierte Entscheidungsfindung",
          "EU AI Act Readiness: Risikoklassifizierung, Konformitätsbewertungen, Dokumentationspflichten",
          "Cross-Border-Datentransfer-Strukturierung (EU, MENA, ASEAN) unter Schrems-II-Anforderungen",
        ] },
        { t: "Sicherheit & Architektur", who: "Philip Kügler", items: [
          "Sicherheitsanforderungen nach ISO 27001, BSI und ITIL – umgesetzt mit Datenschutz- und Sicherheitsverantwortlichen",
          "Identity- und Access-Management und SSO-Rollouts (Keycloak, OIDC/SAML) in gewachsenen Behördenumgebungen",
          "Sichere internationale Datenübertragung und IT-Compliance-Prozessmodelle",
          "Hochverfügbarkeits-, Backup- und Failover-Architekturen für kritische nationale Systeme",
          "Privacy by Design und AI-Governance in der Datenarchitektur – inklusive Enablement der Teams",
        ] },
      ],
    },
    tLabel: "AI Transformation & Implementation", tTitle: "OPEX-Reduktion & neue Revenue Streams",
    tP: "Wir transformieren Unternehmen nicht theoretisch – wir implementieren messbare Ergebnisse. Drei Hebel: operative Kosten senken, neue Revenue Streams erschließen – und Agentic AI implementieren, die autonom innerhalb Ihrer Organisation handelt. Alles nachweisbar innerhalb von 6 bis 9 Monaten.",
    opexT: "OPEX-Reduktion",
    opex: ["AI-gestützte Automatisierung repetitiver Prozesse", "Reduktion manueller Fehlerquoten und Nacharbeitskosten", "Intelligentes Dokumentenmanagement und Vertragsanalyse", "Konsolidierung fragmentierter Datenquellen und Systeme", "Predictive Maintenance statt reaktiver Kostentreiber"],
    revT: "Neue Revenue Streams",
    rev: ["Datenmonetarisierung aus bestehenden Unternehmensassets", "AI-gestützte Produkt- und Serviceentwicklung", "Digitale Plattform- und Marktplatzmodelle", "Cross-Selling durch intelligente Kundenanalyse", "Skalierbare SaaS-Komponenten aus internen Lösungen"],
    kpis: [{ v: "6–9", u: " Monate", l: "bis zum messbaren Ergebnis" }, { v: "30%+", l: "typische OPEX-Ersparnis in Zielprozessen" }, { v: "Net New", l: "Revenue Streams aus bestehenden Assets", gold: true }],
    sLabel: "Leistungen", sTitle: "Wie wir wirken",
    serv: [
      { t: "Strategic Sparring & Advisory", d: "Strategische Reflexion auf Augenhöhe mit CEOs und Vorständen. Cross-Sektor-Perspektive. Transaktionsbegleitung. Interim Management.", tags: ["CEO-Sparring", "Transaktionen", "Interim"] },
      { t: "AI & Data Consulting", d: "Branchenspezifische AI-Beratung vom Assessment bis zur Implementierung. AI-Agenten, Datenplattformen, Predictive Analytics – DSGVO- und EU-AI-Act-konform.", tags: ["AI-Agents", "Data Strategy", "EU AI Act"] },
      { t: "AI Transformation & Implementation", d: "End-to-End AI-Transformation. Workflow-Automatisierung, intelligentes Dokumentenmanagement, Change Management für AI-gestützte Arbeitsprozesse.", tags: ["Automatisierung", "Implementierung", "Dashboards"] },
      { t: "Agentic AI — Pioneer & Deploy", d: "Konzeption und Deployment autonomer Multi-Agent-Systeme in Ihrem Unternehmen oder Partnernetzwerk. Von der Orchestrierungsarchitektur bis zur Produktion: AI, die eigenständig handelt, Engpässe beseitigt und nachhaltigen operativen Mehrwert schafft.", tags: ["Agentic AI", "Multi-Agent", "Autonom"] },
      { t: "Plattformen für regulierte Märkte", d: "Konzeption, Aufbau und Betrieb digitaler Plattformen für Gesundheit, Bildung und öffentliche Hand: Rechtsgrundlage, Sicherheitsarchitektur, Identity-Management, Förderstrategie und Rollout – aus einem Team.", tags: ["Gesundheit & Bildung", "Öffentliche Hand", "Security by Design"] },
      { t: "Company Building, Joint Ventures & Accelerator", d: "Ventures aufbauen mit Founder-Erfahrung: Ideation, Gründung, Joint-Venture-Strukturen, Fundraising und Förderungen, internationale Skalierung – plus Fast-Track-Programm für Early-Stage-Teams.", tags: ["Company Building", "Joint Ventures", "Fundraising"] },
    ],
    netLabel: "Netzwerk & Execution", netTitle: "Das richtige Team für jede Herausforderung.",
    netP: "Nicht nur Beratung – Umsetzung. Mit den richtigen Expertinnen und Experten, projektspezifisch zusammengestellt aus einem bewährten Netzwerk in Recht, Technologie, Immobilien, Finanz und Industrie.",
    clusters: [
      ["Legal", "Gesellschafts-, IP- & Regulierungsrecht – Lansky & Partner RAe, Herbst Kinsky"],
      ["Tech & AI", "Enterprise-Architekten, Security- & IAM-Spezialisten, AI- und Data-Engineers, Product Builder"],
      ["Öffentliche Hand & Gesundheit", "Erfahrung mit Ministerien, nationalen Registern, Krankenversicherern und Universitäten"],
      ["Finance", "Raiffeisen Bank International, Wiener Privatbank SE, VCs, Family Offices"],
      ["Industry", "Telekom-Operatoren, Enterprise-Transformationsexperten, Uniqa Versicherung"],
    ],
    netBar: "Projektspezifische Team-Zusammenstellung – die richtigen Experten für jede Phase, jede Branche, jede Herausforderung.", netBadge: "Consulting & Execution",
    pLabel: "Prozess", pTitle: "Von der Analyse zum Ergebnis in 6–9 Monaten",
    proc: [
      { t: "Erstgespräch", sub: "Woche 1", d: "Scope, Ziele und Quick-Win-Potenziale identifizieren" },
      { t: "Case-Analyse", sub: "Woche 2–3", d: "Tiefenanalyse: Prozesse, Daten, Stakeholder, Engpässe" },
      { t: "Strategieplan", sub: "Woche 4–5", d: "Maßnahmenplan mit KPIs, Verantwortlichkeiten, Meilensteinen" },
      { t: "Umsetzung", sub: "Monat 2–6", d: "Operative Implementierung, AI-Integration, Change Management" },
      { t: "Revenue Impact", sub: "Monat 6–9", d: "Messbare OPEX-Reduktion und aktivierte Revenue Streams" },
    ],
    pBar: ["Gesamtdauer:", "6–9 Monate", "vom Erstgespräch bis zum messbaren Revenue Impact"], pBadge: "Verbindlicher Zeitrahmen",
  },
  re: {
    nav: [["profil", "Profil"], ["expertise", "Expertise"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    h1: ["Fundierte Analyse.", "Präzise Strukturierung.", "Sicheres Closing."],
    heroP: "Über EUR 600 Mio. in Transaktionen in Wohn-, Gewerbe- und Hospitality-Immobilien. Deal-Strukturierung, Projektleitung und operative Umsetzung – vom Verkauf bis zum Ankauf.",
    ctaA: "Unsere Leistungen", ctaB: "Profil",
    stats: [{ v: "€600m+", l: "Beratenes Transaktionsvolumen" }, { v: "25+", l: "Jahre Immobilien & Hospitality" }, { v: "3", l: "Asset-Klassen: Wohnen, Gewerbe, Hotel" }, { v: "AT · CEE · ES", l: "Transaktionsmärkte" }],
    partnerTitle: "Kunden & Partner",
    profileLabel: "Founder & Managing Partner",
    profile: {
      key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
      role: "Founder & Managing Partner", focus: "Recht · Transaktionen · Real Estate",
      paras: [
        "Jurist und Mehrfach-CEO mit über 25 Jahren Immobilien- und Hospitality-Erfahrung. Transaction Record von über EUR 600 Mio. in Wohn-, Gewerbe- und Hotel-Portfolios.",
        "Vertrauenspartner und Projektleiter für institutionelle Investoren, Family Offices und Developer in Österreich, CEE und auf den Kanarischen Inseln. Aktiver Netzwerkpartner der EPI Immobilien Group und führender österreichischer Hospitality-Operators.",
      ],
      quote: "Juristisch denkend. Unternehmerisch handelnd. Mit hohem Impact umsetzend.",
      cards: [
        ["Wohnimmobilien", "EPI Immobilien Group, Trimmobilien Gruppe, Conwert AG, Akkadia Immobilien"],
        ["Gewerbe & Büro", "Strategische Beratung bei gewerblichen An- und Verkäufen"],
        ["Hotel & Hospitality", "EPI Hospitality, Ibis Group, Arcotel Hotels – Hotel-Transaktionen & Advisory"],
        ["Retail & Mixed Use", "Mixed-Use-Projektberatung und Transaktionsstrukturierung"],
        ["Entwicklungsprojekte", "Projektentwicklungsberatung, Machbarkeit, Behördenkoordination"],
        ["Verkauf & Ankauf", "End-to-End Buy-Side- und Sell-Side-Mandatsbetreuung"],
      ],
    },
    tLabel: "Real Estate Expertise", tTitle: "Von der ersten Analyse bis zum erfolgreichen Closing.",
    tP: "Tiefes Marktwissen, rechtliche Präzision und operative Umsetzung. Wir strukturieren und leiten Immobilientransaktionen – immer mit dem Ziel eines sauberen, termingerechten, wertoptimierenden Ergebnisses.",
    opexT: "Transaktion & Advisory",
    opex: ["Strategische Markt- und Machbarkeitsanalyse", "Vollständiger Due-Diligence-Prozess: rechtlich, finanziell, technisch und kaufmännisch", "Finanzierungs- und Eigenkapitalstrukturierung", "Stakeholder-Management und Verhandlungsführung", "Behörden- und Widmungsprozesskoordination"],
    revT: "Verkauf, Ankauf & Projektleitung",
    rev: ["Buy-Side- und Sell-Side-Mandatsführung", "Projektentwicklungssteuerung von der Planung bis zur Übergabe", "Hospitality-Repositionierung und Markenberatung", "Grenzüberschreitendes Deal-Sourcing (CEE, Spanien)", "Advisory bei Distressed Assets und Restrukturierung"],
    kpis: [{ v: "EUR 600M+", l: "Transaction Record über Asset-Klassen" }, { v: "25+", l: "Jahre Immobilienberatung & Execution" }, { v: "CEE & Spanien", l: "Transaktionsraum über Märkte" }],
    sLabel: "Leistungen", sTitle: "Wie wir im Bereich Real Estate & Hospitality wirken",
    serv: [
      { t: "Transaktions-Advisory", d: "Buy-Side- und Sell-Side-Mandatsbetreuung. Marktanalyse, vollständige Due Diligence (rechtlich, finanziell, technisch) und Strukturierung.", tags: ["Ankauf", "Verkauf", "Due Diligence"] },
      { t: "Projektmanagement & -leitung", d: "Operative Projektleitung bei Entwicklung, Sanierung und Repositionierung. Budget, Zeitplan, Generalunternehmer- und Behördenmanagement.", tags: ["Projektleitung", "Entwicklung", "Execution"] },
      { t: "Hospitality Advisory", d: "Strategische Beratung für Hotel- und F&B-Assets: Repositionierung, Markenwahl, Operatorverhandlungen und Wertsteigerungspotenziale.", tags: ["Hotels", "F&B", "Repositionierung"] },
      { t: "RE-Strukturierung & Legal", d: "Transaktionsstrukturierung, Gesellschaftsrecht, Finanzierungskoordination und Closing-Dokumentation. Grenzüberschreitende Execution.", tags: ["Strukturierung", "Legal", "Cross-Border"] },
      { t: "Sparring & Verhandlung", d: "Strategisches Sparring für komplexe Verhandlungssituationen. Positionierung, Gegenparteienanalyse und Deal-Dynamik – wir bereiten Verhandlungen vor und führen sie, um Ihr Ergebnis zu schützen und zu maximieren.", tags: ["Sparring", "Verhandlung", "Advisory"] },
      { t: "Deal Closing", d: "Ein Ziel: Der Deal wird abgeschlossen. Wir treiben Transaktionen zum Abschluss – Stakeholder-Management, Timelines und finale Dokumentation. Denn das einzige Ergebnis, das zählt, ist ein unterzeichneter Vertrag.", tags: ["Closing", "Execution", "Ergebnisse"] },
    ],
    netLabel: "Netzwerk & Execution", netTitle: "Das richtige Team für jede Herausforderung.",
    netP: "Nicht nur Beratung – Umsetzung. Mit den richtigen Expertinnen und Experten, projektspezifisch zusammengestellt aus einem bewährten Netzwerk in Recht, Immobilien, Finanz, Industrie und Technologie.",
    clusters: [
      ["Legal", "DSC Rechtsanwälte, Herbst Kinsky RAe – Immobilien-, Gesellschafts- & Transaktionsrecht. Kleine spezialisierte Boutiquen."],
      ["Real Estate", "EPI Immobilien Group, Akkadia Immobilien, Arcotel Hotels, Plaza Group"],
      ["Finance", "Raiffeisen Bank International, Wiener Privatbank SE, Family Offices"],
      ["Industry", "Uniqa Versicherung, Stadt Wien, Bau- & Entwicklungspartner"],
      ["Tech & AI", "PropTech, digitales Asset-Management, AI-Prozessautomatisierung"],
    ],
    netBar: "Projektspezifische Team-Zusammenstellung – die richtigen Experten für jede Phase, jede Asset-Klasse, jede Verhandlung.", netBadge: "Consulting & Execution",
    pLabel: "Prozess", pTitle: "Vom ersten Briefing bis zum erfolgreichen Closing",
    proc: [
      { t: "Erstbriefing", sub: "Woche 1", d: "Mandat, Ziele, Zeitplan und Rahmenbedingungen definieren" },
      { t: "Markt- & Asset-Analyse", sub: "Woche 2–3", d: "Tiefenanalyse: Marktdaten, rechtlicher Rahmen, Risikobeurteilung" },
      { t: "Strategie & Strukturierung", sub: "Woche 3–5", d: "Transaktionsstruktur, Finanzierungsansatz, Verhandlungsstrategie" },
      { t: "Execution & Verhandlung", sub: "Monat 2–4", d: "Aktives Deal-Management, Stakeholder-Verhandlung, Behördenkoordination" },
      { t: "Closing & Übergabe", sub: "Monat 3–6", d: "Erfolgreiches Closing, Dokumentation, Post-Closing-Integration" },
    ],
    pBar: ["Typischer Transaktionszeitraum:", "3–6 Monate", "vom Mandat bis zum erfolgreichen Closing"], pBadge: "Operative Execution",
  },
},

// ─────────────────────────────────────────────────────────────── 中文
cn: {
  meta: {
    home: "InVentures — 公司建设、法律、资本与技术",
    tech: "技术与AI — InVentures",
    re: "房地产与酒店业 — InVentures",
    notFound: "页面未找到 — InVentures",
  },
  ui: {
    entity: "Inside Holding & Real Estate GmbH 旗下项目",
    entityLong: "InVentures，Inside Holding & Real Estate GmbH 旗下项目",
    back: "返回总览",
    menu: "菜单",
    since06: "始于2006年", since15: "始于2015年",
    imprint: "法律声明", privacy: "隐私政策", cookies: "Cookie 设置",
    trackTech: "技术与AI", trackRe: "房地产",
    switchTrack: "关闭板块",
    notFoundTitle: "页面未找到。",
    notFoundText: "您要访问的页面不存在或已被移动。",
  },
  homeNav: [["team", "管理团队"], ["regulated", "受监管领域"], ["track-record", "发展历程"], ["kontakt", "联系"]],
  home: {
    brandSub: "AI 与房地产领域的 Venture Building",
    brandP: "公司建设、法律架构、资本与技术，由同一团队提供——服务于受监管市场中的创业项目与转型。从最初构想到可衡量的成果。",
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "两大领域。一个 Venture 平台。",
    selectSub: "请选择您的领域",
    tracks: {
      tech: { label: "技术与AI", sub: "AI转型 · 受监管平台 · 公司建设", tags: ["AI转型", "GDPR / AI法案", "医疗与教育", "公司建设"], cta: "了解技术与AI" },
      re: { label: "房地产与\n酒店业", sub: "销售与收购 · 交易 · 项目领导", tags: ["销售与收购", "交易", "项目管理", "酒店业"], cta: "了解房地产" },
    },
  },
  team: {
    label: "管理团队",
    title: "两位合伙人，一支默契的团队。",
    intro: "InVentures由两位多年合作的管理合伙人共同领导。David Brainin负责法律、资本与公司建设；Philip Kügler负责技术、架构与交付。我们共同覆盖受监管市场中创业项目所需的一切——从最初的架构设计到平台的稳定运行。",
    people: [
      {
        key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
        role: "创始人兼管理合伙人", focus: "法律 · 资本 · 公司建设",
        bio: "法律专家、创业者及连续CEO，拥有超过25年的运营管理经验。横跨六大行业的交易记录超过6亿欧元；Geolad GmbH创始人；2015年受德国电信和A1集团委托开发新的数字收入来源。在GDPR与欧盟AI法案方面拥有扎实的实践经验。",
        facts: [{ v: "€600m+", l: "顾问交易总额" }, { v: "€45m+", l: "动员的风投与成长资本" }, { v: "€12m+", l: "获得的研究资助" }],
      },
      {
        key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver",
        role: "技术管理合伙人", focus: "架构 · 安全 · 交付",
        bio: "企业架构师、项目集经理及CTO，拥有超过25年大型IT与转型项目经验。为公共部门、医疗、教育、金融和电信领域构建平台——从一个国家医疗保险体系的IT建设，到奥地利财政部的海关系统。以IT安全、数据保护与高可用性为架构原则。",
        facts: [{ v: "4", l: "国家级政府项目" }, { v: "100+", l: "在15个国家集成的移动运营商" }, { v: "30+", l: "集成至同一国家级平台的系统" }],
      },
    ],
    bondsLabel: "我们的共同优势",
    bonds: [
      { t: "受监管市场", d: "医疗、教育、公共部门、金融、房地产：我们在法律和技术两方面都熟知这些市场的规则。" },
      { t: "敏感数据", d: "GDPR（包括特殊类别数据）、数据保护影响评估、欧盟AI法案、ISO 27001与BSI要求——从第一天起融入架构与商业模式。" },
      { t: "从构想到运营", d: "公司设立、治理、融资、架构、上线与运营——同一团队，从战略到执行无缝衔接。" },
    ],
    cta: "洽谈项目",
  },
  regulated: {
    label: "受监管领域创业",
    title: "处理敏感数据的平台，需要的不只是好软件。",
    intro: "处理医疗、教育或政府数据的项目，需要坚实的法律基础、安全的架构、超越试点阶段的资金保障——以及有过成功经验的合作伙伴。这正是我们经验的交汇点。",
    pillars: [
      { t: "公司建设与资本", who: "David Brainin", d: "公司设立、治理、股权结构与市场进入——并已动员超过4500万欧元的风险与成长资本，获得超过1200万欧元的研究资助。" },
      { t: "法律与合规", who: "David Brainin", d: "针对特殊类别个人数据的GDPR合规、数据保护影响评估、数据处理协议及欧盟AI法案风险分级——在编写第一行代码之前确保法律基础稳固。" },
      { t: "安全设计", who: "Philip Kügler", d: "与数据保护及安全负责人共同落实ISO 27001、BSI与GDPR要求；身份与访问管理及单点登录（Keycloak、OIDC/SAML）；安全的国际数据传输。" },
      { t: "架构与运营", who: "Philip Kügler", d: "为政府、医疗和教育构建高可用平台：30多个周边系统集成、备份与故障切换方案、上线及运维交接。" },
    ],
    fieldsLabel: "我们的实践领域",
    fields: [
      { t: "医疗与科研", items: ["国家医疗保险体系的IT建设（卡塔尔，与麦肯锡合作）", "欧洲卒中组织", "维也纳西格蒙德·弗洛伊德私立大学"] },
      { t: "教育", items: ["Untis——联邦、州与学校系统集成、身份管理与单点登录", "多瑙大学克雷姆斯", "维也纳技术大学——教学与客座讲座"] },
      { t: "公共部门", items: ["奥地利联邦财政部／海关——欧盟海关法典进口流程（逾1000万欧元，30多个系统）", "国家电子护照、身份证与边境管控系统", "维也纳市"] },
      { t: "社会", items: ["维也纳融合之家", "vidid协会", "ORF"] },
    ],
    closing: "最终成果：让专业人士、机构与政府部门能够放心托付数据的平台。",
  },
  timeline: { label: "发展历程", title: "20年。一条主线。", sub: "从维也纳房地产到全球电信数据平台，再到AI咨询——跨越关键行业的清晰路径。" },
  clients: { label: "部分客户与合作伙伴", fo: "+ 非公开家族办公室" },
  groups: { telecom: "电信与数据", public: "公共部门与医疗", edu: "教育与科研", finance: "金融与支付", industry: "产业与技术", re: "房地产与酒店业", legal: "法律、媒体与社会" },
  contact: {
    label: "联系", title: "联系我们。",
    p: "欢迎战略咨询、受监管市场项目、合作机会或加速器申请。",
    web: "网站", mail: "电子邮件", loc: "地点", locV: "奥地利维也纳", entity: "法律实体",
    form: {
      name: "姓名", company: "公司", email: "电子邮件地址", topic: "感兴趣领域", message: "留言",
      topics: ["技术与AI", "房地产与酒店业", "受监管市场／合资项目", "其他"],
      namePh: "您的姓名", companyPh: "公司（可选）", emailPh: "您的邮箱", messagePh: "请简要描述您的咨询或项目……",
      submit: "发送咨询", sending: "发送中……",
      privacy: "您的数据将依据我们的", privacyLink: "隐私政策处理",
      success: "感谢您的咨询，我们已收到并将尽快与您联系。",
      fallbackTitle: "您的咨询未能自动发送。",
      fallbackText: "请改用电子邮件发送——我们已为您准备好邮件内容。",
      fallbackBtn: "打开邮件", fallbackOr: "或直接发送至",
      required: "请填写您的姓名和有效的电子邮件地址。",
    },
  },
  insights: { label: "研究与洞察", title: "新闻与出版物", sub: "精选文章、报告与市场分析。", all: "全部", more: "显示更多", read: "阅读文章" },
  tech: {
    nav: [["team", "管理团队"], ["compliance", "合规"], ["leistungen", "服务"], ["netzwerk", "网络"], ["prozess", "流程"], ["kontakt", "联系"]],
    h1: ["深度分析。", "快速执行。", "高效成果。"],
    heroP: "战略顾问、AI驱动的企业转型与智能体AI实施——以及面向受监管市场的数字平台，在这些市场中数据保护是前提而非选项。运营成本降低与新收入来源，6至9个月内可衡量。",
    ctaA: "我们的服务", ctaB: "团队介绍",
    stats: [{ v: "€45m+", l: "动员的风投与成长资本" }, { v: "€12m+", l: "获得的研究资助" }, { v: "4", l: "国家级政府项目" }, { v: "100+", l: "在15个国家集成的移动运营商" }, { v: "40+", l: "DACH与中东北非地区项目" }, { v: "50+", l: "合计从业年限" }],
    partnerTitle: "客户与合作伙伴",
    teamLabel: "管理团队",
    teamTitle: "法律、资本与技术——同一团队。",
    teamIntro: "两位多年合作的管理合伙人——对自己的建议共同负责。",
    profiles: [
      {
        key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
        role: "创始人兼管理合伙人", focus: "法律 · 资本 · 公司建设",
        paras: [
          "法律专家、创业者及连续CEO，拥有超过25年的运营经验。横跨六大行业的交易记录超过6亿欧元——涵盖电信、房地产、酒店业、科研与社会公益。",
          "2015年受德国电信和A1集团委托，率先开发新的数字收入来源。Geolad GmbH创始人兼CEO——一家拥有30多名员工、合作伙伴遍布欧洲和亚洲的跨国电信数据平台。",
          "在GDPR与欧盟AI法案的理论与企业实践方面拥有深厚知识。",
        ],
        quote: "以法律思维思考。以企业家方式行动。以高成效付诸实施。",
        cards: [
          ["电信与数据", "德国电信, A1集团, Orange, Zain, Viettel, 华为, 爱立信"],
          ["科研与教育", "欧洲卒中组织, 维也纳西格蒙德·弗洛伊德私立大学, 多瑙大学克雷姆斯"],
          ["房地产", "维也纳私人银行, EPI不动产集团, Uniqa保险"],
          ["法律", "Lansky & Partner RAe, Herbst Kinsky"],
          ["酒店业", "EPI Hospitality, Ibis集团, Arcotel酒店"],
          ["社会公益", "维也纳融合之家, ORF, 红牛, vidid协会"],
        ],
      },
      {
        key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver",
        role: "技术管理合伙人", focus: "架构 · 安全 · 交付",
        paras: [
          "企业架构师、项目集经理及CTO，拥有超过25年大型IT与转型项目经验。近年聚焦公共部门、金融与教育——主导大型项目，在这些项目中IT安全、数据保护与高可用性不容妥协。",
          "主导卡塔尔国家医疗保险体系的IT建设（与麦肯锡合作）；担任奥地利联邦财政部海关系统进口模块产品负责人；参与国家电子护照与边境管控系统建设；带领横跨三大洲的50余人团队，在15个国家集成100多家移动运营商。",
          "为联邦、州及学校管理系统构建身份与访问管理（Keycloak、OIDC/SAML）；与数据保护及安全负责人共同落实ISO 27001、BSI与GDPR要求。OptInk首席技术官兼联合创始人，Merkit Consulting FlexCo总经理。维也纳技术大学媒体信息学硕士（优异毕业），IPMA C级认证，iREB认证。",
        ],
        quote: "系统化思考。务实地构建。可靠地运行。",
        cards: [
          ["公共部门", "奥地利财政部／海关、电子护照与边境管控、中央户籍登记"],
          ["医疗", "卡塔尔国家医疗保险（麦肯锡／最高卫生委员会）"],
          ["教育", "Untis——联邦、州与学校系统集成、身份管理与单点登录；维也纳技术大学"],
          ["金融与支付", "Global Blue、理特咨询（移动支付）、核心银行系统集成"],
          ["电信与平台", "奥地利电信、VeriSign / 3united——在15个国家集成100多家移动运营商"],
          ["创业与产业", "OptInk、Merkit Consulting、保时捷信息技术（大众集团）、RISE、Match Maker Ventures"],
        ],
      },
    ],
    comp: {
      label: "数据保护、安全与AI监管",
      title: "GDPR、欧盟AI法案、ISO 27001——从第一天开始。",
      p: "自2018年GDPR生效以来，我们在多个行业提供数据保护合规咨询与实施，并构建了必须满足政府、保险机构及学校要求的平台。法律评估与技术实施由同一团队完成。",
      cols: [
        { t: "法律与监管", who: "David Brainin", items: [
          "在电信、房地产、酒店业和科研领域8年的GDPR实施经验",
          "特殊类别个人数据（GDPR第9条）：法律依据、同意机制与处理方案",
          "针对AI系统和自动化决策的数据保护影响评估",
          "欧盟AI法案就绪：风险分类、合规评估、文档义务",
          "Schrems II要求下的跨境数据传输架构（欧盟、中东北非、东盟）",
        ] },
        { t: "安全与架构", who: "Philip Kügler", items: [
          "依据ISO 27001、BSI与ITIL的安全要求——与数据保护及安全负责人共同落实",
          "在复杂的公共部门环境中实施身份与访问管理及单点登录（Keycloak、OIDC/SAML）",
          "安全的国际数据传输与IT合规流程模型",
          "关键国家系统的高可用、备份与故障切换架构",
          "在数据架构中落实隐私设计与AI治理——包括团队赋能",
        ] },
      ],
    },
    tLabel: "AI转型与实施", tTitle: "运营成本优化与新收入来源",
    tP: "不做理论转型——实现可衡量的结果。三大杠杆：降低运营成本、开拓新收入来源，并率先实施能在组织内自主运作的智能体AI。一切在6至9个月内可验证。",
    opexT: "运营成本优化",
    opex: ["AI驱动重复流程自动化", "降低人工错误率和返工成本", "智能文档管理与合同分析", "整合碎片化数据源和系统", "预测性维护取代被动成本驱动"],
    revT: "新收入来源",
    rev: ["从现有企业资产中实现数据变现", "AI驱动的产品与服务开发", "数字平台与市场模式", "通过智能客户分析实现交叉销售", "从内部解决方案构建可扩展SaaS组件"],
    kpis: [{ v: "6–9", u: " 个月", l: "达到可衡量成果" }, { v: "30%+", l: "目标流程运营成本节省" }, { v: "全新", l: "来自现有资产的收入来源", gold: true }],
    sLabel: "服务", sTitle: "我们如何发挥作用",
    serv: [
      { t: "战略顾问与咨询", d: "与CEO和董事会平等对话的战略反思。跨行业视角。交易支持。临时管理。", tags: ["CEO顾问", "交易", "临时管理"] },
      { t: "AI与数据咨询", d: "从准备度评估到运营实施的行业AI咨询。AI代理、数据平台、预测分析——符合GDPR与欧盟AI法案。", tags: ["AI代理", "数据战略", "欧盟AI法案"] },
      { t: "AI转型与实施", d: "端到端AI转型。工作流自动化、智能文档管理、AI驱动工作流程的变革管理。", tags: ["自动化", "实施", "仪表盘"] },
      { t: "智能体AI——开拓与部署", d: "在您的组织或合作网络中设计并部署自主多智能体系统。从编排架构到生产环境：能够独立行动、消除瓶颈并持续创造运营价值的AI。", tags: ["智能体AI", "多智能体", "自主"] },
      { t: "受监管市场平台", d: "为医疗、教育和公共部门设计、构建并运营数字平台：法律依据、安全架构、身份管理、资助策略与上线——由同一团队完成。", tags: ["医疗与教育", "公共部门", "安全设计"] },
      { t: "公司建设、合资与加速器", d: "以创始人经验打造创业项目：创意、设立、合资架构、融资与资助、国际化扩展——并为早期团队提供快速通道计划。", tags: ["公司建设", "合资企业", "融资"] },
    ],
    netLabel: "网络与执行", netTitle: "为每个挑战组建合适的团队。",
    netP: "不仅提供咨询——更付诸实施。从法律、技术、房地产、金融到产业的成熟网络中，根据项目需求组建专家团队。",
    clusters: [
      ["法律", "企业、知识产权及监管——Lansky & Partner RAe, Herbst Kinsky"],
      ["技术与AI", "企业架构师、安全与身份管理专家、AI与数据工程师、产品构建者"],
      ["公共部门与医疗", "与部委、国家登记系统、医疗保险机构及大学合作的经验"],
      ["金融", "Raiffeisen银行国际、维也纳私人银行、风险投资、家族办公室"],
      ["行业", "电信运营商、企业转型领导者、Uniqa保险"],
    ],
    netBar: "根据项目需求组建团队——为每个阶段、每个行业、每个挑战匹配合适的专家。", netBadge: "咨询与执行",
    pLabel: "流程", pTitle: "从分析到成果：6–9个月",
    proc: [
      { t: "初次会议", sub: "第1周", d: "确定范围、目标和速赢潜力" },
      { t: "案例分析", sub: "第2–3周", d: "深度分析：流程、数据、利益相关方、瓶颈" },
      { t: "战略规划", sub: "第4–5周", d: "包含KPI、责任分配和里程碑的行动计划" },
      { t: "执行实施", sub: "第2–6月", d: "运营实施、AI集成、变革管理" },
      { t: "收入成效", sub: "第6–9月", d: "可衡量的运营成本降低和已激活的收入来源" },
    ],
    pBar: ["总周期：", "6–9个月", "从首次会议到可衡量的收入成效"], pBadge: "承诺时间框架",
  },
  re: {
    nav: [["profil", "简介"], ["expertise", "专业"], ["leistungen", "服务"], ["netzwerk", "网络"], ["prozess", "流程"], ["kontakt", "联系"]],
    h1: ["深入分析。", "精准架构。", "稳妥交割。"],
    heroP: "超过6亿欧元的住宅、商业和酒店地产交易记录。交易结构设计、项目领导和实际执行——从出售到收购。",
    ctaA: "我们的服务", ctaB: "简介",
    stats: [{ v: "€600m+", l: "顾问交易总额" }, { v: "25+", l: "年房地产与酒店业经验" }, { v: "3", l: "资产类别：住宅、商业、酒店" }, { v: "AT · CEE · ES", l: "交易市场" }],
    partnerTitle: "客户与合作伙伴",
    profileLabel: "创始人兼管理合伙人",
    profile: {
      key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold",
      role: "创始人兼管理合伙人", focus: "法律 · 交易 · 房地产",
      paras: [
        "法律专家及连续CEO，拥有超过25年的房地产和酒店业经验。在住宅、商业和酒店资产组合中的交易记录超过6亿欧元。",
        "为奥地利、中东欧、加那利群岛等地的机构投资者、家族办公室和开发商提供可信赖的顾问和项目领导服务。EPI不动产集团及奥地利领先酒店运营商的活跃网络合作伙伴。",
      ],
      quote: "以法律思维思考。以企业家方式行动。以高成效付诸实施。",
      cards: [
        ["住宅", "EPI不动产集团, Trimmobilien集团, Conwert AG, Akkadia Immobilien"],
        ["商业与办公", "商业收购和处置战略咨询"],
        ["酒店与餐饮", "EPI Hospitality, Ibis集团, Arcotel酒店——酒店交易与咨询"],
        ["零售与综合用途", "综合用途项目咨询和交易结构设计"],
        ["开发项目", "项目开发咨询、可行性研究、监管协调"],
        ["销售与收购", "端到端买方和卖方交易管理"],
      ],
    },
    tLabel: "房地产专业知识", tTitle: "从首次分析到成功交割。",
    tP: "深厚的市场知识、法律精准度和运营执行力。我们为房地产交易提供结构设计和项目领导——始终以干净、及时、价值最大化的结果为目标。",
    opexT: "交易与顾问",
    opex: ["战略市场和可行性分析", "完整尽职调查：法律、财务、技术和商业", "融资和股权结构咨询", "利益相关方管理和谈判领导", "监管和规划流程协调"],
    revT: "销售、收购与项目领导",
    rev: ["买方和卖方授权管理", "从概念到交付的项目开发监督", "酒店重新定位和品牌咨询", "跨境交易来源（中东欧、西班牙）", "不良资产咨询和重组"],
    kpis: [{ v: "6亿欧元+", l: "跨资产类别交易记录" }, { v: "25+", l: "年房地产咨询与执行经验" }, { v: "中东欧与西班牙", l: "跨市场交易覆盖" }],
    sLabel: "服务", sTitle: "我们如何在房地产与酒店业发挥作用",
    serv: [
      { t: "交易顾问", d: "买方和卖方授权执行。市场分析、完整尽职调查（法律、财务、技术）与结构设计。", tags: ["收购", "销售", "尽职调查"] },
      { t: "项目管理与领导", d: "开发、翻新和重新定位项目的实际领导。预算、时间表、承包商和政府机构管理。", tags: ["项目管理", "开发", "执行"] },
      { t: "酒店顾问", d: "酒店和餐饮资产的战略咨询：重新定位、品牌选择、运营商谈判与增值机会识别。", tags: ["酒店", "餐饮", "重新定位"] },
      { t: "房地产结构设计与法律", d: "交易结构、公司法、融资协调和交割文件。跨境执行。", tags: ["结构设计", "法律", "跨境"] },
      { t: "战略顾问与谈判", d: "为复杂谈判提供战略顾问。定位、对手方分析与交易动态——我们准备并主导谈判，以保障并最大化您的成果。", tags: ["顾问", "谈判", "咨询"] },
      { t: "促成交割", d: "唯一目标：完成交易。我们推动交易直至完成——管理利益相关方、时间表和最终文件。因为唯一重要的结果是签署的合同。", tags: ["交割", "执行", "成果"] },
    ],
    netLabel: "网络与执行", netTitle: "为每个挑战组建合适的团队。",
    netP: "不仅提供咨询——更付诸实施。从法律、房地产、金融、产业到技术的成熟网络中，根据项目需求组建专家团队。",
    clusters: [
      ["法律", "DSC律所、Herbst Kinsky RAe——房地产、公司及交易法。小型专业精品律所。"],
      ["房地产", "EPI不动产集团、Akkadia Immobilien、Arcotel酒店、Plaza集团"],
      ["金融", "Raiffeisen银行国际、维也纳私人银行、家族办公室"],
      ["行业", "Uniqa保险、维也纳市、建筑与开发合作伙伴"],
      ["技术与AI", "房地产科技、数字资产管理、AI流程自动化"],
    ],
    netBar: "根据项目需求组建团队——为每个阶段、每类资产、每次谈判匹配合适的专家。", netBadge: "咨询与执行",
    pLabel: "流程", pTitle: "从首次简报到成功交割",
    proc: [
      { t: "初次简报", sub: "第1周", d: "定义授权、目标、时间表和关键约束条件" },
      { t: "市场与资产分析", sub: "第2–3周", d: "深度分析：市场数据、法律框架、风险评估" },
      { t: "战略与结构设计", sub: "第3–5周", d: "交易结构、融资方案、谈判策略" },
      { t: "执行与谈判", sub: "第2–4月", d: "积极的交易管理、利益相关方谈判、政府协调" },
      { t: "交割与移交", sub: "第3–6月", d: "成功交割、文件记录、交割后整合" },
    ],
    pBar: ["典型交易周期：", "3–6个月", "从授权到成功交割"], pBadge: "实际执行",
  },
},
};
