// All user-visible copy of the /new site (EN / DE / 中文). Short by design: facts first.
// Facts about David Brainin come from the live site; facts about Philip Kügler from his CV (released by him, 2026-09).

export const LANGS = [["en", "EN"], ["de", "DE"], ["cn", "中文"]];
export const HTML_LANG = { en: "en", de: "de", cn: "zh-Hans" };

const PEOPLE = { david: { key: "david", name: "Mag. David Brainin", initials: "DB", accent: "gold", photo: "portrait-brainin" }, philip: { key: "philip", name: "Philip Kügler, MSc", initials: "PK", accent: "silver", photo: "portrait-kuegler" } };

export const TX = {
// ─────────────────────────────────────────────────────────────── EN
en: {
  meta: { home: "InVentures — Company Building, Legal, Capital & Technology", tech: "Tech & AI — InVentures", re: "Real Estate & Hospitality — InVentures", notFound: "Page not found — InVentures" },
  ui: {
    entity: "A project of Inside Holding & Real Estate GmbH", entityLong: "InVentures, a project of Inside Holding & Real Estate GmbH",
    back: "Back to overview", menu: "Menu", since06: "Since 2006", since15: "Since 2015",
    imprint: "Imprint", privacy: "Privacy Policy", cookies: "Cookie Settings", trackTech: "Tech & AI", trackRe: "Real Estate", switchTrack: "Close track",
    notFoundTitle: "Page not found.", notFoundText: "This page does not exist or has moved.",
    readArticle: "Read full article", closeArticle: "Collapse article", showRefs: "Show sectors & clients", hideRefs: "Hide sectors & clients",
  },
  homeNav: [["team", "Team"], ["regulated", "Regulated Ventures"], ["track-record", "Track Record"], ["kontakt", "Contact"]],
  home: {
    brandSub: "Venture Building in AI & Real Estate",
    brandP: "We build ventures in regulated markets — law, capital and technology from one team.",
    chapters: ["Areas", "Clients", "Team", "Expertise", "References", "Track Record", "Contact"],
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "Two disciplines. One platform.", selectSub: "Choose your area",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI transformation, regulated platforms, company building", tags: ["AI Transformation", "GDPR & AI Act", "Health & Education", "Company Building"], cta: "Explore Tech & AI" },
      re: { label: "Real Estate &\nHospitality", sub: "Sale & acquisition, transactions, project leadership", tags: ["Sale & Acquisition", "Transactions", "Project Leadership", "Hospitality"], cta: "Explore Real Estate" },
    },
  },
  team: {
    label: "Team", title: "Two partners. 50+ years of experience.",
    intro: "Law, capital and company building meet architecture, security and delivery — a team for years.",
    people: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        bio: "Lawyer, founder and serial CEO. 25+ years of operational responsibility, EUR 600m+ in transactions, founder of Geolad. GDPR and EU AI Act in practice.",
        facts: [{ v: "€600m+", l: "Transactions" }, { v: "€45m+", l: "Capital raised" }, { v: "€12m+", l: "Research grants" }] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        bio: "Enterprise architect and CTO. 25+ years of large IT programmes for government, health, education and telecom — from customs to a national health insurance.",
        facts: [{ v: "10+", l: "Years in government projects" }, { v: "12", l: "Direct client mandates" }, { v: "30+", l: "Systems integrated" }] },
    ],
    bondsLabel: "What we combine",
    bonds: [
      { t: "Regulated markets", d: "Health, education, public sector, finance, real estate." },
      { t: "Sensitive data", d: "GDPR, AI Act, ISO 27001 — from day one." },
      { t: "Concept to operation", d: "Incorporation, funding, architecture, rollout. One team." },
    ],
    cta: "Discuss a project",
  },
  regulated: {
    label: "Regulated Ventures", title: "Sensitive data needs more than software.",
    intro: "A legal basis, a secure architecture, funding — and partners who have done it before.",
    pillars: [
      { t: "Company Building & Capital", who: "David Brainin", d: "Incorporation, governance, go-to-market. €45m+ capital, €12m+ grants." },
      { t: "Legal & Compliance", who: "David Brainin", d: "Art. 9 GDPR, impact assessments, AI Act classification." },
      { t: "Security by Design", who: "Philip Kügler", d: "ISO 27001, BSI, identity and access management." },
      { t: "Architecture & Operations", who: "Philip Kügler", d: "High availability, 30+ systems integrated, rollout to operations." },
    ],
    fieldsLabel: "References",
    fields: [
      { t: "Health & Science", items: ["National health insurance Qatar (with McKinsey)", "European Stroke Organisation", "Sigmund Freud University Vienna"] },
      { t: "Education", items: ["Untis — IAM for federal, state and schools", "Danube University Krems", "TU Wien"] },
      { t: "Public Sector", items: ["Austrian Ministry of Finance — customs", "ePassport & border control", "City of Vienna"] },
      { t: "Society", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    closing: "The result: platforms that professionals, institutions and authorities entrust with their data.",
    refLabel: "References", refTitle: "Proven in health, education and government.", refIntro: "Platforms where failure is not an option.",
  },
  timeline: { label: "Track Record", title: "Two paths. Joint projects since 2016.", sub: "Real estate, telecom data, government platforms — and joint ventures.", joint: "Together", more: "Show full track record", less: "Show highlights only" },
  clients: { label: "Clients & partners", title: "Trusted by corporates, authorities and investors.", fo: "+ undisclosed family offices" },
  groups: { telecom: "Telecom & Data", public: "Public Sector & Health", edu: "Education & Science", finance: "Finance & Payments", industry: "Industry & Technology", re: "Real Estate & Hospitality", legal: "Legal, Media & Society" },
  contact: {
    label: "Contact", title: "Let's talk.", p: "Strategy, regulated-market projects, partnerships.",
    web: "Web", mail: "E-mail", loc: "Location", locV: "Vienna, Austria", entity: "Legal entity",
    form: {
      name: "Name", company: "Company", email: "E-mail", topic: "Topic", message: "Message",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulated markets / joint venture", "Other"],
      namePh: "Your name", companyPh: "Optional", emailPh: "you@company.com", messagePh: "Your enquiry in a few lines",
      submit: "Send", sending: "Sending…",
      privacy: "We process your data according to our", privacyLink: "privacy policy",
      success: "Thank you — we will be in touch shortly.",
      fallbackTitle: "Could not send automatically.", fallbackText: "Please send it by e-mail — the message is prepared.",
      fallbackBtn: "Open e-mail", fallbackOr: "or write to", required: "Please enter your name and a valid e-mail address.",
    },
  },
  insights: { label: "Insights", title: "What moves the market.", sub: "Selected analyses since February 2026.", all: "All", more: "Show more", read: "Read" },
  tech: {
    nav: [["team", "Team"], ["compliance", "Compliance"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    chapters: ["Team", "Compliance", "Transformation", "Services", "Network", "Process", "Contact", "Insights"],
    h1: ["Deep Analysis.", "Fast Execution.", "High Impact."],
    heroP: "AI transformation, agentic AI and platforms for regulated markets. Measurable results in 6–9 months.",
    ctaA: "Services", ctaB: "Team",
    stats: [{ v: "€45m+", l: "Capital raised" }, { v: "€12m+", l: "Research grants" }, { v: "10+", l: "Years in government projects" }, { v: "30+", l: "Systems integrated" }, { v: "40+", l: "Projects DACH & MENA" }, { v: "50+", l: "Years of combined experience" }],
    partnerTitle: "Clients & partners",
    teamLabel: "Team", teamTitle: "Law, capital, technology. One team.", teamIntro: "",
    profiles: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        paras: ["Lawyer, startup founder and serial CEO. 25+ years of operational experience, EUR 600m+ in transactions across six sectors.",
          "Pioneer mandate from Deutsche Telekom and A1 in 2015. Founder and CEO of Geolad (30+ staff, EU & Asia). GDPR and EU AI Act in practice."],
        quote: "Thinking like a lawyer. Acting like an entrepreneur. Executing with impact.",
        cards: [["Telecom & Data", "Deutsche Telekom, A1, Orange, Zain, Viettel, Huawei, Ericsson"], ["Science & Education", "European Stroke Organisation, Sigmund Freud University, Danube University Krems"], ["Real Estate", "Wiener Privatbank, EPI Immobilien, UNIQA"], ["Legal", "Lansky, Ganzger & Partner, Herbst Kinsky"], ["Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Social Impact", "Integrationshaus Wien, ORF, Red Bull, vidid"]] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        paras: ["Enterprise architect, programme manager and CTO. 25+ years of large IT programmes — focus on public sector, finance and education.",
          "National health insurance Qatar (with McKinsey), customs imports at the Austrian Ministry of Finance, ePassport and border control. CTO & co-founder of OptInk, MD of Merkit Consulting. MSc TU Wien, IPMA Level C."],
        quote: "Thinking in systems. Building pragmatically. Running reliably.",
        cards: [["Public Sector", "Ministry of Finance / customs, ePassport, border control"], ["Health", "National health insurance Qatar (McKinsey)"], ["Education", "Untis — IAM & SSO for schools; TU Wien"], ["Finance & Payments", "Global Blue, Arthur D. Little, core banking"], ["Telecom", "Telekom Austria, VeriSign / 3united"], ["Ventures", "OptInk, Merkit Consulting, Porsche Informatik, RISE"]] },
    ],
    comp: {
      label: "Data Protection & Security", title: "GDPR, AI Act, ISO 27001 — from day one.",
      p: "Legal assessment and technical implementation from one team.",
      cols: [
        { t: "Legal & Regulatory", who: "David Brainin", items: ["8 years of GDPR practice across four industries", "Art. 9 GDPR: health data and consent", "Impact assessments for AI systems", "AI Act: risk classes, conformity, documentation", "Data transfers EU, MENA, ASEAN (Schrems II)"] },
        { t: "Security & Architecture", who: "Philip Kügler", items: ["ISO 27001, BSI and ITIL implemented", "IAM & SSO: Keycloak, OIDC/SAML", "Secure international data transfer", "High availability, backup, failover", "Privacy by design and AI governance"] },
      ],
    },
    tLabel: "AI Transformation", tTitle: "Lower costs. New revenue.",
    tP: "Three levers: automation, new revenue streams, agentic AI. Proven within 6–9 months.",
    opexT: "OPEX reduction", opex: ["Automation of repetitive processes", "Fewer errors and less rework", "Smart document and contract analysis", "Consolidated data sources"],
    revT: "New revenue", rev: ["Data monetisation", "AI-driven products and services", "Platform and marketplace models", "SaaS from internal solutions"],
    kpis: [{ v: "6–9", u: " months", l: "to results" }, { v: "30%+", l: "OPEX savings" }, { v: "Net New", l: "revenue from existing assets", gold: true }],
    sLabel: "Services", sTitle: "From strategy to operation.",
    serv: [
      { t: "Strategic Sparring & Advisory", d: "C-level sparring, transaction support, interim management.", tags: ["CEO Sparring", "Transactions", "Interim"] },
      { t: "AI & Data Consulting", d: "From readiness assessment to implementation — GDPR and AI Act compliant.", tags: ["AI Agents", "Data Strategy", "EU AI Act"] },
      { t: "AI Transformation", d: "Workflow automation, document management, change management.", tags: ["Automation", "Implementation", "Change"] },
      { t: "Agentic AI", d: "Autonomous multi-agent systems — from architecture to production.", tags: ["Agentic AI", "Multi-Agent", "Autonomous"] },
      { t: "Platforms for Regulated Markets", d: "Health, education, public sector: law, security, funding, rollout.", tags: ["Health & Education", "Public Sector", "Security by Design"] },
      { t: "Company Building & Joint Ventures", d: "Incorporation, JV structures, fundraising, accelerator.", tags: ["Company Building", "Joint Ventures", "Fundraising"] },
    ],
    netLabel: "Network", netTitle: "The right team for every task.", netP: "Specialists in law, technology, finance and industry — assembled per project.",
    clusters: [["Legal", "Corporate, IP, regulatory — Lansky, Ganzger & Partner, Herbst Kinsky"], ["Tech & AI", "Architects, security & IAM, AI and data engineers"], ["Public & Health", "Ministries, registries, insurers, universities"], ["Finance", "RBI, Wiener Privatbank, VCs, family offices"], ["Industry", "Telecom operators, transformation leaders, UNIQA"]],
    netBar: "Advice and execution from one hand.", netBadge: "Consulting & Execution",
    pLabel: "Process", pTitle: "Results in 6–9 months.",
    proc: [{ t: "Kick-off", sub: "Week 1", d: "Scope and quick wins" }, { t: "Analysis", sub: "Week 2–3", d: "Processes, data, bottlenecks" }, { t: "Plan", sub: "Week 4–5", d: "Measures, KPIs, milestones" }, { t: "Execution", sub: "Month 2–6", d: "Implementation, AI integration" }, { t: "Impact", sub: "Month 6–9", d: "Lower OPEX, new revenue" }],
    pBar: ["Total:", "6–9 months", ""], pBadge: "Committed timeline",
  },
  re: {
    nav: [["profil", "Profile"], ["expertise", "Expertise"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    chapters: ["Profile", "Expertise", "Services", "Network", "Process", "Contact", "Insights"],
    profileTitle: "25 years. EUR 600m+ in transactions.",
    h1: ["Sound Analysis.", "Precise Structuring.", "Secure Closing."],
    heroP: "EUR 600m+ in transactions across residential, commercial and hotel. Structuring, project leadership, closing.",
    ctaA: "Services", ctaB: "Profile",
    stats: [{ v: "€600m+", l: "Transactions" }, { v: "25+", l: "Years real estate & hospitality" }, { v: "3", l: "Asset classes" }, { v: "AT · CEE · ES", l: "Markets" }],
    partnerTitle: "Clients & partners",
    profileLabel: "Founder & Managing Partner",
    profile: { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Transactions · Real Estate",
      paras: ["Lawyer and serial CEO. 25+ years in real estate and hospitality, EUR 600m+ in transactions.", "Partner to institutional investors, family offices and developers in Austria, CEE and Spain."],
      quote: "Thinking like a lawyer. Acting like an entrepreneur. Executing with impact.",
      cards: [["Residential", "EPI Immobilien, Trimmobilien, Conwert, Akkadia"], ["Commercial & Office", "Acquisitions and disposals"], ["Hotel & Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Retail & Mixed Use", "Advisory and structuring"], ["Development", "Feasibility, permits, project lead"], ["Sale & Acquisition", "Buy-side and sell-side mandates"]] },
    tLabel: "Real Estate Expertise", tTitle: "From analysis to closing.", tP: "Market knowledge, legal precision, hands-on execution.",
    opexT: "Transaction & Advisory", opex: ["Market and feasibility analysis", "Due diligence: legal, financial, technical", "Financing and equity structure", "Negotiation and authority coordination"],
    revT: "Sale, Acquisition & Projects", rev: ["Buy-side and sell-side mandates", "Development through to handover", "Hotel repositioning", "Deal sourcing CEE & Spain"],
    kpis: [{ v: "€600m+", l: "transaction record" }, { v: "25+", l: "years of execution" }, { v: "CEE & Spain", l: "transaction reach" }],
    sLabel: "Services", sTitle: "Buy, sell, develop — through to signature.",
    serv: [
      { t: "Transaction Advisory", d: "Acquisitions and sales: analysis, due diligence, structuring.", tags: ["Acquisitions", "Sales", "Due Diligence"] },
      { t: "Project Leadership", d: "Development, refurbishment, repositioning — budget, time, authorities.", tags: ["Project Mgmt", "Development", "Execution"] },
      { t: "Hospitality Advisory", d: "Repositioning, brand selection, operator negotiations.", tags: ["Hotels", "F&B", "Repositioning"] },
      { t: "Structuring & Legal", d: "Deal structure, corporate law, closing documentation.", tags: ["Structuring", "Legal", "Cross-Border"] },
      { t: "Sparring & Negotiation", d: "Preparing and leading complex negotiations.", tags: ["Sparring", "Negotiation", "Advisory"] },
      { t: "Closing", d: "We take transactions to signature.", tags: ["Closing", "Execution", "Results"] },
    ],
    netLabel: "Network", netTitle: "The right team for every deal.", netP: "Legal, real estate, finance and industry partners — assembled per mandate.",
    clusters: [["Legal", "DSC Rechtsanwälte, Herbst Kinsky — RE, corporate, transactions"], ["Real Estate", "EPI Immobilien, Akkadia, Arcotel, Plaza"], ["Finance", "RBI, Wiener Privatbank, family offices"], ["Industry", "UNIQA, City of Vienna, construction partners"], ["Tech & AI", "PropTech, digital asset management"]],
    netBar: "Advice and execution from one hand.", netBadge: "Consulting & Execution",
    pLabel: "Process", pTitle: "Closing in 3–6 months.",
    proc: [{ t: "Brief", sub: "Week 1", d: "Mandate, goals, timeline" }, { t: "Analysis", sub: "Week 2–3", d: "Market, legal, risk" }, { t: "Structure", sub: "Week 3–5", d: "Deal, financing, strategy" }, { t: "Negotiation", sub: "Month 2–4", d: "Deal management, authorities" }, { t: "Closing", sub: "Month 3–6", d: "Signature, handover" }],
    pBar: ["Typical:", "3–6 months", "from mandate to closing"], pBadge: "Hands-on execution",
  },
},

// ─────────────────────────────────────────────────────────────── DE
de: {
  meta: { home: "InVentures — Company Building, Recht, Kapital & Technologie", tech: "Tech & AI — InVentures", re: "Real Estate & Hospitality — InVentures", notFound: "Seite nicht gefunden — InVentures" },
  ui: {
    entity: "Ein Projekt der Inside Holding & Real Estate GmbH", entityLong: "InVentures, ein Projekt der Inside Holding & Real Estate GmbH",
    back: "Zur Übersicht", menu: "Menü", since06: "Seit 2006", since15: "Seit 2015",
    imprint: "Impressum", privacy: "Datenschutz", cookies: "Cookie-Einstellungen", trackTech: "Tech & AI", trackRe: "Real Estate", switchTrack: "Bereich schließen",
    notFoundTitle: "Seite nicht gefunden.", notFoundText: "Diese Seite existiert nicht oder wurde verschoben.",
    readArticle: "Ganzen Artikel lesen", closeArticle: "Artikel einklappen", showRefs: "Branchen & Kunden anzeigen", hideRefs: "Branchen & Kunden ausblenden",
  },
  homeNav: [["team", "Team"], ["regulated", "Regulated Ventures"], ["track-record", "Track Record"], ["kontakt", "Kontakt"]],
  home: {
    brandSub: "Venture Building in AI & Real Estate",
    brandP: "Wir bauen Ventures in regulierten Märkten – mit Recht, Kapital und Technologie aus einem Team.",
    chapters: ["Bereiche", "Kunden", "Team", "Kompetenz", "Referenzen", "Track Record", "Kontakt"],
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "Zwei Disziplinen. Eine Plattform.", selectSub: "Bereich wählen",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI-Transformation, regulierte Plattformen, Company Building", tags: ["AI-Transformation", "DSGVO & AI Act", "Gesundheit & Bildung", "Company Building"], cta: "Tech & AI entdecken" },
      re: { label: "Real Estate &\nHospitality", sub: "Verkauf & Ankauf, Transaktionen, Projektleitung", tags: ["Verkauf & Ankauf", "Transaktionen", "Projektleitung", "Hospitality"], cta: "Real Estate entdecken" },
    },
  },
  team: {
    label: "Team", title: "Zwei Partner. Über 50 Jahre Erfahrung.",
    intro: "Recht, Kapital und Company Building trifft Architektur, Sicherheit und Delivery – eingespielt seit Jahren.",
    people: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        bio: "Jurist, Gründer und Mehrfach-CEO. 25+ Jahre operative Verantwortung, Transaktionen über EUR 600 Mio., Gründer der Geolad. DSGVO und EU AI Act in der Praxis.",
        facts: [{ v: "€600m+", l: "Transaktionen" }, { v: "€45m+", l: "Kapital mobilisiert" }, { v: "€12m+", l: "Forschungsförderung" }] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Delivery",
        bio: "Enterprise Architect und CTO. 25+ Jahre IT-Großprojekte für Behörden, Gesundheit, Bildung und Telekom – vom Zoll bis zur nationalen Krankenversicherung.",
        facts: [{ v: "10+", l: "Jahre Regierungsprojekte" }, { v: "12", l: "Direkte Kundenmandate" }, { v: "30+", l: "Systeme integriert" }] },
    ],
    bondsLabel: "Was wir verbinden",
    bonds: [
      { t: "Regulierte Märkte", d: "Gesundheit, Bildung, Behörden, Finanz, Immobilien." },
      { t: "Sensible Daten", d: "DSGVO, AI Act, ISO 27001 – ab Tag eins." },
      { t: "Konzept bis Betrieb", d: "Gründung, Finanzierung, Architektur, Rollout. Ein Team." },
    ],
    cta: "Projekt besprechen",
  },
  regulated: {
    label: "Regulated Ventures", title: "Sensible Daten brauchen mehr als Software.",
    intro: "Rechtsgrundlage, sichere Architektur, Finanzierung – und Partner, die das schon gemacht haben.",
    pillars: [
      { t: "Company Building & Kapital", who: "David Brainin", d: "Gründung, Governance, Go-to-Market. €45m+ Kapital, €12m+ Förderungen." },
      { t: "Recht & Compliance", who: "David Brainin", d: "Art. 9 DSGVO, Folgenabschätzung, AI-Act-Klassifizierung." },
      { t: "Security by Design", who: "Philip Kügler", d: "ISO 27001, BSI, Identity- & Access-Management." },
      { t: "Architektur & Betrieb", who: "Philip Kügler", d: "Hochverfügbar, 30+ Systeme integriert, Rollout bis Betrieb." },
    ],
    fieldsLabel: "Referenzen",
    fields: [
      { t: "Gesundheit & Wissenschaft", items: ["Nationale Krankenversicherung Katar (mit McKinsey)", "European Stroke Organisation", "Sigmund Freud PrivatUniversität"] },
      { t: "Bildung", items: ["Untis – IAM für Bund, Länder, Schulen", "Donau-Universität Krems", "TU Wien"] },
      { t: "Öffentliche Hand", items: ["BMF / Zoll – Unionszollkodex", "ePassport & Grenzkontrolle", "Stadt Wien"] },
      { t: "Gesellschaft", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    closing: "Das Ergebnis: Plattformen, denen Fachkräfte, Institutionen und Behörden ihre Daten anvertrauen.",
    refLabel: "Referenzen", refTitle: "Bewiesen in Gesundheit, Bildung und Verwaltung.", refIntro: "Plattformen, bei denen Fehler keine Option sind.",
  },
  timeline: { label: "Track Record", title: "Zwei Wege. Gemeinsame Projekte seit 2016.", sub: "Immobilien, Telekom-Daten, Regierungsplattformen – und gemeinsame Ventures.", joint: "Gemeinsam", more: "Gesamten Track Record anzeigen", less: "Nur Highlights anzeigen" },
  clients: { label: "Kunden & Partner", title: "Vertraut von Konzernen, Behörden und Investoren.", fo: "+ nicht genannte Family Offices" },
  groups: { telecom: "Telekom & Data", public: "Öffentliche Hand & Gesundheit", edu: "Bildung & Wissenschaft", finance: "Finanz & Payments", industry: "Industrie & Technologie", re: "Immobilien & Hospitality", legal: "Recht, Medien & Gesellschaft" },
  contact: {
    label: "Kontakt", title: "Sprechen wir.", p: "Strategie, Projekte in regulierten Märkten, Partnerschaften.",
    web: "Web", mail: "E-Mail", loc: "Standort", locV: "Wien, Österreich", entity: "Rechtsträger",
    form: {
      name: "Name", company: "Unternehmen", email: "E-Mail", topic: "Thema", message: "Nachricht",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulierte Märkte / Joint Venture", "Sonstiges"],
      namePh: "Ihr Name", companyPh: "Optional", emailPh: "sie@unternehmen.at", messagePh: "Ihr Anliegen in wenigen Zeilen",
      submit: "Senden", sending: "Wird gesendet …",
      privacy: "Wir verarbeiten Ihre Daten gemäß unserer", privacyLink: "Datenschutzerklärung",
      success: "Danke – wir melden uns in Kürze.",
      fallbackTitle: "Automatischer Versand nicht möglich.", fallbackText: "Bitte per E-Mail senden – die Nachricht ist vorbereitet.",
      fallbackBtn: "E-Mail öffnen", fallbackOr: "oder direkt an", required: "Bitte Name und gültige E-Mail-Adresse angeben.",
    },
  },
  insights: { label: "Insights", title: "Was den Markt bewegt.", sub: "Ausgewählte Analysen seit Februar 2026.", all: "Alle", more: "Mehr anzeigen", read: "Lesen" },
  tech: {
    nav: [["team", "Team"], ["compliance", "Compliance"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    chapters: ["Team", "Compliance", "Transformation", "Leistungen", "Netzwerk", "Prozess", "Kontakt", "Insights"],
    h1: ["Tiefe Analyse.", "Schnelle Umsetzung.", "Hoher Impact."],
    heroP: "AI-Transformation, Agentic AI und Plattformen für regulierte Märkte. Messbare Ergebnisse in 6–9 Monaten.",
    ctaA: "Leistungen", ctaB: "Team",
    stats: [{ v: "€45m+", l: "Kapital mobilisiert" }, { v: "€12m+", l: "Forschungsförderung" }, { v: "10+", l: "Jahre Regierungsprojekte" }, { v: "30+", l: "Systeme integriert" }, { v: "40+", l: "Projekte DACH & MENA" }, { v: "50+", l: "Jahre Erfahrung, gemeinsam" }],
    partnerTitle: "Kunden & Partner",
    teamLabel: "Team", teamTitle: "Recht, Kapital, Technologie. Ein Team.", teamIntro: "",
    profiles: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        paras: ["Jurist, Startup-Founder und Mehrfach-CEO. 25+ Jahre operative Erfahrung, Transaktionen über EUR 600 Mio. in sechs Branchen.",
          "2015 Pionierauftrag von Deutscher Telekom und A1. Gründer und CEO der Geolad (30+ Mitarbeiter, EU & Asien). DSGVO und EU AI Act in der Praxis."],
        quote: "Juristisch denkend. Unternehmerisch handelnd. Mit Impact umsetzend.",
        cards: [["Telekom & Data", "Deutsche Telekom, A1, Orange, Zain, Viettel, Huawei, Ericsson"], ["Wissenschaft & Bildung", "European Stroke Organisation, Sigmund Freud PrivatUniversität, Donau-Universität Krems"], ["Immobilien", "Wiener Privatbank, EPI Immobilien, UNIQA"], ["Legal", "Lansky, Ganzger & Partner, Herbst Kinsky"], ["Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Social Impact", "Integrationshaus Wien, ORF, Red Bull, vidid"]] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Delivery",
        paras: ["Enterprise Architect, Programm-Manager und CTO. 25+ Jahre IT-Großprojekte – Schwerpunkt öffentliche Hand, Finanz und Bildung.",
          "Nationale Krankenversicherung Katar (mit McKinsey), Zoll-Import im Finanzministerium, ePassport und Grenzkontrolle. CTO & Co-Founder OptInk, GF Merkit Consulting. MSc TU Wien, IPMA Level C."],
        quote: "Systemisch denkend. Pragmatisch bauend. Verlässlich betreibend.",
        cards: [["Öffentliche Hand", "BMF / Zoll, ePassport, Grenzkontrolle"], ["Gesundheit", "Nationale Krankenversicherung Katar (McKinsey)"], ["Bildung", "Untis – IAM & SSO für Schulen; TU Wien"], ["Finanz & Payments", "Global Blue, Arthur D. Little, Core Banking"], ["Telekom", "Telekom Austria, VeriSign / 3united"], ["Ventures", "OptInk, Merkit Consulting, Porsche Informatik, RISE"]] },
    ],
    comp: {
      label: "Datenschutz & Sicherheit", title: "DSGVO, AI Act, ISO 27001 – ab Tag eins.",
      p: "Rechtliche Bewertung und technische Umsetzung aus einem Team.",
      cols: [
        { t: "Recht & Regulierung", who: "David Brainin", items: ["8 Jahre DSGVO-Praxis in vier Branchen", "Art. 9 DSGVO: Gesundheitsdaten und Einwilligung", "Folgenabschätzung für AI-Systeme", "AI Act: Risikoklassen, Konformität, Dokumentation", "Datentransfers EU, MENA, ASEAN (Schrems II)"] },
        { t: "Sicherheit & Architektur", who: "Philip Kügler", items: ["ISO 27001, BSI und ITIL umgesetzt", "IAM & SSO: Keycloak, OIDC/SAML", "Sichere internationale Datenübertragung", "Hochverfügbarkeit, Backup, Failover", "Privacy by Design und AI-Governance"] },
      ],
    },
    tLabel: "AI-Transformation", tTitle: "Weniger Kosten. Neue Umsätze.",
    tP: "Drei Hebel: Automatisierung, neue Revenue Streams, Agentic AI. Nachweisbar in 6–9 Monaten.",
    opexT: "OPEX-Reduktion", opex: ["Automatisierung repetitiver Prozesse", "Weniger Fehler und Nacharbeit", "Intelligente Dokumenten- und Vertragsanalyse", "Konsolidierte Datenquellen"],
    revT: "Neue Umsätze", rev: ["Datenmonetarisierung", "AI-gestützte Produkte und Services", "Plattform- und Marktplatzmodelle", "SaaS aus internen Lösungen"],
    kpis: [{ v: "6–9", u: " Monate", l: "bis zum Ergebnis" }, { v: "30%+", l: "OPEX-Ersparnis" }, { v: "Net New", l: "Umsatz aus bestehenden Assets", gold: true }],
    sLabel: "Leistungen", sTitle: "Von der Strategie bis zum Betrieb.",
    serv: [
      { t: "Strategic Sparring & Advisory", d: "Sparring auf C-Level, Transaktionsbegleitung, Interim Management.", tags: ["CEO-Sparring", "Transaktionen", "Interim"] },
      { t: "AI & Data Consulting", d: "Vom Readiness-Assessment zur Umsetzung – DSGVO- und AI-Act-konform.", tags: ["AI-Agents", "Data Strategy", "EU AI Act"] },
      { t: "AI-Transformation", d: "Workflow-Automatisierung, Dokumentenmanagement, Change Management.", tags: ["Automatisierung", "Implementierung", "Change"] },
      { t: "Agentic AI", d: "Autonome Multi-Agent-Systeme – von der Architektur bis zur Produktion.", tags: ["Agentic AI", "Multi-Agent", "Autonom"] },
      { t: "Plattformen für regulierte Märkte", d: "Gesundheit, Bildung, Behörden: Recht, Sicherheit, Förderung, Rollout.", tags: ["Gesundheit & Bildung", "Öffentliche Hand", "Security by Design"] },
      { t: "Company Building & Joint Ventures", d: "Gründung, JV-Strukturen, Fundraising, Accelerator.", tags: ["Company Building", "Joint Ventures", "Fundraising"] },
    ],
    netLabel: "Netzwerk", netTitle: "Das richtige Team für jede Aufgabe.", netP: "Spezialisten aus Recht, Technologie, Finanz und Industrie – projektbezogen.",
    clusters: [["Legal", "Gesellschafts-, IP- und Regulierungsrecht – Lansky, Ganzger & Partner, Herbst Kinsky"], ["Tech & AI", "Architekten, Security & IAM, AI- und Data-Engineers"], ["Öffentliche Hand & Gesundheit", "Ministerien, Register, Versicherer, Universitäten"], ["Finance", "RBI, Wiener Privatbank, VCs, Family Offices"], ["Industry", "Telekom-Operatoren, Transformationsexperten, UNIQA"]],
    netBar: "Beratung und Umsetzung aus einer Hand.", netBadge: "Consulting & Execution",
    pLabel: "Prozess", pTitle: "In 6–9 Monaten zum Ergebnis.",
    proc: [{ t: "Kick-off", sub: "Woche 1", d: "Scope und Quick Wins" }, { t: "Analyse", sub: "Woche 2–3", d: "Prozesse, Daten, Engpässe" }, { t: "Plan", sub: "Woche 4–5", d: "Maßnahmen, KPIs, Meilensteine" }, { t: "Umsetzung", sub: "Monat 2–6", d: "Implementierung, AI-Integration" }, { t: "Impact", sub: "Monat 6–9", d: "OPEX runter, Umsatz rauf" }],
    pBar: ["Gesamt:", "6–9 Monate", ""], pBadge: "Verbindlicher Zeitrahmen",
  },
  re: {
    nav: [["profil", "Profil"], ["expertise", "Expertise"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    chapters: ["Profil", "Expertise", "Leistungen", "Netzwerk", "Prozess", "Kontakt", "Insights"],
    profileTitle: "25 Jahre. Über EUR 600 Mio. Transaktionen.",
    h1: ["Fundierte Analyse.", "Präzise Strukturierung.", "Sicheres Closing."],
    heroP: "Über EUR 600 Mio. Transaktionen in Wohnen, Gewerbe und Hotel. Strukturierung, Projektleitung, Closing.",
    ctaA: "Leistungen", ctaB: "Profil",
    stats: [{ v: "€600m+", l: "Transaktionen" }, { v: "25+", l: "Jahre Immobilien & Hospitality" }, { v: "3", l: "Asset-Klassen" }, { v: "AT · CEE · ES", l: "Märkte" }],
    partnerTitle: "Kunden & Partner",
    profileLabel: "Founder & Managing Partner",
    profile: { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Recht · Transaktionen · Real Estate",
      paras: ["Jurist und Mehrfach-CEO. 25+ Jahre Immobilien und Hospitality, Transaktionen über EUR 600 Mio.", "Partner für institutionelle Investoren, Family Offices und Developer in Österreich, CEE und Spanien."],
      quote: "Juristisch denkend. Unternehmerisch handelnd. Mit Impact umsetzend.",
      cards: [["Wohnen", "EPI Immobilien, Trimmobilien, Conwert, Akkadia"], ["Gewerbe & Büro", "An- und Verkäufe"], ["Hotel & Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Retail & Mixed Use", "Beratung und Strukturierung"], ["Entwicklung", "Machbarkeit, Behörden, Projektleitung"], ["Verkauf & Ankauf", "Buy-Side- und Sell-Side-Mandate"]] },
    tLabel: "Real Estate Expertise", tTitle: "Von der Analyse zum Closing.", tP: "Marktwissen, rechtliche Präzision, operative Umsetzung.",
    opexT: "Transaktion & Advisory", opex: ["Markt- und Machbarkeitsanalyse", "Due Diligence: rechtlich, finanziell, technisch", "Finanzierungs- und Eigenkapitalstruktur", "Verhandlung und Behördenkoordination"],
    revT: "Verkauf, Ankauf & Projekte", rev: ["Buy-Side- und Sell-Side-Mandate", "Entwicklung bis zur Übergabe", "Hotel-Repositionierung", "Deal-Sourcing CEE & Spanien"],
    kpis: [{ v: "€600m+", l: "Transaction Record" }, { v: "25+", l: "Jahre Execution" }, { v: "CEE & Spanien", l: "Transaktionsraum" }],
    sLabel: "Leistungen", sTitle: "Ankauf, Verkauf, Projekte – bis zur Unterschrift.",
    serv: [
      { t: "Transaktions-Advisory", d: "Ankauf und Verkauf: Analyse, Due Diligence, Strukturierung.", tags: ["Ankauf", "Verkauf", "Due Diligence"] },
      { t: "Projektleitung", d: "Entwicklung, Sanierung, Repositionierung – Budget, Zeit, Behörden.", tags: ["Projektleitung", "Entwicklung", "Execution"] },
      { t: "Hospitality Advisory", d: "Repositionierung, Markenwahl, Betreiberverhandlungen.", tags: ["Hotels", "F&B", "Repositionierung"] },
      { t: "Strukturierung & Legal", d: "Transaktionsstruktur, Gesellschaftsrecht, Closing-Dokumentation.", tags: ["Strukturierung", "Legal", "Cross-Border"] },
      { t: "Sparring & Verhandlung", d: "Komplexe Verhandlungen vorbereiten und führen.", tags: ["Sparring", "Verhandlung", "Advisory"] },
      { t: "Closing", d: "Wir bringen Transaktionen zur Unterschrift.", tags: ["Closing", "Execution", "Ergebnisse"] },
    ],
    netLabel: "Netzwerk", netTitle: "Das richtige Team für jeden Deal.", netP: "Partner aus Recht, Immobilien, Finanz und Industrie – je Mandat.",
    clusters: [["Legal", "DSC Rechtsanwälte, Herbst Kinsky – Immobilien-, Gesellschafts- und Transaktionsrecht"], ["Real Estate", "EPI Immobilien, Akkadia, Arcotel, Plaza"], ["Finance", "RBI, Wiener Privatbank, Family Offices"], ["Industry", "UNIQA, Stadt Wien, Baupartner"], ["Tech & AI", "PropTech, digitales Asset-Management"]],
    netBar: "Beratung und Umsetzung aus einer Hand.", netBadge: "Consulting & Execution",
    pLabel: "Prozess", pTitle: "In 3–6 Monaten zum Closing.",
    proc: [{ t: "Briefing", sub: "Woche 1", d: "Mandat, Ziele, Zeitplan" }, { t: "Analyse", sub: "Woche 2–3", d: "Markt, Recht, Risiko" }, { t: "Struktur", sub: "Woche 3–5", d: "Deal, Finanzierung, Strategie" }, { t: "Verhandlung", sub: "Monat 2–4", d: "Deal-Management, Behörden" }, { t: "Closing", sub: "Monat 3–6", d: "Unterschrift, Übergabe" }],
    pBar: ["Typisch:", "3–6 Monate", "vom Mandat zum Closing"], pBadge: "Operative Execution",
  },
},

// ─────────────────────────────────────────────────────────────── 中文
cn: {
  meta: { home: "InVentures — 公司建设、法律、资本与技术", tech: "技术与AI — InVentures", re: "房地产与酒店业 — InVentures", notFound: "页面未找到 — InVentures" },
  ui: {
    entity: "Inside Holding & Real Estate GmbH 旗下项目", entityLong: "InVentures，Inside Holding & Real Estate GmbH 旗下项目",
    back: "返回总览", menu: "菜单", since06: "始于2006年", since15: "始于2015年",
    imprint: "法律声明", privacy: "隐私政策", cookies: "Cookie 设置", trackTech: "技术与AI", trackRe: "房地产", switchTrack: "关闭板块",
    notFoundTitle: "页面未找到。", notFoundText: "该页面不存在或已移动。",
    readArticle: "阅读全文", closeArticle: "收起文章", showRefs: "查看行业与客户", hideRefs: "收起行业与客户",
  },
  homeNav: [["team", "团队"], ["regulated", "受监管领域"], ["track-record", "发展历程"], ["kontakt", "联系"]],
  home: {
    brandSub: "AI 与房地产领域的 Venture Building",
    brandP: "我们在受监管市场中打造创业项目——法律、资本与技术，由同一团队提供。",
    chapters: ["领域", "客户", "团队", "能力", "参考", "历程", "联系"],
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "两大领域，一个平台。", selectSub: "选择领域",
    tracks: {
      tech: { label: "技术与AI", sub: "AI转型、受监管平台、公司建设", tags: ["AI转型", "GDPR与AI法案", "医疗与教育", "公司建设"], cta: "了解技术与AI" },
      re: { label: "房地产与\n酒店业", sub: "买卖、交易、项目领导", tags: ["买卖", "交易", "项目领导", "酒店业"], cta: "了解房地产" },
    },
  },
  team: {
    label: "团队", title: "两位合伙人，逾50年经验。",
    intro: "法律、资本与公司建设，结合架构、安全与交付——多年默契合作。",
    people: [
      { ...PEOPLE.david, role: "创始人兼管理合伙人", focus: "法律 · 资本 · 公司建设",
        bio: "法律专家、创业者及连续CEO。25年以上运营经验，交易额逾6亿欧元，Geolad创始人。GDPR与欧盟AI法案实践经验丰富。",
        facts: [{ v: "€600m+", l: "交易额" }, { v: "€45m+", l: "募集资本" }, { v: "€12m+", l: "研究资助" }] },
      { ...PEOPLE.philip, role: "技术管理合伙人", focus: "架构 · 安全 · 交付",
        bio: "企业架构师兼CTO。25年以上为政府、医疗、教育和电信主导大型IT项目——从海关系统到国家医疗保险。",
        facts: [{ v: "10+", l: "年政府项目经验" }, { v: "12", l: "直接客户委托" }, { v: "30+", l: "系统集成" }] },
    ],
    bondsLabel: "我们的结合",
    bonds: [
      { t: "受监管市场", d: "医疗、教育、公共部门、金融、房地产。" },
      { t: "敏感数据", d: "GDPR、AI法案、ISO 27001——从第一天起。" },
      { t: "从构想到运营", d: "设立、融资、架构、上线。同一团队。" },
    ],
    cta: "洽谈项目",
  },
  regulated: {
    label: "受监管领域", title: "敏感数据需要的不只是软件。",
    intro: "法律基础、安全架构、资金保障——以及有经验的合作伙伴。",
    pillars: [
      { t: "公司建设与资本", who: "David Brainin", d: "设立、治理、市场进入。4500万欧元以上资本，1200万欧元以上资助。" },
      { t: "法律与合规", who: "David Brainin", d: "GDPR第9条、影响评估、AI法案分级。" },
      { t: "安全设计", who: "Philip Kügler", d: "ISO 27001、BSI、身份与访问管理。" },
      { t: "架构与运营", who: "Philip Kügler", d: "高可用，30多个系统集成，从上线到运营。" },
    ],
    fieldsLabel: "参考项目",
    fields: [
      { t: "医疗与科研", items: ["卡塔尔国家医疗保险（与麦肯锡）", "欧洲卒中组织", "西格蒙德·弗洛伊德私立大学"] },
      { t: "教育", items: ["Untis——联邦、州与学校身份管理", "多瑙大学克雷姆斯", "维也纳技术大学"] },
      { t: "公共部门", items: ["奥地利财政部／海关", "电子护照与边境管控", "维也纳市"] },
      { t: "社会", items: ["维也纳融合之家", "vidid协会", "ORF"] },
    ],
    closing: "最终成果：专业人士、机构与政府放心托付数据的平台。",
    refLabel: "参考项目", refTitle: "在医疗、教育与政务领域久经验证。", refIntro: "不容有失的平台。",
  },
  timeline: { label: "发展历程", title: "两条路径，自2016年起共同合作。", sub: "房地产、电信数据、政府平台——以及共同创办的企业。", joint: "携手", more: "查看完整历程", less: "仅显示重点" },
  clients: { label: "客户与合作伙伴", title: "深受企业、政府与投资者信赖。", fo: "+ 非公开家族办公室" },
  groups: { telecom: "电信与数据", public: "公共部门与医疗", edu: "教育与科研", finance: "金融与支付", industry: "产业与技术", re: "房地产与酒店业", legal: "法律、媒体与社会" },
  contact: {
    label: "联系", title: "联系我们。", p: "战略、受监管市场项目、合作机会。",
    web: "网站", mail: "电子邮件", loc: "地点", locV: "奥地利维也纳", entity: "法律实体",
    form: {
      name: "姓名", company: "公司", email: "电子邮件", topic: "主题", message: "留言",
      topics: ["技术与AI", "房地产与酒店业", "受监管市场／合资项目", "其他"],
      namePh: "您的姓名", companyPh: "可选", emailPh: "您的邮箱", messagePh: "简要描述您的需求",
      submit: "发送", sending: "发送中……",
      privacy: "我们依据", privacyLink: "隐私政策处理您的数据",
      success: "感谢——我们将尽快与您联系。",
      fallbackTitle: "无法自动发送。", fallbackText: "请通过电子邮件发送——邮件已为您准备好。",
      fallbackBtn: "打开邮件", fallbackOr: "或直接发送至", required: "请填写姓名和有效的电子邮件地址。",
    },
  },
  insights: { label: "洞察", title: "市场动态。", sub: "2026年2月以来的精选分析。", all: "全部", more: "更多", read: "阅读" },
  tech: {
    nav: [["team", "团队"], ["compliance", "合规"], ["leistungen", "服务"], ["netzwerk", "网络"], ["prozess", "流程"], ["kontakt", "联系"]],
    chapters: ["团队", "合规", "转型", "服务", "网络", "流程", "联系", "洞察"],
    h1: ["深度分析。", "快速执行。", "高效成果。"],
    heroP: "AI转型、智能体AI与受监管市场平台。6至9个月内取得可衡量成果。",
    ctaA: "服务", ctaB: "团队",
    stats: [{ v: "€45m+", l: "募集资本" }, { v: "€12m+", l: "研究资助" }, { v: "10+", l: "年政府项目经验" }, { v: "30+", l: "系统集成" }, { v: "40+", l: "DACH与中东北非项目" }, { v: "50+", l: "年合计经验" }],
    partnerTitle: "客户与合作伙伴",
    teamLabel: "团队", teamTitle: "法律、资本、技术。同一团队。", teamIntro: "",
    profiles: [
      { ...PEOPLE.david, role: "创始人兼管理合伙人", focus: "法律 · 资本 · 公司建设",
        paras: ["法律专家、创业者及连续CEO。25年以上运营经验，横跨六大行业交易额逾6亿欧元。", "2015年受德国电信和A1委托开拓新业务。Geolad创始人兼CEO（30余名员工，欧洲与亚洲）。GDPR与欧盟AI法案实践经验丰富。"],
        quote: "以法律思维思考。以企业家方式行动。以成效付诸实施。",
        cards: [["电信与数据", "德国电信、A1、Orange、Zain、Viettel、华为、爱立信"], ["科研与教育", "欧洲卒中组织、西格蒙德·弗洛伊德私立大学、多瑙大学克雷姆斯"], ["房地产", "维也纳私人银行、EPI不动产、UNIQA"], ["法律", "Lansky, Ganzger & Partner、Herbst Kinsky"], ["酒店业", "EPI Hospitality、Ibis、Arcotel"], ["社会公益", "维也纳融合之家、ORF、红牛、vidid"]] },
      { ...PEOPLE.philip, role: "技术管理合伙人", focus: "架构 · 安全 · 交付",
        paras: ["企业架构师、项目集经理及CTO。25年以上大型IT项目经验——专注公共部门、金融与教育。", "卡塔尔国家医疗保险（与麦肯锡）、奥地利财政部海关进口、电子护照与边境管控。OptInk首席技术官兼联合创始人，Merkit Consulting总经理。维也纳技术大学硕士，IPMA C级。"],
        quote: "系统化思考。务实地构建。可靠地运行。",
        cards: [["公共部门", "财政部／海关、电子护照、边境管控"], ["医疗", "卡塔尔国家医疗保险（麦肯锡）"], ["教育", "Untis——学校身份管理与单点登录；维也纳技术大学"], ["金融与支付", "Global Blue、理特咨询、核心银行"], ["电信", "奥地利电信、VeriSign / 3united"], ["创业", "OptInk、Merkit Consulting、保时捷信息技术、RISE"]] },
    ],
    comp: {
      label: "数据保护与安全", title: "GDPR、AI法案、ISO 27001——从第一天起。",
      p: "法律评估与技术实施，由同一团队完成。",
      cols: [
        { t: "法律与监管", who: "David Brainin", items: ["四大行业8年GDPR实践", "GDPR第9条：健康数据与同意", "AI系统影响评估", "AI法案：风险等级、合规、文档", "欧盟、中东北非、东盟数据传输（Schrems II）"] },
        { t: "安全与架构", who: "Philip Kügler", items: ["落实ISO 27001、BSI与ITIL", "身份管理与单点登录：Keycloak、OIDC/SAML", "安全的国际数据传输", "高可用、备份、故障切换", "隐私设计与AI治理"] },
      ],
    },
    tLabel: "AI转型", tTitle: "降低成本，创造新收入。",
    tP: "三大杠杆：自动化、新收入来源、智能体AI。6至9个月内可验证。",
    opexT: "运营成本优化", opex: ["重复流程自动化", "减少错误与返工", "智能文档与合同分析", "整合数据源"],
    revT: "新收入", rev: ["数据变现", "AI驱动的产品与服务", "平台与市场模式", "内部方案SaaS化"],
    kpis: [{ v: "6–9", u: " 个月", l: "见成效" }, { v: "30%+", l: "运营成本节省" }, { v: "全新", l: "来自现有资产的收入", gold: true }],
    sLabel: "服务", sTitle: "从战略到运营。",
    serv: [
      { t: "战略顾问与咨询", d: "C级战略对话、交易支持、临时管理。", tags: ["CEO顾问", "交易", "临时管理"] },
      { t: "AI与数据咨询", d: "从准备度评估到落地实施——符合GDPR与AI法案。", tags: ["AI代理", "数据战略", "欧盟AI法案"] },
      { t: "AI转型", d: "工作流自动化、文档管理、变革管理。", tags: ["自动化", "实施", "变革"] },
      { t: "智能体AI", d: "自主多智能体系统——从架构到生产。", tags: ["智能体AI", "多智能体", "自主"] },
      { t: "受监管市场平台", d: "医疗、教育、公共部门：法律、安全、资助、上线。", tags: ["医疗与教育", "公共部门", "安全设计"] },
      { t: "公司建设与合资", d: "设立、合资架构、融资、加速器。", tags: ["公司建设", "合资企业", "融资"] },
    ],
    netLabel: "网络", netTitle: "为每项任务组建合适团队。", netP: "法律、技术、金融与产业专家——按项目组建。",
    clusters: [["法律", "公司、知识产权与监管——Lansky, Ganzger & Partner、Herbst Kinsky"], ["技术与AI", "架构师、安全与身份管理、AI与数据工程师"], ["公共部门与医疗", "部委、登记系统、保险机构、大学"], ["金融", "RBI、维也纳私人银行、风投、家族办公室"], ["行业", "电信运营商、转型专家、UNIQA"]],
    netBar: "咨询与执行，一站完成。", netBadge: "咨询与执行",
    pLabel: "流程", pTitle: "6至9个月见成效",
    proc: [{ t: "启动", sub: "第1周", d: "范围与速赢" }, { t: "分析", sub: "第2–3周", d: "流程、数据、瓶颈" }, { t: "规划", sub: "第4–5周", d: "措施、KPI、里程碑" }, { t: "执行", sub: "第2–6月", d: "实施与AI集成" }, { t: "成效", sub: "第6–9月", d: "降本增收" }],
    pBar: ["总周期：", "6–9个月", ""], pBadge: "承诺时间框架",
  },
  re: {
    nav: [["profil", "简介"], ["expertise", "专业"], ["leistungen", "服务"], ["netzwerk", "网络"], ["prozess", "流程"], ["kontakt", "联系"]],
    chapters: ["简介", "专业", "服务", "网络", "流程", "联系", "洞察"],
    profileTitle: "25年，逾6亿欧元交易。",
    h1: ["深入分析。", "精准架构。", "稳妥交割。"],
    heroP: "住宅、商业与酒店交易额逾6亿欧元。结构设计、项目领导、交割。",
    ctaA: "服务", ctaB: "简介",
    stats: [{ v: "€600m+", l: "交易额" }, { v: "25+", l: "年房地产与酒店业" }, { v: "3", l: "资产类别" }, { v: "AT · CEE · ES", l: "市场" }],
    partnerTitle: "客户与合作伙伴",
    profileLabel: "创始人兼管理合伙人",
    profile: { ...PEOPLE.david, role: "创始人兼管理合伙人", focus: "法律 · 交易 · 房地产",
      paras: ["法律专家及连续CEO。25年以上房地产与酒店业经验，交易额逾6亿欧元。", "服务奥地利、中东欧及西班牙的机构投资者、家族办公室和开发商。"],
      quote: "以法律思维思考。以企业家方式行动。以成效付诸实施。",
      cards: [["住宅", "EPI不动产、Trimmobilien、Conwert、Akkadia"], ["商业与办公", "收购与出售"], ["酒店与餐饮", "EPI Hospitality、Ibis、Arcotel"], ["零售与综合", "咨询与结构设计"], ["开发", "可行性、审批、项目领导"], ["买卖", "买方与卖方授权"]] },
    tLabel: "房地产专业", tTitle: "从分析到交割。", tP: "市场洞察、法律精准、实际执行。",
    opexT: "交易与顾问", opex: ["市场与可行性分析", "尽职调查：法律、财务、技术", "融资与股权结构", "谈判与政府协调"],
    revT: "买卖与项目", rev: ["买方与卖方授权", "开发直至交付", "酒店重新定位", "中东欧与西班牙交易来源"],
    kpis: [{ v: "6亿欧元+", l: "交易记录" }, { v: "25+", l: "年执行经验" }, { v: "中东欧与西班牙", l: "交易范围" }],
    sLabel: "服务", sTitle: "收购、出售、开发——直至签约。",
    serv: [
      { t: "交易顾问", d: "收购与出售：分析、尽调、结构设计。", tags: ["收购", "出售", "尽职调查"] },
      { t: "项目领导", d: "开发、翻新、重新定位——预算、时间、审批。", tags: ["项目管理", "开发", "执行"] },
      { t: "酒店顾问", d: "重新定位、品牌选择、运营商谈判。", tags: ["酒店", "餐饮", "重新定位"] },
      { t: "结构设计与法律", d: "交易结构、公司法、交割文件。", tags: ["结构设计", "法律", "跨境"] },
      { t: "顾问与谈判", d: "准备并主导复杂谈判。", tags: ["顾问", "谈判", "咨询"] },
      { t: "交割", d: "推动交易直至签约。", tags: ["交割", "执行", "成果"] },
    ],
    netLabel: "网络", netTitle: "为每笔交易组建合适团队。", netP: "法律、房地产、金融与产业合作伙伴——按授权组建。",
    clusters: [["法律", "DSC律所、Herbst Kinsky——房地产、公司与交易法"], ["房地产", "EPI不动产、Akkadia、Arcotel、Plaza"], ["金融", "RBI、维也纳私人银行、家族办公室"], ["行业", "UNIQA、维也纳市、建筑合作伙伴"], ["技术与AI", "房地产科技、数字资产管理"]],
    netBar: "咨询与执行，一站完成。", netBadge: "咨询与执行",
    pLabel: "流程", pTitle: "3至6个月完成交割。",
    proc: [{ t: "简报", sub: "第1周", d: "授权、目标、时间表" }, { t: "分析", sub: "第2–3周", d: "市场、法律、风险" }, { t: "结构", sub: "第3–5周", d: "交易、融资、策略" }, { t: "谈判", sub: "第2–4月", d: "交易管理、审批" }, { t: "交割", sub: "第3–6月", d: "签约与移交" }],
    pBar: ["典型周期：", "3–6个月", "从授权到交割"], pBadge: "实际执行",
  },
},
};
