// Data for the /new site.

// Track record of both partners. `who`: "david" (left lane), "philip" (right lane), "both" (joint).
// David's entries: texts unchanged from src/Timeline.jsx (8 of 13 kept, CN added).
// Philip's entries: from his CV (released by him, 2026-09).
export const TIMELINE = [
  { year: "2002", who: "philip",
    en: { title: "Telekom Austria — Digital Products & E-Commerce", desc: "Project manager and technical consultant: new digital products, e-commerce and online marketing platforms, integrated into billing, SLA and contract processes." },
    de: { title: "Telekom Austria — digitale Produkte & E-Commerce", desc: "Projektleiter und Technical Consultant: neue digitale Produkte, E-Commerce- und Online-Marketing-Plattformen, eingebunden in Verrechnung, SLA- und Vertragsprozesse." },
    cn: { title: "奥地利电信——数字产品与电子商务", desc: "项目经理兼技术顾问：新数字产品、电子商务与在线营销平台，并与计费、SLA及合同流程集成。" } },
  { year: "2005", who: "david",
    en: { title: "Portfolio Expansion — Trimmobilien Real Estate Group", desc: "Co-investment in a Vienna residential portfolio expansion alongside the Trimmobilien Real Estate Group, marking the first significant co-investment mandate." },
    de: { title: "Beteiligung & Skalierung Trimmobilien Real Estate Group", desc: "Co-Investment im Rahmen einer Portfolioerweiterung der Trimmobilien Real Estate Group Wien — erstes bedeutendes Co-Investment-Mandat." },
    cn: { title: "参股Trimmobilien房地产集团", desc: "参与维也纳Trimmobilien房地产集团住宅资产组合扩张的共同投资——首个重要共同投资项目。" } },
  { year: "2006", who: "philip",
    en: { title: "VeriSign / 3united — 100+ Mobile Operators, 15 Countries", desc: "Technical lead for integrating more than 100 mobile network operators in 15 countries into a multimedia and payment platform — with a team of 50+ across three continents." },
    de: { title: "VeriSign / 3united — 100+ Mobilfunkbetreiber, 15 Länder", desc: "Technische Projektleitung der Integration von über 100 Mobilfunkbetreibern in 15 Ländern in eine Multimedia- und Payment-Plattform — mit einem Team von 50+ auf drei Kontinenten." },
    cn: { title: "VeriSign / 3united——100多家运营商，15个国家", desc: "技术负责人，将15个国家的100多家移动运营商集成至多媒体与支付平台——带领横跨三大洲的50余人团队。" } },
  { year: "2009", who: "david",
    en: { title: "International Real Estate Desk at Lansky, Ganzger & Partner", desc: "Established and led the International Real Estate Desk at Lansky, Ganzger & Partner in Vienna, structuring cross-border transactions for CEE and MENA clients." },
    de: { title: "International Real Estate Desk bei Lansky, Ganzger & Partner", desc: "Aufbau und Leitung des International Real Estate Desk bei Lansky, Ganzger & Partner in Wien — Strukturierung grenzüberschreitender Transaktionen für CEE- und MENA-Mandanten." },
    cn: { title: "Lansky, Ganzger & Partner律所国际房地产部", desc: "在维也纳Lansky, Ganzger & Partner律所组建并领导国际房地产部——为中东欧及中东北非客户设计跨境交易结构。" } },
  { year: "2012", who: "philip",
    en: { title: "RISE — International Large-Scale IT Programmes", desc: "Project manager and enterprise architect for national and international IT programmes; key account and presales for public tenders, presenting up to board level." },
    de: { title: "RISE — internationale IT-Großprojekte", desc: "Projektleiter und Enterprise Architect für nationale und internationale IT-Großprojekte; Key Account und Presales für öffentliche Ausschreibungen, Präsentation bis auf Vorstandsebene." },
    cn: { title: "RISE——国际大型IT项目", desc: "担任国家级与国际大型IT项目的项目经理及企业架构师；负责公共招标的大客户与售前工作，并向董事会层级汇报。" } },
  { year: "2013", who: "david",
    en: { title: "Founding of geolad GmbH", desc: "Established geolad GmbH as a specialist vehicle for location intelligence and spatial data analytics, bridging real estate expertise and emerging data markets." },
    de: { title: "Gründung geolad GmbH", desc: "Gründung der geolad GmbH als Spezialbeteiligungsgesellschaft für Location Intelligence und räumliche Datenanalytik — Brücke zwischen Immobilien-Know-how und Datenmärkten." },
    cn: { title: "创立geolad GmbH", desc: "创立geolad GmbH，专注位置智能与空间数据分析——连接房地产专业知识与新兴数据市场。" } },
  { year: "2013", who: "philip",
    en: { title: "National Health Insurance Qatar — with McKinsey", desc: "Interim IT operations manager and enterprise architect for building a national health insurance: ministries and registries connected, data centre, ERP and a permanent IT team established." },
    de: { title: "Nationale Krankenversicherung Katar — mit McKinsey", desc: "Interim IT Operations Manager und Enterprise Architect beim Aufbau einer nationalen Krankenversicherung: Anbindung von Ministerien und Registern, Rechenzentrum, ERP und Aufbau des permanenten IT-Teams." },
    cn: { title: "卡塔尔国家医疗保险——与麦肯锡合作", desc: "担任临时IT运营经理及企业架构师，参与建设国家医疗保险体系：连接各部委与登记系统，建立数据中心、ERP及常设IT团队。" } },
  { year: "2015", who: "david",
    en: { title: "First Telecom Data Hub Infrastructure Mandate — Deutsche Telekom", desc: "Awarded the first engagement for the development of a Telecom Science Data Hub infrastructure — a pioneering B2B platform monetising network data for enterprise clients, anchored by Deutsche Telekom." },
    de: { title: "Erstes Telco-Data-Hub-Infrastrukturmandat — Deutsche Telekom", desc: "Erste Beauftragung zur Entwicklung einer Telecom Science Data Hub Infrastruktur — wegweisende B2B-Plattform zur Monetarisierung von Netzwerkdaten für Unternehmenskunden, verankert durch Deutsche Telekom." },
    cn: { title: "首个电信数据中心基础设施委托——德国电信", desc: "获得首个电信科学数据中心基础设施开发委托——以德国电信为核心、面向企业客户实现网络数据变现的开创性B2B平台。" } },
  { year: "2016", who: "both", roles: { en: ["Founder & CEO", "Advisor"], de: ["Gründer & CEO", "Advisor"], cn: ["创始人兼CEO", "顾问"] },
    en: { title: "geolad — Philip Kügler joins as Advisor", desc: "David Brainin, founder and CEO, brings in Philip Kügler as advisor to the telecom data platform geolad." },
    de: { title: "geolad — Philip Kügler als Advisor", desc: "David Brainin, Gründer und CEO, holt Philip Kügler als Advisor zur Telekom-Datenplattform geolad." },
    cn: { title: "geolad——Philip Kügler出任顾问", desc: "创始人兼CEO David Brainin邀请Philip Kügler担任电信数据平台geolad的顾问。" } },
  { year: "2017", who: "both", roles: { en: ["CEO", "CTO"], de: ["CEO", "CTO"], cn: ["CEO", "CTO"] },
    en: { title: "TICO — Telecom Identity Product", desc: "A jointly built telecom identity product with IP in the EU and the US." },
    de: { title: "TICO — Telekom-Identity-Produkt", desc: "Gemeinsam aufgebautes Telekom-Identity-Produkt mit IP in der EU und den USA." },
    cn: { title: "TICO——电信身份产品", desc: "共同打造的电信身份产品，在欧盟和美国拥有知识产权。" } },
  { year: "2017", who: "philip",
    en: { title: "OptInk — CTO & Co-Founder", desc: "Co-founder and CTO of the Austrian startup OptInk — responsible for technology, architecture and product development." },
    de: { title: "OptInk — CTO & Co-Founder", desc: "Mitgründer und CTO des österreichischen Startups OptInk — verantwortlich für Technologie, Architektur und Produktentwicklung." },
    cn: { title: "OptInk——首席技术官兼联合创始人", desc: "奥地利初创公司OptInk联合创始人兼首席技术官——负责技术、架构与产品开发。" } },
  { year: "2018", who: "david",
    en: { title: "International Telco Consortium", desc: "Orange, Viettel, Zain, Huawei and Ericsson joined the ecosystem — establishing InVentures as a global connector between telecoms and data platform buyers." },
    de: { title: "Internationales Telko-Konsortium", desc: "Orange, Viettel, Zain, Huawei und Ericsson traten dem Ökosystem bei — InVentures etablierte sich als globaler Verbinder zwischen Telekommunikationsunternehmen und Datenplattform-Käufern." },
    cn: { title: "国际电信联盟", desc: "Orange、Viettel、Zain、华为和爱立信加入生态系统——InVentures成为电信企业与数据平台买家之间的全球连接者。" } },
  { year: "2020", who: "david",
    en: { title: "COVID Digital Resilience Advisory", desc: "Pivoted to digital resilience consulting for real estate and telecom clients navigating pandemic-driven market dislocations — 14 mandates delivered in 9 months." },
    de: { title: "COVID Digital Resilience Advisory", desc: "Umstieg auf Digital-Resilience-Beratung für Immobilien- und Telekom-Kunden inmitten pandemiebedingter Marktverschiebungen — 14 Mandate in 9 Monaten abgeschlossen." },
    cn: { title: "新冠数字韧性咨询", desc: "转向为应对疫情市场冲击的房地产与电信客户提供数字韧性咨询——9个月内完成14项委托。" } },
  { year: "2020", who: "philip",
    en: { title: "Austrian Ministry of Finance — Customs Import", desc: "Product owner and project manager for imports under the Union Customs Code: stream above EUR 10 million, integration of 30+ surrounding systems, more than four years of delivery with Scrum and SAFe." },
    de: { title: "Bundesministerium für Finanzen — Zoll-Import", desc: "Product Owner und Projektleiter Import im Unionszollkodex: Stream über EUR 10 Mio., Integration von 30+ Umfeldsystemen, über vier Jahre Umsetzung mit Scrum und SAFe." },
    cn: { title: "奥地利联邦财政部——海关进口", desc: "欧盟海关法典进口模块产品负责人兼项目经理：逾1000万欧元的项目流，集成30多个周边系统，以Scrum与SAFe交付逾四年。" } },
  { year: "2021", who: "david",
    en: { title: "PropTech Portfolio Entry", desc: "First direct PropTech investment in a Vienna-based AI-powered property management platform — seed round led alongside Austrian and German family offices." },
    de: { title: "PropTech-Portfolioeinstieg", desc: "Erste direkte PropTech-Beteiligung an einer Wiener KI-gestützten Property-Management-Plattform — Seed-Runde gemeinsam mit österreichischen und deutschen Family Offices geleitet." },
    cn: { title: "进军房地产科技投资", desc: "首次直接投资维也纳一家AI驱动的物业管理平台——与奥地利和德国家族办公室共同领投种子轮。" } },
  { year: "2021", who: "philip",
    en: { title: "Untis — Identity Management for Schools", desc: "Large-scale integration across federal, state and school administrations: identity and access management, SSO rollout, and security requirements under ISO 27001, BSI and GDPR." },
    de: { title: "Untis — Identity-Management für Schulen", desc: "Integrationsgroßprojekte über Bund, Länder und Schulen: Identity- und Access-Management, SSO-Rollout sowie Sicherheitsanforderungen nach ISO 27001, BSI und DSGVO." },
    cn: { title: "Untis——学校身份管理", desc: "覆盖联邦、州与学校管理系统的大型集成项目：身份与访问管理、单点登录上线，以及依据ISO 27001、BSI与GDPR的安全要求。" } },
  { year: "2023", who: "david",
    en: { title: "MENA Capital Bridge", desc: "Established structured access to Gulf Cooperation Council sovereign and family office capital for European real estate — first GCC-to-AT deal closed Q4 2023." },
    de: { title: "MENA Capital Bridge", desc: "Strukturierter Zugang zu souveränem und Family-Office-Kapital aus dem Golfkooperationsrat für europäische Immobilien geschaffen — erster GCC-zu-AT-Deal im Q4 2023 abgeschlossen." },
    cn: { title: "中东北非资本桥梁", desc: "为欧洲房地产建立对接海湾合作委员会主权基金与家族办公室资本的结构化渠道——2023年第四季度完成首笔GCC至奥地利交易。" } },
  { year: "2025", who: "philip",
    en: { title: "Merkit Consulting FlexCo — Managing Director", desc: "Managing director of a consultancy for robotic process automation and test automation." },
    de: { title: "Merkit Consulting FlexCo — Geschäftsführer", desc: "Geschäftsführer einer Beratung für Robotic Process Automation und Testautomatisierung." },
    cn: { title: "Merkit Consulting FlexCo——总经理", desc: "担任一家机器人流程自动化与测试自动化咨询公司的总经理。" } },
  { year: "2026", who: "both", final: true,
    en: { title: "prax.net — Our Joint Venture", desc: "The clinical referral network for psychosocial professionals in Austria (FlexCo in formation). In parallel, both lead InVentures as managing partners." },
    de: { title: "prax.net — gemeinsames Joint Venture", desc: "Das klinische Referral-Netzwerk für psychosoziale Fachkräfte in Österreich (FlexCo i. G.). Parallel führen beide InVentures als Managing Partner." },
    cn: { title: "prax.net——共同创办的合资企业", desc: "面向奥地利心理社会专业人士的临床转介网络（FlexCo筹建中）。同时，两人以管理合伙人身份共同领导InVentures。" } },
];

// Clients & partners, grouped. `tracks` decides where a group appears.
export const CLIENT_GROUPS = [
  { key: "telecom", tracks: ["home", "tech"], names: ["Deutsche Telekom", "A1 Group", "Telekom Austria", "Orange", "Zain Group", "Viettel", "Huawei", "Ericsson", "VeriSign"] },
  { key: "public", tracks: ["home", "tech"], names: ["Bundesministerium für Finanzen", "Supreme Council of Health (Qatar)", "McKinsey & Company", "European Stroke Organisation"] },
  { key: "edu", tracks: ["home", "tech"], names: ["Sigmund Freud PrivatUniversität Wien", "Donau-Universität Krems", "Untis"] },
  { key: "finance", tracks: ["home", "tech", "re"], names: ["Raiffeisen Bank International", "Wiener Privatbank SE", "Uniqa Versicherung", "Global Blue", "Arthur D. Little"] },
  { key: "industry", tracks: ["home", "tech"], names: ["Porsche Informatik (Volkswagen)", "RISE", "Match Maker Ventures"] },
  { key: "re", tracks: ["home", "re"], names: ["EPI Immobilien Group", "Conwert AG", "Trimmobilien Gruppe", "Akkadia Immobilien", "EPI Hospitality", "Arcotel Hotels", "Ibis Group", "Stadt Wien"] },
  { key: "legal", tracks: ["home", "tech", "re"], names: ["Lansky, Ganzger & Partner", "Herbst Kinsky RAe", "DSC Rechtsanwälte", "ORF", "Integrationshaus Wien"] },
];

// Logo files for the client marquee: name → path under public/ (e.g. "/logos/deutsche-telekom.svg").
// Names without a file are shown as a typographic wordmark.
export const LOGOS = {};
