// All user-visible copy of the /new site (EN / DE / 中文). Short by design: facts first.
// Facts about David Brainin come from the live site; facts about Philip Kügler from his CV (released by him, 2026-09).

export const LANGS = [["en", "EN"], ["de", "DE"], ["cn", "中文"]];
export const HTML_LANG = { en: "en", de: "de", cn: "zh-Hans" };

// Names without academic titles (English, 中文); the German pages add them (David, 2026-09-23).
// "^iur" renders as a small superscript, see Rich in ui.jsx.
const PEOPLE = { david: { key: "david", name: "David Brainin", initials: "DB", accent: "gold", photo: "portrait-brainin" }, philip: { key: "philip", name: "Philip Kügler", initials: "PK", accent: "silver", photo: "portrait-kuegler" } };
const PEOPLE_DE = { david: { ...PEOPLE.david, name: "Mag.^iur David Brainin" }, philip: { ...PEOPLE.philip, name: "Philip Kügler, MSc" } };

export const TX = {
// ─────────────────────────────────────────────────────────────── EN
en: {
  meta: { home: "InVentures — Ventures in the most regulated markets", tech: "Tech & AI — InVentures", re: "Real Estate & Hospitality — InVentures", insights: "Insights — InVentures", impressum: "Legal notice — InVentures", datenschutz: "Privacy policy — InVentures", notFound: "Page not found — InVentures",
    desc: { home: "InVentures builds ventures in the most regulated markets: law, capital and technology in one team — Tech & AI and Real Estate & Hospitality, from Vienna.", tech: "AI strategy, implementation and platforms for regulated markets, with GDPR and the AI Act considered from day one. InVentures, Vienna.", re: "Transaction advisory, project and development management and hospitality: EUR 600m+ in transactions. InVentures, Vienna.", insights: "Own analyses and selected market reports on AI, regulation and real estate.", impressum: "Legal notice of InVentures, a joint venture operated by Inside Holding & Real Estate GmbH.", datenschutz: "Privacy policy of InVentures: no cookies, no tracking, self-hosted fonts and images." } },
  ui: {
    entity: "A project of Inside Holding & Real Estate GmbH", entityLong: "A joint venture of David Brainin and Philip Kügler. Legal entity: Inside Holding & Real Estate GmbH.",
    back: "Back to overview", menu: "Menu", since06: "Since 2006", since15: "Since 2015",
    imprint: "Legal notice", privacy: "Privacy policy", cookies: "Cookie Settings", trackTech: "Tech & AI", trackRe: "Real Estate", switchTrack: "Back to overview",
    discuss: "Discuss your project", allInsights: "All insights", refNote: "Organisations from our partners' project experience, including before InVentures was founded.", refLink: "Note on references", langHint: { de: "Article in German", en: "Article in English" },
    notFoundTitle: "Page not found.", notFoundText: "This page does not exist or has moved.",
    readArticle: "Read full article", closeArticle: "Collapse article", showRefs: "Show sectors & clients", hideRefs: "Hide sectors & clients",
  },
  homeNav: [["/tech", "Tech & AI"], ["/real-estate", "Real Estate & Hospitality"], ["referenzen", "References"], ["team", "Team"], ["kontakt", "Contact"]],
  home: {
    brandSub: "Venture Building in AI & Real Estate",
    h1: "We build ventures in the most regulated markets.",
    brandP: "Law, capital and technology in one team — for companies, investors and founders in AI and real estate.",
    chapters: ["Areas", "Experience", "Team", "Expertise", "References", "Track Record", "Contact"],
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "Two disciplines. One platform.", selectSub: "Choose your area",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI transformation, regulated platforms, company building", tags: ["AI Transformation", "GDPR & AI Act", "Health & Education", "Company Building"], cta: "Explore Tech & AI" },
      re: { label: "Real Estate &\nHospitality", sub: "Sale & acquisition, transactions, project management", tags: ["Sale & Acquisition", "Transactions", "Project Management", "Hospitality"], cta: "Explore Real Estate" },
    },
    waysLabel: "How we work with you",
    ways: [
      { t: "Advisory", d: "Analysis, strategy, structuring and a sound basis for decisions — for management, investors and public bodies." },
      { t: "Delivery", d: "Technical implementation, project management and operational responsibility — through to operation or closing." },
      { t: "Venture building & investments", d: "Our own ventures in regulated markets, co-investments with partners and family offices, structured financing." },
    ],
  },
  team: {
    label: "Team", title: "Two partners. 50+ years of experience.",
    intro: "We combine law, capital and company building with architecture, security and delivery — with a proven history of working together.",
    people: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        bio: "Lawyer by training, founder and serial CEO. 25+ years of operational responsibility, EUR 600m+ in transactions, founder of geolad. GDPR and EU AI Act in practice.",
        facts: [{ v: "€600m+", l: "Transaction volume" }, { v: "€45m+", l: "Capital mobilised" }, { v: "€12m+", l: "Research grants" }] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        bio: "Enterprise architect and CTO. 25+ years of large IT programmes for government, health, education and telecom — from customs to a national health insurance system.",
        facts: [{ v: "4", l: "National government programmes" }, { v: "€10m+", l: "Programme stream managed (customs)" }, { v: "5", l: "Years of identity management for federal, state and school systems" }] },
    ],
    bondsLabel: "What we combine",
    bonds: [
      { t: "Regulated markets", d: "Health, education, public sector, finance, real estate." },
      { t: "Sensitive data", d: "GDPR, AI Act, ISO 27001 — from day one." },
      { t: "Concept to operation", d: "Incorporation, funding, architecture, rollout. One team." },
    ],
    cta: "Discuss a project",
  },
  regulated: {
    label: "Regulated markets", title: "Sensitive data needs more than software.",
    focus: "GDPR in the most sensitive areas: personal telecom, health and education data.",
    intro: "A legal basis, a secure architecture, funding — and partners who have done it before.",
    pillars: [
      { t: "Security by Design", who: "Philip Kügler", d: "Security requirements per ISO 27001 and BSI, identity and access management." },
      { t: "Architecture & Operations", who: "Philip Kügler", d: "National registries and platforms — highly available, integrated, through to operation." },
      { t: "Company Building & Capital", who: "David Brainin", d: "Incorporation, governance, go-to-market. €45m+ capital, €12m+ grants." },
      { t: "Legal & Compliance", who: "David Brainin", d: "Art. 9 GDPR, impact assessments, AI Act classification." },
    ],
    telecom: { label: "Telecommunications law", claim: "Trained where data protection is strictest: in telecommunications law.", p: "Both partners have worked with telecom data for years — under the telecommunications laws of several countries, which are more detailed, stricter and more closely supervised than the GDPR alone." },
    fieldsLabel: "References",
    fields: [
      { t: "Health & Science", items: ["National health insurance Qatar (with McKinsey)", "European Stroke Organisation", "World Stroke Organization"] },
      { t: "Education", items: ["Untis — identity and access management for federal and state authorities and schools", "Danube University Krems", "TU Wien"] },
      { t: "Public Sector", items: ["Austrian Ministry of Finance — customs", "ePassport & border control", "City of Vienna"] },
      { t: "Society", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    closing: "The result: platforms that professionals, institutions and authorities entrust with their data.",
    refLabel: "References", refTitle: "State of the art in health, education and government.", refIntro: "Systems people rely on every day.",
  },
  timeline: { label: "Track Record", title: "Two paths. Joint projects since 2016.", sub: "Real estate, telecom data, government platforms — and joint ventures.", joint: "Together", more: "Show full track record", less: "Show highlights only" },
  clients: { label: "Project experience", title: "Corporates, authorities and investors rely on our experience.", fo: "+ undisclosed family offices" },
  groups: { telecom: "Telecom & Data", public: "Public Sector & Health", edu: "Education & Science", finance: "Finance & Payments", industry: "Industry & Technology", re: "Real Estate & Hospitality", legal: "Legal, Media & Society" },
  contact: {
    label: "Contact", title: "Let's talk.", p: "Strategy, regulated-market projects, partnerships.",
    first: "In a first conversation we clarify your goal, starting point and timeline — and which form of collaboration fits: advisory, delivery or a joint venture.",
    web: "Web", mail: "E-mail", loc: "Location", locV: "Vienna, Austria", entity: "Legal entity",
    people: "Contact persons", peopleV: ["David Brainin — law, capital, real estate", "Philip Kügler — technology, security, product"],
    form: {
      name: "Name", company: "Company", email: "E-mail", topic: "Topic", message: "Message",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulated markets / joint venture", "Other"],
      namePh: "Your name", companyPh: "Optional", emailPh: "you@company.com", messagePh: "Your enquiry in a few lines",
      submit: "Send project enquiry", sending: "Sending…",
      privacy: "We process your data according to our", privacyLink: "privacy policy",
      success: "Thank you — we will be in touch shortly.",
      fallbackTitle: "Your message is ready.", fallbackText: "One click opens it, fully prepared, in your e-mail app.",
      fallbackBtn: "Open e-mail", fallbackOr: "or write to", required: "Please enter your name and a valid e-mail address.",
    },
  },
  insights: { label: "Insights", title: "What moves the market.", sub: "Selected analyses since February 2026.", all: "All", more: "Show more", read: "Read", view: "InVentures View", viewSub: "Our own analyses.", pageTitle: "Insights", pageSub: "Our own analyses and selected market reports on AI, regulation and real estate.", back: "All insights" },
  tech: {
    nav: [["team", "Team"], ["compliance", "Compliance"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    chapters: ["Team", "Compliance", "Transformation", "Services", "Network", "Process", "Contact", "Insights"],
    h1: ["Deep analysis.", "Fast execution.", "Measurable impact."],
    heroP: "AI transformation, agentic AI and platforms for regulated markets. Clearly scoped projects with measurable goals — typically 6–9 months.",
    ctaA: "Services", ctaB: "Team",
    contactP: "An AI project, a platform or a venture in a regulated market: let's discuss your plans.",
    visual: { label: "Compliance by design", layers: [["Use cases", "AI agents, automation, new services"], ["Integration & operations", "Interfaces, identity, monitoring"], ["Data & systems", "Registries, ERP, data platforms"]], chips: ["GDPR", "AI Act", "ISO 27001", "BSI"], caption: "Law, security and technology in one architecture." },
    stats: [{ v: "€45m+", l: "Capital mobilised" }, { v: "€12m+", l: "Research grants" }, { v: "4", l: "National government programmes" }, { v: "€10m+", l: "Programme stream managed (customs)" }, { v: "40+", l: "Projects DACH & MENA" }, { v: "50+", l: "Years of combined experience" }],
    partnerTitle: "Project experience",
    teamLabel: "Team", teamTitle: "Law, capital, technology. One team.", teamIntro: "",
    profiles: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        paras: ["Lawyer by training, startup founder and serial CEO. 25+ years of operational experience, EUR 600m+ in transactions across two sectors.",
          "Pioneer mandate from Deutsche Telekom and A1 in 2015. Founder and CEO of geolad (30+ staff, EU & Asia). GDPR and EU AI Act in practice."],
        quote: "Thinking like a lawyer. Acting like an entrepreneur. Executing with impact.",
        cards: [["Telecom & Data", "Deutsche Telekom, A1, Orange, Zain, Viettel, Huawei, Ericsson"], ["Science & Education", "European Stroke Organisation, World Stroke Organization, Danube University Krems, Sigmund Freud University Vienna (in preparation)"], ["Real Estate", "Wiener Privatbank, EPI Immobilien, UNIQA"], ["Legal", "Lansky, Ganzger & Partner, Herbst Kinsky"], ["Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Social Impact", "Integrationshaus Wien, ORF, Red Bull, vidid"]] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        paras: ["Enterprise architect, programme manager and CTO. 25+ years of large IT programmes — focus on public sector, finance and education.",
          "National health insurance Qatar (with McKinsey), customs imports at the Austrian Ministry of Finance, ePassport and border control. CTO & co-founder of OptInk, MD of Merkit Consulting. MSc TU Wien, IPMA Level C."],
        quote: "Thinking in systems. Building pragmatically. Running reliably.",
        cards: [["Public Sector", "Ministry of Finance / customs, ePassport, border control"], ["Health", "National health insurance Qatar (McKinsey)"], ["Education", "Untis — IAM & SSO for schools; TU Wien"], ["Finance & Payments", "Global Blue, Arthur D. Little, core banking"], ["Telecom", "Telekom Austria, VeriSign / 3united"], ["Ventures", "OptInk, Merkit Consulting, Porsche Informatik, RISE"]] },
    ],
    comp: {
      label: "Data Protection & Security", title: "GDPR, telecom law, AI Act, ISO 27001 — from day one.",
      p: "Legal assessment and technical implementation from one team — trained on the telecommunications laws of several countries, which are stricter and more closely supervised than the GDPR alone.",
      cols: [
        { t: "Security & Architecture", who: "Philip Kügler", items: ["Security requirements per ISO 27001 and BSI and ITIL processes implemented in projects", "IAM & SSO: Keycloak, OIDC/SAML", "Secure international data transfer", "High availability, backup, failover", "Privacy by design and AI governance"] },
        { t: "Legal & Regulatory", who: "David Brainin", items: ["Telecommunications law in several countries, incl. the Austrian TKG", "8 years of GDPR practice across four industries", "Art. 9 GDPR: health data and consent", "Impact assessments for AI systems", "AI Act: risk classes, conformity, documentation", "Data transfers EU, MENA, ASEAN (Schrems II)"] },
      ],
    },
    tLabel: "AI Transformation", tTitle: "Lower costs. New revenue.",
    tP: "Three levers: automation, new revenue streams, agentic AI — with measurable goals for every project.",
    opexT: "OPEX reduction", opex: ["Automation of repetitive processes", "AI-supported quality assurance", "Smart document and contract analysis", "Consolidated data sources"],
    revT: "New revenue", rev: ["Data monetisation", "AI-driven products and services", "Platform and marketplace models", "SaaS from internal solutions"],
    kpis: [{ v: "6–9", u: " months", l: "typical duration for a clearly scoped project" }, { v: "30%", l: "savings target per automated process, agreed per project" }, { v: "New", l: "revenue streams from existing data and assets", gold: true }],
    sLabel: "Services", sTitle: "From strategy to operation.",
    serv: [
      { t: "AI Strategy & Decision Basis", d: "For boards and management: prioritised use cases, business case, data and risk review under GDPR and the AI Act, and an implementation plan.", tags: ["Use Cases", "Business Case", "GDPR & AI Act"] },
      { t: "AI Implementation & Automation", d: "A clearly scoped pilot, integration into existing systems, evaluation and human approval steps — through to operation and monitoring. Including agentic AI.", tags: ["Pilot", "Integration", "Agentic AI"] },
      { t: "Platforms & Venture Building", d: "For projects in regulated markets such as health, education and the public sector: product, governance, funding, architecture and market launch — up to a joint venture.", tags: ["Health & Education", "Governance", "Joint Ventures"] },
      { t: "Executive Advisory & Strategic Support", d: "Strategic support for executive teams, transaction support and interim management.", tags: ["Executive Teams", "Transactions", "Interim"] },
    ],
    netLabel: "Network", netTitle: "The right team for every task.", netP: "Specialists in law, technology, finance and industry — assembled per project.",
    clusters: [["Legal", "Corporate, IP, regulatory — Lansky, Ganzger & Partner, Herbst Kinsky"], ["Tech & AI", "Architects, security & IAM, AI and data engineers"], ["Public & Health", "Ministries, registries, insurers, universities"], ["Finance", "RBI, Wiener Privatbank, VCs, family offices"], ["Industry", "Telecom operators, transformation leaders, UNIQA"]],
    netBar: "Advisory and execution from one team.", netBadge: "Advisory & delivery",
    pLabel: "Process", pTitle: "Typically 6–9 months to results.",
    proc: [{ t: "Kick-off", sub: "Week 1", d: "Scope and quick wins" }, { t: "Analysis", sub: "Week 2–3", d: "Processes, data, potential" }, { t: "Plan", sub: "Week 4–5", d: "Measures, KPIs, milestones" }, { t: "Execution", sub: "Month 2–6", d: "Implementation, AI integration" }, { t: "Impact", sub: "Month 6–9", d: "Lower OPEX, new revenue" }],
    pBar: ["Typical:", "6–9 months", "for an agreed scope"], pBadge: "Timeline agreed per project",
  },
  re: {
    nav: [["profil", "Profile"], ["expertise", "Expertise"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    chapters: ["Profile", "Expertise", "Services", "Network", "Process", "Contact", "Insights"],
    profileTitle: "25 years. EUR 600m+ in transactions.",
    h1: ["Sound analysis.", "Precise structure.", "Secure closing."],
    heroP: "EUR 600m+ in transactions across residential, commercial and hotel properties. Structuring, project management, closing.",
    ctaA: "Services", ctaB: "Profile",
    contactP: "Acquisition, disposal, development or hotel repositioning: let's discuss your project.",
    stats: [{ v: "€600m+", l: "Transaction volume" }, { v: "25+", l: "Years of personal experience in real estate & hospitality (David Brainin)" }, { v: "3", l: "Asset classes" }, { v: "AT · CEE · ES", l: "Markets" }],
    partnerTitle: "Project experience",
    profileLabel: "Founder & Managing Partner",
    profile: { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Transactions · Real Estate",
      paras: ["Lawyer by training and serial CEO. 25+ years in real estate and hospitality, EUR 600m+ in transactions.", "Partner to institutional investors, family offices and developers in Austria, CEE and Spain."],
      quote: "Thinking like a lawyer. Acting like an entrepreneur. Executing with impact.",
      cards: [["Residential", "EPI Immobilien, Trimmobilien, Conwert, Akkadia"], ["Commercial & Office", "Acquisitions and disposals"], ["Hotel & Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Retail & Mixed Use", "Advisory and structuring"], ["Development", "Feasibility, permits, project management"], ["Sale & Acquisition", "Buy-side and sell-side mandates"]] },
    tLabel: "Real Estate Expertise", tTitle: "From analysis to closing.", tP: "Market knowledge, legal precision, hands-on execution.",
    opexT: "Transaction & Advisory", opex: ["Market and feasibility analysis", "Due diligence: legal, financial, technical", "Financing and equity structure", "Negotiation and authority coordination"],
    revT: "Sale, Acquisition & Projects", rev: ["Buy-side and sell-side mandates", "Development through to handover", "Hotel repositioning", "Deal sourcing CEE & Spain"],
    kpis: [{ v: "€600m+", l: "transaction volume" }, { v: "25+", l: "years of execution experience" }, { v: "CEE & Spain", l: "transaction reach" }],
    sLabel: "Services", sTitle: "Buy, sell, develop — through to closing.",
    serv: [
      { t: "Transaction Advisory", d: "Buy-side and sell-side: market analysis, due diligence, deal structure and negotiation — through to signing and closing. Legal work is carried out with our partner law firms.", tags: ["Acquisitions & Disposals", "Due Diligence", "Closing"] },
      { t: "Project & Development Management", d: "Development, refurbishment and repositioning: budget, schedule and authorities — from feasibility to handover.", tags: ["Development", "Refurbishment", "Authorities"] },
      { t: "Hospitality", d: "Repositioning, brand selection and operator negotiations for hotel properties.", tags: ["Hotels", "Operators", "Repositioning"] },
    ],
    netLabel: "Network", netTitle: "The right team for every deal.", netP: "Legal, real estate, finance and industry partners — assembled per mandate.",
    clusters: [["Legal", "DSC Rechtsanwälte, Herbst Kinsky — RE, corporate, transactions"], ["Real Estate", "EPI Immobilien, Akkadia, Arcotel, Plaza"], ["Finance", "RBI, Wiener Privatbank, family offices"], ["Industry", "UNIQA, City of Vienna, construction partners"], ["Tech & AI", "PropTech, digital asset management"]],
    netBar: "Advisory and execution from one team.", netBadge: "Advisory & delivery",
    pLabel: "Process", pTitle: "Typically 3–6 months to closing.",
    proc: [{ t: "Brief", sub: "Week 1", d: "Mandate, goals, timeline" }, { t: "Analysis", sub: "Week 2–3", d: "Market, legal, risk" }, { t: "Structure", sub: "Week 3–5", d: "Deal, financing, strategy" }, { t: "Negotiation", sub: "Month 2–4", d: "Deal management, authorities" }, { t: "Closing", sub: "Month 3–6", d: "Signing, completion, handover" }],
    pBar: ["Typical:", "3–6 months", "from mandate to closing"], pBadge: "Hands-on execution",
  },
},

// ─────────────────────────────────────────────────────────────── DE
de: {
  meta: { home: "InVentures — Ventures in den am stärksten regulierten Märkten", tech: "Tech & AI — InVentures", re: "Real Estate & Hospitality — InVentures", insights: "Insights — InVentures", impressum: "Impressum — InVentures", datenschutz: "Datenschutz — InVentures", notFound: "Seite nicht gefunden — InVentures",
    desc: { home: "InVentures baut Ventures in den am stärksten regulierten Märkten: Recht, Kapital und Technologie aus einem Team – Tech & AI sowie Real Estate & Hospitality, aus Wien.", tech: "AI-Strategie, Umsetzung und Plattformen für regulierte Märkte – DSGVO und AI Act von Beginn an berücksichtigt. InVentures, Wien.", re: "Transaktionsberatung, Projekt- und Entwicklungsmanagement und Hospitality: über 600 Mio. € Transaktionsvolumen. InVentures, Wien.", insights: "Eigene Analysen und ausgewählte Marktberichte zu AI, Regulierung und Immobilien.", impressum: "Impressum von InVentures, einem Joint Venture unter dem Rechtsträger Inside Holding & Real Estate GmbH.", datenschutz: "Datenschutzerklärung von InVentures: keine Cookies, kein Tracking, selbst gehostete Schriften und Bilder." } },
  ui: {
    entity: "Ein Projekt der Inside Holding & Real Estate GmbH", entityLong: "Ein Joint Venture von Mag.^iur David Brainin und Philip Kügler, MSc. Rechtsträger: Inside Holding & Real Estate GmbH.",
    back: "Zur Übersicht", menu: "Menü", since06: "Seit 2006", since15: "Seit 2015",
    imprint: "Impressum", privacy: "Datenschutz", cookies: "Cookie-Einstellungen", trackTech: "Tech & AI", trackRe: "Real Estate", switchTrack: "Zur Übersicht",
    discuss: "Projekt besprechen", allInsights: "Alle Insights", refNote: "Organisationen aus der Projekterfahrung unserer Partner – auch vor Gründung von InVentures.", refLink: "Hinweis zu Referenzen", langHint: { de: "Artikel auf Deutsch", en: "Artikel auf Englisch" },
    notFoundTitle: "Seite nicht gefunden.", notFoundText: "Diese Seite existiert nicht oder wurde verschoben.",
    readArticle: "Ganzen Artikel lesen", closeArticle: "Artikel einklappen", showRefs: "Branchen & Kunden anzeigen", hideRefs: "Branchen & Kunden ausblenden",
  },
  homeNav: [["/tech", "Tech & AI"], ["/real-estate", "Real Estate & Hospitality"], ["referenzen", "Referenzen"], ["team", "Team"], ["kontakt", "Kontakt"]],
  home: {
    brandSub: "Venture Building in AI & Real Estate",
    h1: "Wir bauen Ventures in den am stärksten regulierten Märkten.",
    brandP: "Recht, Kapital und Technologie aus einem Team – für Unternehmen, Investoren und Gründer in AI und Immobilien.",
    chapters: ["Bereiche", "Erfahrung", "Team", "Kompetenz", "Referenzen", "Track Record", "Kontakt"],
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "Zwei Disziplinen. Eine Plattform.", selectSub: "Bereich wählen",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI-Transformation, regulierte Plattformen, Company Building", tags: ["AI-Transformation", "DSGVO & AI Act", "Gesundheit & Bildung", "Company Building"], cta: "Tech & AI entdecken" },
      re: { label: "Real Estate &\nHospitality", sub: "Verkauf & Ankauf, Transaktionen, Projektmanagement", tags: ["Verkauf & Ankauf", "Transaktionen", "Projektmanagement", "Hospitality"], cta: "Real Estate entdecken" },
    },
    waysLabel: "So arbeiten wir mit Ihnen",
    ways: [
      { t: "Beratung", d: "Analyse, Strategie, Strukturierung und belastbare Entscheidungsgrundlagen – für Geschäftsführung, Investoren und öffentliche Stellen." },
      { t: "Umsetzung", d: "Technische Implementierung, Projektmanagement und operative Verantwortung – bis zum Betrieb oder Closing." },
      { t: "Venture Building & Beteiligungen", d: "Eigene Ventures in regulierten Märkten, Co-Investments mit Partnern und Family Offices, strukturierte Finanzierungen." },
    ],
  },
  team: {
    label: "Team", title: "Zwei Partner. Über 50 Jahre Erfahrung.",
    intro: "Wir verbinden Recht, Kapital und Unternehmensaufbau mit Architektur, Sicherheit und Umsetzung – als eingespieltes Team.",
    people: [
      { ...PEOPLE_DE.david, role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        bio: "Jurist, Gründer und Mehrfach-CEO. 25+ Jahre operative Verantwortung, Transaktionen über 600 Mio. €, Gründer der geolad. DSGVO und EU AI Act in der Praxis.",
        facts: [{ v: "600+", l: "Mio. € Transaktions\u00advolumen" }, { v: "45+", l: "Mio. € Kapital mobilisiert" }, { v: "12+", l: "Mio. € Forschungs\u00adförderung" }] },
      { ...PEOPLE_DE.philip, role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Umsetzung",
        bio: "Enterprise Architect und CTO. 25+ Jahre IT-Großprojekte für Behörden, Gesundheit, Bildung und Telekom – vom Zoll bis zur nationalen Krankenversicherung.",
        facts: [{ v: "4", l: "Nationale Regierungs\u00adprogramme" }, { v: "10+", l: "Mio. € Verantwortung im Zollprogramm" }, { v: "5", l: "Jahre Identity-Management für Bund, Länder und Schulen" }] },
    ],
    bondsLabel: "Was wir verbinden",
    bonds: [
      { t: "Regulierte Märkte", d: "Gesundheit, Bildung, Behörden, Finanz, Immobilien." },
      { t: "Sensible Daten", d: "DSGVO, AI Act, ISO 27001 – ab Tag eins." },
      { t: "Konzept bis Betrieb", d: "Gründung, Finanzierung, Architektur, Rollout. Ein Team." },
    ],
    cta: "Projekt besprechen",
  },
  regulated: {
    label: "Regulierte Märkte", title: "Sensible Daten brauchen mehr als Software.",
    focus: "DSGVO in den sensibelsten Bereichen: personenbezogene Telekom-, Gesundheits- und Bildungsdaten.",
    intro: "Rechtsgrundlage, sichere Architektur, Finanzierung – und Partner, die das schon gemacht haben.",
    pillars: [
      { t: "Security by Design", who: "Philip Kügler", d: "Sicherheitsanforderungen nach ISO 27001 und BSI, Identity- & Access-Management." },
      { t: "Architektur & Betrieb", who: "Philip Kügler", d: "Nationale Register und Plattformen – hochverfügbar, integriert, bis in den Betrieb." },
      { t: "Company Building & Kapital", who: "David Brainin", d: "Gründung, Governance, Go-to-Market. Über 45 Mio. € Kapital, über 12 Mio. € Förderungen." },
      { t: "Recht & Compliance", who: "David Brainin", d: "Art. 9 DSGVO, Folgenabschätzung, AI-Act-Klassifizierung." },
    ],
    telecom: { label: "Telekommunikationsrecht", claim: "Gelernt, wo Datenschutz am strengsten ist: im Telekommunikationsrecht.", p: "Beide Partner arbeiten seit Jahren mit Telekom-Daten – unter den Telekommunikationsgesetzen mehrerer Länder, die differenzierter, strenger und enger überwacht sind als die DSGVO allein." },
    fieldsLabel: "Referenzen",
    fields: [
      { t: "Gesundheit & Wissenschaft", items: ["Nationale Krankenversicherung Katar (mit McKinsey)", "European Stroke Organisation", "World Stroke Organization"] },
      { t: "Bildung", items: ["Untis – Identity- & Access-Management für Bund, Länder und Schulen", "Donau-Universität Krems", "TU Wien"] },
      { t: "Öffentliche Hand", items: ["BMF / Zoll – Unionszollkodex", "ePassport & Grenzkontrolle", "Stadt Wien"] },
      { t: "Gesellschaft", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    closing: "Das Ergebnis: Plattformen, denen Fachkräfte, Institutionen und Behörden ihre Daten anvertrauen.",
    refLabel: "Referenzen", refTitle: "Stand der Technik in Gesundheit, Bildung und Verwaltung.", refIntro: "Systeme, auf die sich Menschen jeden Tag verlassen.",
  },
  timeline: { label: "Track Record", title: "Zwei Wege. Gemeinsame Projekte seit 2016.", sub: "Immobilien, Telekom-Daten, Regierungsplattformen – und gemeinsame Ventures.", joint: "Gemeinsam", more: "Gesamten Track Record anzeigen", less: "Nur Highlights anzeigen" },
  clients: { label: "Projekterfahrung", title: "Konzerne, Behörden und Investoren vertrauen auf unsere Erfahrung.", fo: "+ nicht genannte Family Offices" },
  groups: { telecom: "Telekom & Data", public: "Öffentliche Hand & Gesundheit", edu: "Bildung & Wissenschaft", finance: "Finanz & Payments", industry: "Industrie & Technologie", re: "Immobilien & Hospitality", legal: "Recht, Medien & Gesellschaft" },
  contact: {
    label: "Kontakt", title: "Sprechen wir.", p: "Strategie, Projekte in regulierten Märkten, Partnerschaften.",
    first: "Im ersten Gespräch klären wir Ziel, Ausgangslage und Zeitrahmen – und welche Form der Zusammenarbeit passt: Beratung, Umsetzung oder Joint Venture.",
    web: "Web", mail: "E-Mail", loc: "Standort", locV: "Wien, Österreich", entity: "Rechtsträger",
    people: "Ansprechpartner", peopleV: ["Mag.^iur David Brainin – Recht, Kapital, Immobilien", "Philip Kügler, MSc – Technologie, Security, Produkt"],
    form: {
      name: "Name", company: "Unternehmen", email: "E-Mail", topic: "Thema", message: "Nachricht",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulierte Märkte / Joint Venture", "Sonstiges"],
      namePh: "Ihr Name", companyPh: "Optional", emailPh: "sie@unternehmen.at", messagePh: "Ihr Anliegen in wenigen Zeilen",
      submit: "Projektanfrage senden", sending: "Wird gesendet …",
      privacy: "Wir verarbeiten Ihre Daten gemäß unserer", privacyLink: "Datenschutzerklärung",
      success: "Danke – wir melden uns in Kürze.",
      fallbackTitle: "Ihre Nachricht ist bereit.", fallbackText: "Ein Klick öffnet sie fertig vorbereitet in Ihrem E-Mail-Programm.",
      fallbackBtn: "E-Mail öffnen", fallbackOr: "oder direkt an", required: "Bitte Name und gültige E-Mail-Adresse angeben.",
    },
  },
  insights: { label: "Insights", title: "Was den Markt bewegt.", sub: "Ausgewählte Analysen seit Februar 2026.", all: "Alle", more: "Mehr anzeigen", read: "Lesen", view: "InVentures View", viewSub: "Unsere eigenen Analysen.", pageTitle: "Insights", pageSub: "Eigene Analysen und ausgewählte Marktberichte zu AI, Regulierung und Immobilien.", back: "Alle Insights" },
  tech: {
    nav: [["team", "Team"], ["compliance", "Compliance"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    chapters: ["Team", "Compliance", "Transformation", "Leistungen", "Netzwerk", "Prozess", "Kontakt", "Insights"],
    h1: ["Fundierte Analyse.", "Schnelle Umsetzung.", "Messbare Wirkung."],
    heroP: "AI-Transformation, Agentic AI und Plattformen für regulierte Märkte. Klar abgegrenzte Projekte mit messbaren Zielen – typischerweise 6–9 Monate.",
    ctaA: "Leistungen", ctaB: "Team",
    contactP: "AI-Projekt, Plattform oder Venture in einem regulierten Markt: Besprechen wir Ihr Vorhaben.",
    visual: { label: "Compliance by Design", layers: [["Anwendungsfälle", "AI-Agenten, Automatisierung, neue Services"], ["Integration & Betrieb", "Schnittstellen, Identity, Monitoring"], ["Daten & Systeme", "Register, ERP, Datenplattformen"]], chips: ["DSGVO", "AI Act", "ISO 27001", "BSI"], caption: "Recht, Sicherheit und Technik in einer Architektur." },
    stats: [{ v: "45+", l: "Mio. € Kapital mobilisiert" }, { v: "12+", l: "Mio. € Forschungs\u00adförderung" }, { v: "4", l: "Nationale Regierungs\u00adprogramme" }, { v: "10+", l: "Mio. € Verantwortung im Zollprogramm" }, { v: "40+", l: "Projekte DACH & MENA" }, { v: "50+", l: "Jahre Erfahrung, zusammen\u00adgerechnet" }],
    partnerTitle: "Projekterfahrung",
    teamLabel: "Team", teamTitle: "Recht, Kapital, Technologie. Ein Team.", teamIntro: "",
    profiles: [
      { ...PEOPLE_DE.david, role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        paras: ["Jurist, Startup-Gründer und Mehrfach-CEO. 25+ Jahre operative Erfahrung, Transaktionen über 600 Mio. € in zwei Branchen.",
          "2015 Pionierauftrag von Deutscher Telekom und A1. Gründer und CEO der geolad (30+ Mitarbeiter, EU & Asien). DSGVO und EU AI Act in der Praxis."],
        quote: "Juristisch denkend. Unternehmerisch handelnd. Mit Impact umsetzend.",
        cards: [["Telekom & Data", "Deutsche Telekom, A1, Orange, Zain, Viettel, Huawei, Ericsson"], ["Wissenschaft & Bildung", "European Stroke Organisation, World Stroke Organization, Donau-Universität Krems, Sigmund Freud PrivatUniversität (in Vorbereitung)"], ["Immobilien", "Wiener Privatbank, EPI Immobilien, UNIQA"], ["Legal", "Lansky, Ganzger & Partner, Herbst Kinsky"], ["Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Social Impact", "Integrationshaus Wien, ORF, Red Bull, vidid"]] },
      { ...PEOPLE_DE.philip, role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Umsetzung",
        paras: ["Enterprise Architect, Programm-Manager und CTO. 25+ Jahre IT-Großprojekte – Schwerpunkt öffentliche Hand, Finanz und Bildung.",
          "Nationale Krankenversicherung Katar (mit McKinsey), Zoll-Import im Finanzministerium, ePassport und Grenzkontrolle. CTO & Co-Founder OptInk, GF Merkit Consulting. MSc TU Wien, IPMA Level C."],
        quote: "Systemisch denkend. Pragmatisch bauend. Verlässlich betreibend.",
        cards: [["Öffentliche Hand", "BMF / Zoll, ePassport, Grenzkontrolle"], ["Gesundheit", "Nationale Krankenversicherung Katar (McKinsey)"], ["Bildung", "Untis – IAM & SSO für Schulen; TU Wien"], ["Finanz & Payments", "Global Blue, Arthur D. Little, Core Banking"], ["Telekom", "Telekom Austria, VeriSign / 3united"], ["Ventures", "OptInk, Merkit Consulting, Porsche Informatik, RISE"]] },
    ],
    comp: {
      label: "Datenschutz & Sicherheit", title: "DSGVO, Telekom-Recht, AI Act, ISO 27001 – ab Tag eins.",
      p: "Rechtliche Bewertung und technische Umsetzung aus einem Team – geschult am Telekommunikationsrecht mehrerer Länder, das strenger reguliert und enger überwacht ist als die DSGVO allein.",
      cols: [
        { t: "Sicherheit & Architektur", who: "Philip Kügler", items: ["Sicherheitsanforderungen nach ISO 27001 und BSI sowie ITIL-Prozesse in Projekten umgesetzt", "IAM & SSO: Keycloak, OIDC/SAML", "Sichere internationale Datenübertragung", "Hochverfügbarkeit, Backup, Failover", "Privacy by Design und AI-Governance"] },
        { t: "Recht & Regulierung", who: "David Brainin", items: ["Telekommunikationsrecht mehrerer Länder, u. a. TKG", "8 Jahre DSGVO-Praxis in vier Branchen", "Art. 9 DSGVO: Gesundheitsdaten und Einwilligung", "Folgenabschätzung für AI-Systeme", "AI Act: Risikoklassen, Konformität, Dokumentation", "Datentransfers EU, MENA, ASEAN (Schrems II)"] },
      ],
    },
    tLabel: "AI-Transformation", tTitle: "Weniger Kosten. Neue Umsätze.",
    tP: "Drei Hebel: Automatisierung, neue Umsatzquellen, Agentic AI – mit messbaren Zielen je Projekt.",
    opexT: "OPEX-Reduktion", opex: ["Automatisierung repetitiver Prozesse", "AI-gestützte Qualitätssicherung", "Intelligente Dokumenten- und Vertragsanalyse", "Konsolidierte Datenquellen"],
    revT: "Neue Umsätze", rev: ["Datenmonetarisierung", "AI-gestützte Produkte und Services", "Plattform- und Marktplatzmodelle", "SaaS aus internen Lösungen"],
    kpis: [{ v: "6–9", u: " Monate", l: "typische Laufzeit eines klar abgegrenzten Projekts" }, { v: "30 %", l: "Einsparziel je automatisiertem Prozess, projektspezifisch vereinbart" }, { v: "Neu", l: "Umsatzquellen aus vorhandenen Daten und Assets", gold: true }],
    sLabel: "Leistungen", sTitle: "Von der Strategie bis zum Betrieb.",
    serv: [
      { t: "AI-Strategie & Entscheidungsgrundlage", d: "Für Geschäftsführung und Vorstand: priorisierte Anwendungsfälle, Wirtschaftlichkeitsbewertung, Daten- und Risikoprüfung nach DSGVO und AI Act, Umsetzungsplan.", tags: ["Anwendungsfälle", "Business Case", "DSGVO & AI Act"] },
      { t: "AI-Implementierung & Automatisierung", d: "Klar abgegrenzter Pilot, Integration in bestehende Systeme, Evaluation und menschliche Freigaben – bis zu Betrieb und Monitoring. Inklusive Agentic AI.", tags: ["Pilot", "Integration", "Agentic AI"] },
      { t: "Plattformen & Venture Building", d: "Für Vorhaben in regulierten Märkten wie Gesundheit, Bildung und Verwaltung: Produkt, Governance, Finanzierung, Architektur und Markteinführung – bis zum gemeinsamen Joint Venture.", tags: ["Gesundheit & Bildung", "Governance", "Joint Ventures"] },
      { t: "Executive Advisory & Strategic Support", d: "Strategische Begleitung von Geschäftsführung und Vorstand, Transaktionsbegleitung, Interim Management.", tags: ["Geschäftsführung", "Transaktionen", "Interim"] },
    ],
    netLabel: "Netzwerk", netTitle: "Das richtige Team für jede Aufgabe.", netP: "Spezialisten aus Recht, Technologie, Finanz und Industrie – projektbezogen.",
    clusters: [["Legal", "Gesellschafts-, IP- und Regulierungsrecht – Lansky, Ganzger & Partner, Herbst Kinsky"], ["Tech & AI", "Architekten, Security & IAM, AI- und Data-Engineers"], ["Öffentliche Hand & Gesundheit", "Ministerien, Register, Versicherer, Universitäten"], ["Finance", "RBI, Wiener Privatbank, VCs, Family Offices"], ["Industry", "Telekom-Operatoren, Transformationsexperten, UNIQA"]],
    netBar: "Beratung und Umsetzung aus einem Team.", netBadge: "Beratung & Umsetzung",
    pLabel: "Prozess", pTitle: "Typischerweise 6–9 Monate bis zum Ergebnis.",
    proc: [{ t: "Kick-off", sub: "Woche 1", d: "Umfang und erste Hebel" }, { t: "Analyse", sub: "Woche 2–3", d: "Prozesse, Daten, Potenziale" }, { t: "Plan", sub: "Woche 4–5", d: "Maßnahmen, Kennzahlen, Meilensteine" }, { t: "Umsetzung", sub: "Monat 2–6", d: "Implementierung, AI-Integration" }, { t: "Wirkung", sub: "Monat 6–9", d: "Geringere Kosten, neue Umsätze" }],
    pBar: ["Typisch:", "6–9 Monate", "bei vereinbartem Umfang"], pBadge: "Zeitplan je Projekt vereinbart",
  },
  re: {
    nav: [["profil", "Profil"], ["expertise", "Expertise"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    chapters: ["Profil", "Expertise", "Leistungen", "Netzwerk", "Prozess", "Kontakt", "Insights"],
    profileTitle: "25 Jahre. Über 600 Mio. € Transaktionsvolumen.",
    h1: ["Fundierte Analyse.", "Präzise Struktur.", "Sicheres Closing."],
    heroP: "Über 600 Mio. € Transaktionsvolumen in Wohnen, Gewerbe und Hotel. Strukturierung, Projektmanagement, Closing.",
    ctaA: "Leistungen", ctaB: "Profil",
    contactP: "Ankauf, Verkauf, Entwicklung oder Hotel-Repositionierung: Besprechen wir Ihr Vorhaben.",
    stats: [{ v: "600+", l: "Mio. € Transaktions\u00advolumen" }, { v: "25+", l: "Jahre persönliche Erfahrung in Immobilien & Hospitality (David Brainin)" }, { v: "3", l: "Asset-Klassen" }, { v: "AT · CEE · ES", l: "Märkte" }],
    partnerTitle: "Projekterfahrung",
    profileLabel: "Founder & Managing Partner",
    profile: { ...PEOPLE_DE.david, role: "Founder & Managing Partner", focus: "Recht · Transaktionen · Real Estate",
      paras: ["Jurist und Mehrfach-CEO. 25+ Jahre Immobilien und Hospitality, Transaktionen über 600 Mio. €.", "Partner für institutionelle Investoren, Family Offices und Developer in Österreich, CEE und Spanien."],
      quote: "Juristisch denkend. Unternehmerisch handelnd. Mit Impact umsetzend.",
      cards: [["Wohnen", "EPI Immobilien, Trimmobilien, Conwert, Akkadia"], ["Gewerbe & Büro", "An- und Verkäufe"], ["Hotel & Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Retail & Mixed Use", "Beratung und Strukturierung"], ["Entwicklung", "Machbarkeit, Behörden, Projektmanagement"], ["Verkauf & Ankauf", "Buy-Side- und Sell-Side-Mandate"]] },
    tLabel: "Real Estate Expertise", tTitle: "Von der Analyse zum Closing.", tP: "Marktwissen, rechtliche Präzision, operative Umsetzung.",
    opexT: "Transaktion & Advisory", opex: ["Markt- und Machbarkeitsanalyse", "Due Diligence: rechtlich, finanziell, technisch", "Finanzierungs- und Eigenkapitalstruktur", "Verhandlung und Behördenkoordination"],
    revT: "Verkauf, Ankauf & Projekte", rev: ["Buy-Side- und Sell-Side-Mandate", "Entwicklung bis zur Übergabe", "Hotel-Repositionierung", "Deal-Sourcing CEE & Spanien"],
    kpis: [{ v: "600+", l: "Mio. € Transaktions\u00advolumen" }, { v: "25+", l: "Jahre Umsetzungserfahrung" }, { v: "CEE & Spanien", l: "Transaktionsraum" }],
    sLabel: "Leistungen", sTitle: "Ankauf, Verkauf, Projekte – bis zum Closing.",
    serv: [
      { t: "Transaktionsberatung", d: "Buy-Side und Sell-Side: Marktanalyse, Due Diligence, Transaktionsstruktur und Verhandlung – bis zu Signing und Closing. Rechtliche Leistungen erbringen unsere Partnerkanzleien.", tags: ["Ankauf & Verkauf", "Due Diligence", "Closing"] },
      { t: "Projekt- und Entwicklungsmanagement", d: "Entwicklung, Sanierung und Repositionierung: Budget, Termine, Behörden – von der Machbarkeit bis zur Übergabe.", tags: ["Entwicklung", "Sanierung", "Behörden"] },
      { t: "Hospitality", d: "Repositionierung, Markenwahl und Betreiberverhandlungen für Hotelimmobilien.", tags: ["Hotels", "Betreiber", "Repositionierung"] },
    ],
    netLabel: "Netzwerk", netTitle: "Das richtige Team für jeden Deal.", netP: "Partner aus Recht, Immobilien, Finanz und Industrie – je Mandat.",
    clusters: [["Legal", "DSC Rechtsanwälte, Herbst Kinsky – Immobilien-, Gesellschafts- und Transaktionsrecht"], ["Real Estate", "EPI Immobilien, Akkadia, Arcotel, Plaza"], ["Finance", "RBI, Wiener Privatbank, Family Offices"], ["Industry", "UNIQA, Stadt Wien, Baupartner"], ["Tech & AI", "PropTech, digitales Asset-Management"]],
    netBar: "Beratung und Umsetzung aus einem Team.", netBadge: "Beratung & Umsetzung",
    pLabel: "Prozess", pTitle: "Typischerweise 3–6 Monate bis zum Closing.",
    proc: [{ t: "Briefing", sub: "Woche 1", d: "Mandat, Ziele, Zeitplan" }, { t: "Analyse", sub: "Woche 2–3", d: "Markt, Recht, Risiko" }, { t: "Struktur", sub: "Woche 3–5", d: "Deal, Finanzierung, Strategie" }, { t: "Verhandlung", sub: "Monat 2–4", d: "Deal-Management, Behörden" }, { t: "Closing", sub: "Monat 3–6", d: "Signing, Vollzug, Übergabe" }],
    pBar: ["Typisch:", "3–6 Monate", "vom Mandat zum Closing"], pBadge: "Operative Umsetzung",
  },
},

// ─────────────────────────────────────────────────────────────── 中文
cn: {
  meta: { home: "InVentures — 在监管最严格的市场中打造创业项目", tech: "技术与AI — InVentures", re: "房地产与酒店业 — InVentures", insights: "洞察 — InVentures", impressum: "法律声明 — InVentures", datenschutz: "隐私政策 — InVentures", notFound: "页面未找到 — InVentures",
    desc: { home: "InVentures在监管最严格的市场中打造创业项目：法律、资本与技术由同一团队提供——技术与AI、房地产与酒店业，立足维也纳。", tech: "面向受监管市场的AI战略、实施与平台，从第一天起兼顾GDPR与AI法案。InVentures，维也纳。", re: "交易顾问、项目与开发管理及酒店业：交易额逾6亿欧元。InVentures，维也纳。", insights: "关于AI、监管与房地产的原创分析和精选市场报告。", impressum: "InVentures法律声明，法律实体为Inside Holding & Real Estate GmbH。", datenschutz: "InVentures隐私政策：不使用Cookie、不追踪，字体与图片均自行托管。" } },
  ui: {
    entity: "Inside Holding & Real Estate GmbH 旗下项目", entityLong: "David Brainin与Philip Kügler的合资项目。法律实体：Inside Holding & Real Estate GmbH。",
    back: "返回总览", menu: "菜单", since06: "始于2006年", since15: "始于2015年",
    imprint: "法律声明", privacy: "隐私政策", cookies: "Cookie 设置", trackTech: "技术与AI", trackRe: "房地产", switchTrack: "返回总览",
    discuss: "洽谈项目", allInsights: "全部洞察", refNote: "所列机构来自两位合伙人的项目经验，包括InVentures成立之前。", refLink: "参考项目说明", langHint: { de: "德文文章", en: "英文文章" },
    notFoundTitle: "页面未找到。", notFoundText: "该页面不存在或已移动。",
    readArticle: "阅读全文", closeArticle: "收起文章", showRefs: "查看行业与客户", hideRefs: "收起行业与客户",
  },
  homeNav: [["/tech", "技术与AI"], ["/real-estate", "房地产与酒店业"], ["referenzen", "参考项目"], ["team", "团队"], ["kontakt", "联系"]],
  home: {
    brandSub: "AI 与房地产领域的 Venture Building",
    h1: "我们在监管最严格的市场中打造创业项目。",
    brandP: "法律、资本与技术由同一团队提供——服务AI与房地产领域的企业、投资者和创业者。",
    chapters: ["领域", "经验", "团队", "能力", "参考", "历程", "联系"],
    claim: ["Analysis.", "Execution.", "Impact."],
    selectTitle: "两大领域，一个平台。", selectSub: "选择领域",
    tracks: {
      tech: { label: "技术与AI", sub: "AI转型、受监管平台、公司建设", tags: ["AI转型", "GDPR与AI法案", "医疗与教育", "公司建设"], cta: "了解技术与AI" },
      re: { label: "房地产与\n酒店业", sub: "买卖、交易、项目管理", tags: ["买卖", "交易", "项目管理", "酒店业"], cta: "了解房地产" },
    },
    waysLabel: "合作方式",
    ways: [
      { t: "咨询", d: "分析、战略、结构设计与可靠的决策依据——服务管理层、投资者与公共机构。" },
      { t: "实施", d: "技术实施、项目管理与运营责任——直至投入运营或完成交割。" },
      { t: "创业建设与投资", d: "在受监管市场中的自有创业项目、与合作伙伴及家族办公室的共同投资、结构化融资。" },
    ],
  },
  team: {
    label: "团队", title: "两位合伙人，逾50年经验。",
    intro: "我们将法律、资本与公司建设，同架构、安全与交付相结合——久经磨合的团队。",
    people: [
      { ...PEOPLE.david, role: "创始人兼管理合伙人", focus: "法律 · 资本 · 公司建设",
        bio: "法律专家、创业者及连续CEO。25年以上运营经验，交易额逾6亿欧元，geolad创始人。GDPR与欧盟AI法案实践经验丰富。",
        facts: [{ v: "€600m+", l: "交易额" }, { v: "€45m+", l: "调动资本" }, { v: "€12m+", l: "研究资助" }] },
      { ...PEOPLE.philip, role: "技术管理合伙人", focus: "架构 · 安全 · 交付",
        bio: "企业架构师兼CTO。25年以上为政府、医疗、教育和电信主导大型IT项目——从海关系统到国家医疗保险。",
        facts: [{ v: "4", l: "国家级政府项目" }, { v: "€10m+", l: "海关项目预算责任" }, { v: "5", l: "年联邦、州与学校身份管理" }] },
    ],
    bondsLabel: "我们的结合",
    bonds: [
      { t: "受监管市场", d: "医疗、教育、公共部门、金融、房地产。" },
      { t: "敏感数据", d: "GDPR、AI法案、ISO 27001——从第一天起。" },
      { t: "从构想到运营", d: "设立、融资、架构、上线。同一团队。" },
    ],
    cta: "洽谈项目",
  },
  regulated: {
    label: "受监管市场", title: "敏感数据需要的不只是软件。",
    focus: "在最敏感的领域落实GDPR：个人电信、健康与教育数据。",
    intro: "法律基础、安全架构、资金保障——以及有经验的合作伙伴。",
    pillars: [
      { t: "安全设计", who: "Philip Kügler", d: "符合ISO 27001与BSI的安全要求、身份与访问管理。" },
      { t: "架构与运营", who: "Philip Kügler", d: "国家级登记系统与平台——高可用、全面集成，直至投入运营。" },
      { t: "公司建设与资本", who: "David Brainin", d: "设立、治理、市场进入。4500万欧元以上资本，1200万欧元以上资助。" },
      { t: "法律与合规", who: "David Brainin", d: "GDPR第9条、影响评估、AI法案分级。" },
    ],
    telecom: { label: "电信法", claim: "在数据保护最严格的领域历练：电信法。", p: "两位合伙人多年来在多个国家的电信法框架下处理电信数据——这些法律比GDPR本身更细致、更严格，监管也更密切。" },
    fieldsLabel: "参考项目",
    fields: [
      { t: "医疗与科研", items: ["卡塔尔国家医疗保险（与麦肯锡）", "欧洲卒中组织", "世界卒中组织"] },
      { t: "教育", items: ["Untis——联邦、州与学校身份管理", "多瑙大学克雷姆斯", "维也纳技术大学"] },
      { t: "公共部门", items: ["奥地利财政部／海关", "电子护照与边境管控", "维也纳市"] },
      { t: "社会", items: ["维也纳融合之家", "vidid协会", "ORF"] },
    ],
    closing: "最终成果：专业人士、机构与政府放心托付数据的平台。",
    refLabel: "参考项目", refTitle: "医疗、教育与政务领域的技术前沿。", refIntro: "人们每天信赖的系统。",
  },
  timeline: { label: "发展历程", title: "两条路径，自2016年起共同合作。", sub: "房地产、电信数据、政府平台——以及共同创办的企业。", joint: "携手", more: "查看完整历程", less: "仅显示重点" },
  clients: { label: "项目经验", title: "企业、政府与投资者信赖我们的经验。", fo: "+ 非公开家族办公室" },
  groups: { telecom: "电信与数据", public: "公共部门与医疗", edu: "教育与科研", finance: "金融与支付", industry: "产业与技术", re: "房地产与酒店业", legal: "法律、媒体与社会" },
  contact: {
    label: "联系", title: "联系我们。", p: "战略、受监管市场项目、合作机会。",
    first: "首次沟通中，我们将明确您的目标、现状与时间安排，以及适合的合作方式：咨询、实施或合资。",
    web: "网站", mail: "电子邮件", loc: "地点", locV: "奥地利维也纳", entity: "法律实体",
    people: "联系人", peopleV: ["David Brainin——法律、资本、房地产", "Philip Kügler——技术、安全、产品"],
    form: {
      name: "姓名", company: "公司", email: "电子邮件", topic: "主题", message: "留言",
      topics: ["技术与AI", "房地产与酒店业", "受监管市场／合资项目", "其他"],
      namePh: "您的姓名", companyPh: "可选", emailPh: "您的邮箱", messagePh: "简要描述您的需求",
      submit: "发送项目咨询", sending: "发送中……",
      privacy: "我们依据", privacyLink: "隐私政策处理您的数据",
      success: "感谢——我们将尽快与您联系。",
      fallbackTitle: "您的留言已准备就绪。", fallbackText: "点击一下，即可在您的邮件程序中打开已准备好的邮件。",
      fallbackBtn: "打开邮件", fallbackOr: "或直接发送至", required: "请填写姓名和有效的电子邮件地址。",
    },
  },
  insights: { label: "洞察", title: "市场动态。", sub: "2026年2月以来的精选分析。", all: "全部", more: "更多", read: "阅读", view: "InVentures观点", viewSub: "我们的原创分析。", pageTitle: "洞察", pageSub: "关于AI、监管与房地产的原创分析和精选市场报告。", back: "全部洞察" },
  tech: {
    nav: [["team", "团队"], ["compliance", "合规"], ["leistungen", "服务"], ["netzwerk", "网络"], ["prozess", "流程"], ["kontakt", "联系"]],
    chapters: ["团队", "合规", "转型", "服务", "网络", "流程", "联系", "洞察"],
    h1: ["深度分析。", "快速执行。", "可衡量的成效。"],
    heroP: "AI转型、智能体AI与受监管市场平台。范围明确、目标可衡量的项目——通常6至9个月。",
    ctaA: "服务", ctaB: "团队",
    contactP: "受监管市场中的AI项目、平台或创业项目：欢迎洽谈您的计划。",
    visual: { label: "合规设计", layers: [["应用场景", "AI智能体、自动化、新服务"], ["集成与运营", "接口、身份、监控"], ["数据与系统", "登记系统、ERP、数据平台"]], chips: ["GDPR", "AI法案", "ISO 27001", "BSI"], caption: "法律、安全与技术融于同一架构。" },
    stats: [{ v: "€45m+", l: "调动资本" }, { v: "€12m+", l: "研究资助" }, { v: "4", l: "国家级政府项目" }, { v: "€10m+", l: "海关项目预算责任" }, { v: "40+", l: "DACH与中东北非项目" }, { v: "50+", l: "年合计经验" }],
    partnerTitle: "项目经验",
    teamLabel: "团队", teamTitle: "法律、资本、技术。同一团队。", teamIntro: "",
    profiles: [
      { ...PEOPLE.david, role: "创始人兼管理合伙人", focus: "法律 · 资本 · 公司建设",
        paras: ["法律专家、创业者及连续CEO。25年以上运营经验，横跨两大行业交易额逾6亿欧元。", "2015年受德国电信和A1委托开拓新业务。geolad创始人兼CEO（30余名员工，欧洲与亚洲）。GDPR与欧盟AI法案实践经验丰富。"],
        quote: "以法律思维思考。以企业家方式行动。以成效付诸实施。",
        cards: [["电信与数据", "德国电信、A1、Orange、Zain、Viettel、华为、爱立信"], ["科研与教育", "欧洲卒中组织、世界卒中组织、多瑙大学克雷姆斯、西格蒙德·弗洛伊德私立大学（筹备中）"], ["房地产", "维也纳私人银行、EPI不动产、UNIQA"], ["法律", "Lansky, Ganzger & Partner、Herbst Kinsky"], ["酒店业", "EPI Hospitality、Ibis、Arcotel"], ["社会公益", "维也纳融合之家、ORF、红牛、vidid"]] },
      { ...PEOPLE.philip, role: "技术管理合伙人", focus: "架构 · 安全 · 交付",
        paras: ["企业架构师、项目集经理及CTO。25年以上大型IT项目经验——专注公共部门、金融与教育。", "卡塔尔国家医疗保险（与麦肯锡）、奥地利财政部海关进口、电子护照与边境管控。OptInk首席技术官兼联合创始人，Merkit Consulting总经理。维也纳技术大学硕士，IPMA C级。"],
        quote: "系统化思考。务实地构建。可靠地运行。",
        cards: [["公共部门", "财政部／海关、电子护照、边境管控"], ["医疗", "卡塔尔国家医疗保险（麦肯锡）"], ["教育", "Untis——学校身份管理与单点登录；维也纳技术大学"], ["金融与支付", "Global Blue、理特咨询、核心银行"], ["电信", "奥地利电信、VeriSign / 3united"], ["创业", "OptInk、Merkit Consulting、保时捷信息技术、RISE"]] },
    ],
    comp: {
      label: "数据保护与安全", title: "GDPR、电信法、AI法案、ISO 27001——从第一天起。",
      p: "法律评估与技术实施由同一团队完成——历经多国电信法的锤炼，其监管比GDPR本身更严格、更密切。",
      cols: [
        { t: "安全与架构", who: "Philip Kügler", items: ["在项目中落实ISO 27001与BSI安全要求及ITIL流程", "身份管理与单点登录：Keycloak、OIDC/SAML", "安全的国际数据传输", "高可用、备份、故障切换", "隐私设计与AI治理"] },
        { t: "法律与监管", who: "David Brainin", items: ["多国电信法，包括奥地利TKG", "四大行业8年GDPR实践", "GDPR第9条：健康数据与同意", "AI系统影响评估", "AI法案：风险等级、合规、文档", "欧盟、中东北非、东盟数据传输（Schrems II）"] },
      ],
    },
    tLabel: "AI转型", tTitle: "降低成本，创造新收入。",
    tP: "三大杠杆：自动化、新收入来源、智能体AI——每个项目都有可衡量的目标。",
    opexT: "运营成本优化", opex: ["重复流程自动化", "AI辅助质量保障", "智能文档与合同分析", "整合数据源"],
    revT: "新收入", rev: ["数据变现", "AI驱动的产品与服务", "平台与市场模式", "内部方案SaaS化"],
    kpis: [{ v: "6–9", u: " 个月", l: "范围明确项目的典型周期" }, { v: "30%", l: "每个自动化流程的节省目标，按项目约定" }, { v: "全新", l: "来自现有数据与资产的收入来源", gold: true }],
    sLabel: "服务", sTitle: "从战略到运营。",
    serv: [
      { t: "AI战略与决策依据", d: "面向董事会与管理层：优先级排序的应用场景、商业论证、依据GDPR与AI法案的数据与风险审查、实施计划。", tags: ["应用场景", "商业论证", "GDPR与AI法案"] },
      { t: "AI实施与自动化", d: "范围明确的试点、与现有系统集成、评估与人工审批——直至运营与监控。包括智能体AI。", tags: ["试点", "集成", "智能体AI"] },
      { t: "平台与创业建设", d: "面向医疗、教育与公共部门等受监管市场：产品、治理、融资、架构与市场推出——直至共同合资。", tags: ["医疗与教育", "治理", "合资企业"] },
      { t: "高管顾问与战略支持", d: "为管理团队提供战略支持、交易支持与临时管理。", tags: ["管理团队", "交易", "临时管理"] },
    ],
    netLabel: "网络", netTitle: "为每项任务组建合适团队。", netP: "法律、技术、金融与产业专家——按项目组建。",
    clusters: [["法律", "公司、知识产权与监管——Lansky, Ganzger & Partner、Herbst Kinsky"], ["技术与AI", "架构师、安全与身份管理、AI与数据工程师"], ["公共部门与医疗", "部委、登记系统、保险机构、大学"], ["金融", "RBI、维也纳私人银行、风投、家族办公室"], ["行业", "电信运营商、转型专家、UNIQA"]],
    netBar: "咨询与执行，由同一团队完成。", netBadge: "咨询与实施",
    pLabel: "流程", pTitle: "通常6至9个月见成效。",
    proc: [{ t: "启动", sub: "第1周", d: "范围与速赢" }, { t: "分析", sub: "第2–3周", d: "流程、数据、潜力" }, { t: "规划", sub: "第4–5周", d: "措施、KPI、里程碑" }, { t: "执行", sub: "第2–6月", d: "实施与AI集成" }, { t: "成效", sub: "第6–9月", d: "降本增收" }],
    pBar: ["典型周期：", "6–9个月", "按约定范围"], pBadge: "时间表按项目约定",
  },
  re: {
    nav: [["profil", "简介"], ["expertise", "专业"], ["leistungen", "服务"], ["netzwerk", "网络"], ["prozess", "流程"], ["kontakt", "联系"]],
    chapters: ["简介", "专业", "服务", "网络", "流程", "联系", "洞察"],
    profileTitle: "25年，逾6亿欧元交易。",
    h1: ["深入分析。", "精准架构。", "稳妥交割。"],
    heroP: "住宅、商业与酒店物业交易额逾6亿欧元。结构设计、项目管理、交割。",
    ctaA: "服务", ctaB: "简介",
    contactP: "收购、出售、开发或酒店重新定位：欢迎洽谈您的项目。",
    stats: [{ v: "€600m+", l: "交易额" }, { v: "25+", l: "年房地产与酒店业个人经验（David Brainin）" }, { v: "3", l: "资产类别" }, { v: "AT · CEE · ES", l: "市场" }],
    partnerTitle: "项目经验",
    profileLabel: "创始人兼管理合伙人",
    profile: { ...PEOPLE.david, role: "创始人兼管理合伙人", focus: "法律 · 交易 · 房地产",
      paras: ["法律专家及连续CEO。25年以上房地产与酒店业经验，交易额逾6亿欧元。", "服务奥地利、中东欧及西班牙的机构投资者、家族办公室和开发商。"],
      quote: "以法律思维思考。以企业家方式行动。以成效付诸实施。",
      cards: [["住宅", "EPI不动产、Trimmobilien、Conwert、Akkadia"], ["商业与办公", "收购与出售"], ["酒店与餐饮", "EPI Hospitality、Ibis、Arcotel"], ["零售与综合", "咨询与结构设计"], ["开发", "可行性、审批、项目管理"], ["买卖", "买方与卖方授权"]] },
    tLabel: "房地产专业", tTitle: "从分析到交割。", tP: "市场洞察、法律精准、实际执行。",
    opexT: "交易与顾问", opex: ["市场与可行性分析", "尽职调查：法律、财务、技术", "融资与股权结构", "谈判与政府协调"],
    revT: "买卖与项目", rev: ["买方与卖方授权", "开发直至交付", "酒店重新定位", "中东欧与西班牙交易来源"],
    kpis: [{ v: "6亿欧元+", l: "交易记录" }, { v: "25+", l: "年执行经验" }, { v: "中东欧与西班牙", l: "交易范围" }],
    sLabel: "服务", sTitle: "收购、出售、开发——直至交割。",
    serv: [
      { t: "交易顾问", d: "买方与卖方：市场分析、尽职调查、交易结构与谈判——直至签约与交割。法律工作由我们的合作律所完成。", tags: ["收购与出售", "尽职调查", "交割"] },
      { t: "项目与开发管理", d: "开发、翻新与重新定位：预算、进度、审批——从可行性研究到交付。", tags: ["开发", "翻新", "审批"] },
      { t: "酒店业", d: "酒店物业的重新定位、品牌选择与运营商谈判。", tags: ["酒店", "运营商", "重新定位"] },
    ],
    netLabel: "网络", netTitle: "为每笔交易组建合适团队。", netP: "法律、房地产、金融与产业合作伙伴——按授权组建。",
    clusters: [["法律", "DSC律所、Herbst Kinsky——房地产、公司与交易法"], ["房地产", "EPI不动产、Akkadia、Arcotel、Plaza"], ["金融", "RBI、维也纳私人银行、家族办公室"], ["行业", "UNIQA、维也纳市、建筑合作伙伴"], ["技术与AI", "房地产科技、数字资产管理"]],
    netBar: "咨询与执行，由同一团队完成。", netBadge: "咨询与实施",
    pLabel: "流程", pTitle: "通常3至6个月完成交割。",
    proc: [{ t: "简报", sub: "第1周", d: "授权、目标、时间表" }, { t: "分析", sub: "第2–3周", d: "市场、法律、风险" }, { t: "结构", sub: "第3–5周", d: "交易、融资、策略" }, { t: "谈判", sub: "第2–4月", d: "交易管理、审批" }, { t: "交割", sub: "第3–6月", d: "签约、完成与移交" }],
    pBar: ["典型周期：", "3–6个月", "从授权到交割"], pBadge: "实际执行",
  },
},
};
