// All user-visible copy of the /new site (EN / DE). Short by design: facts first.
// Facts about David Brainin come from the live site; facts about Philip Kügler from his CV (released by him, 2026-09).

export const LANGS = [["en", "EN"], ["de", "DE"]];
export const HTML_LANG = { en: "en", de: "de" };

// Names without academic titles (English); the German pages add them (David, 2026-09-23).
// "^iur" renders as a small superscript, see Rich in ui.jsx.
const PEOPLE = { david: { key: "david", name: "David Brainin", initials: "DB", accent: "gold", photo: "portrait-brainin" }, philip: { key: "philip", name: "Philip Kügler", initials: "PK", accent: "silver", photo: "portrait-kuegler" } };
const PEOPLE_DE = { david: { ...PEOPLE.david, name: "Mag.^iur David Brainin" }, philip: { ...PEOPLE.philip, name: "Philip Kügler, MSc" } };

export const TX = {
// ─────────────────────────────────────────────────────────────── EN
en: {
  meta: { home: "InVentures — Ventures in regulated markets", tech: "Tech & AI — InVentures", re: "Real Estate & Hospitality — InVentures", insights: "Insights — InVentures", impressum: "Legal notice — InVentures", datenschutz: "Privacy policy — InVentures", notFound: "Page not found — InVentures",
    desc: { home: "Advisory, delivery and venture building in Tech & AI and Real Estate & Hospitality, focused on regulated markets. From Vienna.", tech: "AI strategy, implementation and platforms for regulated markets, with GDPR and the AI Act considered from day one. InVentures, Vienna.", re: "Transaction advisory, project and development management and hospitality: EUR 600m+ in transactions. InVentures, Vienna.", insights: "Own analyses and selected market reports on AI, regulation and real estate.", impressum: "Legal notice of InVentures, a joint venture operated by Inside Holding & Real Estate GmbH.", datenschutz: "Privacy policy of InVentures: no cookies, no tracking, self-hosted fonts and images." } },
  ui: {
    entity: "A project of Inside Holding & Real Estate GmbH", entityLong: "A joint venture of David Brainin and Philip Kügler. Legal entity: Inside Holding & Real Estate GmbH.",
    back: "Back to overview", menu: "Menu", since06: "Since 2006", since15: "Since 2015",
    imprint: "Legal notice", privacy: "Privacy policy", cookies: "Cookie Settings", trackTech: "Tech & AI", trackRe: "Real Estate", switchTrack: "Back to overview",
    discuss: "Discuss your project", allInsights: "All insights", refNote: "Organisations from our partners' project experience, including before InVentures was founded.", refLink: "Note on references", langHint: { de: "Article in German", en: "Article in English" },
    notFoundTitle: "Page not found.", notFoundText: "This page does not exist or has moved.",
    readArticle: "Read full article", closeArticle: "Collapse article", showRefs: "Show selected sectors & clients", hideRefs: "Hide selected sectors & clients",
  },
  homeNav: [["/tech", "Tech & AI"], ["/real-estate", "Real Estate & Hospitality"], ["referenzen", "References"], ["team", "Team"], ["kontakt", "Contact"]],
  home: {
    brandSub: "Venture Building in Tech & Real Estate",
    h1: "We build ventures in the most regulated markets.",
    brandP: "Law, capital and technology in one team — for companies, investors and founders in tech and real estate.",
    chapters: ["Areas", "Experience", "Team", "Expertise", "References", "Track Record", "Contact"],
    claim: ["Analysis.", "Execution.", "Impact."],
    hero: { h1: "Ventures in regulated markets.", sub: "Technology and real estate. Legal precision, entrepreneurial execution." },
    selectTitle: "Two areas, one team.", selectSub: "Choose your area",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI transformation, regulated platforms, company building", tags: ["AI Transformation", "GDPR & AI Act", "Health & Education", "Company Building"], cta: "Explore Tech & AI" },
      re: { label: "Real Estate &\nHospitality", sub: "Sale & acquisition, transactions, project management", tags: ["Sale & Acquisition", "Transactions", "Project Management", "Hospitality"], cta: "Explore Real Estate" },
    },
    waysLabel: "How we work with you",
    ways: [
      { t: "Advisory", d: "Analysis, strategy and structuring as a sound basis for decisions." },
      { t: "Delivery", d: "Implementation and project management until the system is live or the deal has closed." },
      { t: "Venture building & investments", d: "Our own ventures in regulated markets, co-investments with partners and family offices, structured financing." },
    ],
  },
  team: {
    label: "Team", title: "Two partners. 50+ years of experience.",
    intro: "The two have worked together since 2016, most recently on prax.net.",
    people: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        bio: "Trained as a lawyer (full law degree, Mag. iur.), founder of geolad and CEO of several companies. 25+ years of operational responsibility, GDPR and EU AI Act in daily practice.",
        facts: [{ v: "€600m+", l: "Transaction volume" }, { v: "€45m+", l: "Capital mobilised" }, { v: "€12m+", l: "Research grants" }] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        bio: "Enterprise architect and CTO. 25+ years of large IT programmes in government, health, education and telecom, from Austrian customs to Qatar's national health insurance.",
        facts: [{ v: "4", l: "National government IT programmes" }, { v: "€10m+", l: "Programme stream managed (customs)" }, { v: "5", l: "Years of identity management for authorities and schools" }] },
    ],
    bondsLabel: "What we combine",
    bonds: [
      { t: "Regulated markets", d: "Health, education, public sector, finance, real estate." },
      { t: "Sensitive data", d: "GDPR, AI Act, ISO 27001 — from day one." },
      { t: "Concept to operation", d: "Incorporation, funding, architecture, rollout. One team." },
    ],
    cta: "Discuss a project",
  },
  regulated: {
    label: "Regulated markets", title: "Sensitive data needs more than software.",
    focus: "GDPR in the most sensitive areas: personal telecom, health and education data.",
    intro: "We bring the legal basis, a secure architecture and the funding.",
    pillars: [
      { t: "Security by Design", who: "Philip Kügler", d: "Security requirements per ISO 27001 and BSI, identity and access management." },
      { t: "Architecture & Operations", who: "Philip Kügler", d: "Highly available national registries and platforms, through to live operation." },
      { t: "Company Building & Capital", who: "David Brainin", d: "Incorporation, governance, go-to-market. €45m+ capital, €12m+ grants." },
      { t: "Legal & Compliance", who: "David Brainin", d: "Art. 9 GDPR, impact assessments, AI Act classification." },
    ],
    telecom: { label: "Telecommunications law", claim: "In telecommunications, the GDPR is only the starting point.", p: "Both partners have worked with telecom data in several countries for years — under confidentiality of communications, strict purpose limits and deletion duties beyond the GDPR." },
    fieldsLabel: "References",
    fields: [
      { t: "Health & Science", items: ["National health insurance Qatar (with McKinsey)", "European Stroke Organisation", "World Stroke Organization"] },
      { t: "Education", items: ["Untis — identity and access management for federal and state authorities and schools", "Danube University Krems", "TU Wien"] },
      { t: "Public Sector", items: ["Austrian Ministry of Finance — customs", "ePassport & border control", "City of Vienna"] },
      { t: "Society", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    refLabel: "References", refTitle: "Selected projects in health, education and government.", refIntro: "Systems people rely on every day.",
  },
  timeline: { label: "Track Record", title: "Two paths. Joint projects since 2016.", sub: "Real estate, telecom data, government platforms and our joint ventures.", joint: "Together", more: "Show full track record", less: "Show highlights only" },
  clients: { label: "Project experience", title: "Who we have worked with.", fo: "+ undisclosed family offices" },
  groups: { telecom: "Telecom & Data", public: "Public Sector & Health", edu: "Education & Science", finance: "Finance & Payments", industry: "Industry & Technology", re: "Real Estate & Hospitality", legal: "Legal, Media & Society" },
  contact: {
    label: "Contact", title: "Let's talk.", p: "Tell us about your project.",
    first: "In a first conversation we clarify your goal, starting point and timeline, and whether advisory, delivery or a joint venture fits best.",
    web: "Web", mail: "E-mail", loc: "Location", locV: "Vienna, Austria", entity: "Legal entity",
    people: "Contact persons", peopleV: ["David Brainin — law, capital, real estate", "Philip Kügler — technology, security, product"],
    form: {
      name: "Name", company: "Company", email: "E-mail", topic: "Topic", message: "Message",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulated markets / joint venture", "Other"],
      namePh: "Your name", companyPh: "Optional", emailPh: "you@company.com", messagePh: "Your enquiry in a few lines",
      submit: "Send project enquiry", sending: "Sending…",
      privacy: "We process your data according to our", privacyLink: "privacy policy",
      success: "Thank you, we'll be in touch shortly.",
      fallbackTitle: "Not sent yet.", fallbackText: "One click opens it, fully prepared, in your e-mail app.",
      fallbackBtn: "Open e-mail", fallbackOr: "or write to", required: "Please enter your name and a valid e-mail address.",
    },
  },
  insights: { label: "Insights", title: "What moves the market.", sub: "Selected analyses since February 2026.", all: "All", more: "Show more", read: "Read", view: "InVentures View", viewSub: "Our own analyses.", pageTitle: "Insights", pageSub: "Our own analyses and selected market reports on AI, regulation and real estate.", back: "All insights" },
  tech: {
    nav: [["team", "Team"], ["compliance", "Compliance"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    chapters: ["Team", "Compliance", "Transformation", "Services", "Network", "Process", "Contact", "Insights"],
    h1: ["AI and platforms", "for regulated", "markets."],
    heroP: "AI for companies and public bodies that work with sensitive data. Clearly scoped projects.",
    ctaA: "Services", ctaB: "Team",
    contactP: "An AI project, a platform or a venture in a regulated market: let's discuss your plans.",
    visual: { label: "Compliance by design", layers: [["Use cases", "AI agents, automation, new services"], ["Integration & operations", "Interfaces, identity, monitoring"], ["Data & systems", "Registries, ERP, data platforms"]], chips: ["GDPR", "AI Act", "ISO 27001", "BSI"], caption: "Law, security and technology in one architecture." },
    stats: [{ v: "€45m+", l: "Capital mobilised" }, { v: "€12m+", l: "Research grants" }, { v: "4", l: "National government IT programmes" }, { v: "€10m+", l: "Programme stream managed (customs)" }, { v: "40+", l: "Projects DACH & MENA" }, { v: "50+", l: "Years of combined experience" }],
    partnerTitle: "Project experience",
    teamLabel: "Team", teamTitle: "Law and technology in one team.", teamIntro: "",
    profiles: [
      { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Capital · Company Building",
        paras: ["Trained as a lawyer (full law degree, Mag. iur.) and CEO of several companies. 25+ years of operational experience and €600m+ in transactions.",
          "Pioneer mandate from Deutsche Telekom and A1 in 2015. Founder and CEO of geolad (30+ staff, EU & Asia). GDPR and EU AI Act in practice."],
        quote: "Think like a lawyer, act like an entrepreneur.",
        cards: [["Telecom & Data", "Deutsche Telekom, A1, Orange, Zain, Viettel, Huawei, Ericsson"], ["Science & Education", "European Stroke Organisation, World Stroke Organization, Danube University Krems, Sigmund Freud University Vienna (in preparation)"], ["Real Estate", "Wiener Privatbank, EPI Immobilien, UNIQA"], ["Law Firms", "Lansky, Ganzger & Partner, Herbst Kinsky"], ["Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Society", "Integrationshaus Wien, ORF, Red Bull, vidid"]] },
      { ...PEOPLE.philip, role: "Managing Partner, Technology", focus: "Architecture · Security · Delivery",
        paras: ["Enterprise architect, programme manager and CTO. 25+ years of large IT programmes in the public sector, finance and education.",
          "Qatar's national health insurance (with McKinsey), customs at the Austrian Ministry of Finance, ePassport and border control. CTO & co-founder of OptInk, MD of Merkit Consulting. MSc TU Wien, IPMA Level C."],
        quote: "Build pragmatically, run reliably.",
        cards: [["Public Sector", "Ministry of Finance / customs, ePassport, border control"], ["Health", "National health insurance Qatar (McKinsey)"], ["Education", "Untis — IAM & SSO for schools; TU Wien"], ["Finance & Payments", "Global Blue, Arthur D. Little, core banking"], ["Telecom", "Telekom Austria, VeriSign / 3united"], ["Ventures", "OptInk, Merkit Consulting, Porsche Informatik, RISE"]] },
    ],
    comp: {
      label: "Data Protection & Security", title: "GDPR, AI Act and ISO 27001, built in from day one.",
      p: "Legal assessment and technical implementation from one team, schooled in the telecommunications law of several countries.",
      cols: [
        { t: "Security & Architecture", who: "Philip Kügler", items: ["Security requirements per ISO 27001 and BSI and ITIL processes implemented in projects", "IAM & SSO: Keycloak, OIDC/SAML", "Secure international data transfer", "High availability, backup, failover", "Privacy by design and AI governance"] },
        { t: "Legal & Regulatory", who: "David Brainin", items: ["Telecommunications law in several countries, incl. the Austrian TKG", "8 years of GDPR practice across four industries", "Art. 9 GDPR: health data and consent", "Impact assessments for AI systems", "AI Act: risk classes, conformity, documentation", "Data transfers EU, MENA, ASEAN (Schrems II)"] },
      ],
    },
    tLabel: "AI Transformation", tTitle: "Lower costs. New revenue.",
    tP: "Automation, new revenue streams and agentic AI, each with measurable goals.",
    opexT: "OPEX reduction", opex: ["Automation of repetitive processes", "AI-supported quality assurance", "Smart document and contract analysis", "Consolidated data sources"],
    revT: "New revenue", rev: ["Data monetisation", "AI-driven products and services", "Platform and marketplace models", "SaaS from internal solutions"],
    kpis: [{ v: "6–9", u: " months", l: "typical duration for a clearly scoped project" }, { v: "30%", l: "savings target per automated process, agreed per project" }, { v: "New", l: "revenue streams from existing data and assets", gold: true }],
    sLabel: "Services", sTitle: "From strategy to operation.",
    serv: [
      { t: "AI Strategy & Roadmap", d: "For boards and management: prioritised use cases, business case, data and risk review under GDPR and the AI Act, and an implementation plan.", tags: ["Use Cases", "Business Case", "GDPR & AI Act"] },
      { t: "AI Implementation & Automation", d: "A clearly scoped pilot, integration into existing systems, evaluation and human approval steps through to live operation, including agentic AI.", tags: ["Pilot", "Integration", "Agentic AI"] },
      { t: "Platforms & Venture Building", d: "For projects in regulated markets such as health, education and the public sector: product, governance, funding, architecture and market launch, up to a joint venture.", tags: ["Health & Education", "Governance", "Joint Ventures"] },
      { t: "Executive Advisory & Strategic Support", d: "Strategic support for executive teams, transaction support and interim management.", tags: ["Executive Teams", "Transactions", "Interim"] },
    ],
    netLabel: "Network", netTitle: "The right team for every task.", netP: "Specialists in law, technology, finance and industry.",
    clusters: [["Legal", "Corporate, IP, regulatory — Lansky, Ganzger & Partner, Herbst Kinsky"], ["Tech & AI", "Architects, security & IAM, AI and data engineers"], ["Public & Health", "Ministries, registries, insurers, universities"], ["Finance", "RBI, Wiener Privatbank, VCs, family offices"], ["Industry", "Telecom operators, transformation leaders, UNIQA"]],
    netBar: "We build the team for each project.", netBadge: "Advisory & delivery",
    pLabel: "Process", pTitle: "How a project runs.",
    proc: [{ t: "Kick-off", sub: "Week 1", d: "Scope and quick wins" }, { t: "Analysis", sub: "Week 2–3", d: "Processes, data, potential" }, { t: "Plan", sub: "Week 4–5", d: "Measures, KPIs, milestones" }, { t: "Execution", sub: "Month 2–6", d: "Implementation, AI integration" }, { t: "Impact", sub: "Month 6–9", d: "Lower OPEX, new revenue" }],
    pBar: ["Typical:", "6–9 months", "for an agreed scope"], pBadge: "Timeline agreed per project",
  },
  re: {
    nav: [["profil", "Profile"], ["expertise", "Expertise"], ["leistungen", "Services"], ["netzwerk", "Network"], ["prozess", "Process"], ["kontakt", "Contact"]],
    chapters: ["Profile", "Expertise", "Services", "Network", "Process", "Contact", "Insights"],
    profileTitle: "A lawyer with 25 years in real estate.",
    h1: ["Buying, selling", "and developing", "real estate."],
    heroP: "€600m+ in residential, commercial and hotel transactions, from structuring to closing.",
    ctaA: "Services", ctaB: "Profile",
    contactP: "Acquisition, disposal, development or hotel repositioning: let's discuss your project.",
    stats: [{ v: "€600m+", l: "Transaction volume" }, { v: "25+", l: "Years in real estate & hospitality" }, { v: "3", l: "Asset classes" }, { v: "AT · CEE · ES", l: "Markets" }],
    partnerTitle: "Project experience",
    profileLabel: "Profile",
    profile: { ...PEOPLE.david, role: "Founder & Managing Partner", focus: "Legal · Transactions · Real Estate",
      paras: ["Trained as a lawyer (full law degree, Mag. iur.), CEO of several companies, €600m+ in transactions.", "Partner to institutional investors, family offices and developers in Austria, CEE and Spain."],
      quote: "Think like a lawyer, act like an entrepreneur.",
      cards: [["Residential", "EPI Immobilien, Trimmobilien, Conwert, Akkadia"], ["Commercial & Office", "Acquisitions and disposals"], ["Hotel & Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Retail & Mixed Use", "Advisory and structuring"], ["Development", "Feasibility, permits, project management"], ["Sale & Acquisition", "Buy-side and sell-side mandates"]] },
    tLabel: "Real Estate Expertise", tTitle: "From analysis to closing.", tP: "Market knowledge, legal precision, hands-on execution.",
    opexT: "Transaction & Advisory", opex: ["Market and feasibility analysis", "Due diligence: legal, financial, technical", "Financing and equity structure", "Negotiation and authority coordination"],
    revT: "Sale, Acquisition & Projects", rev: ["Buy-side and sell-side mandates", "Development through to handover", "Hotel repositioning", "Deal sourcing CEE & Spain"],
    kpis: [{ v: "€600m+", l: "transaction volume" }, { v: "25+", l: "years of execution experience" }, { v: "CEE & Spain", l: "markets" }],
    sLabel: "Services", sTitle: "What we take on.",
    serv: [
      { t: "Transaction Advisory", d: "Buy-side and sell-side: market analysis, due diligence, deal structure and negotiation through to signing and closing. Legal work is carried out with our partner law firms.", tags: ["Acquisitions & Disposals", "Due Diligence", "Closing"] },
      { t: "Project & Development Management", d: "Development, refurbishment and repositioning: budget, schedule and authorities, from feasibility to handover.", tags: ["Development", "Refurbishment", "Authorities"] },
      { t: "Hospitality", d: "Repositioning, brand selection and operator negotiations for hotel properties.", tags: ["Hotels", "Operators", "Repositioning"] },
    ],
    netLabel: "Network", netTitle: "The right team for every deal.", netP: "Partners in law, real estate, finance and industry.",
    clusters: [["Legal", "DSC Rechtsanwälte, Herbst Kinsky — RE, corporate, transactions"], ["Real Estate", "EPI Immobilien, Akkadia, Arcotel, Plaza"], ["Finance", "RBI, Wiener Privatbank, family offices"], ["Industry", "UNIQA, City of Vienna, construction partners"], ["Tech & AI", "PropTech, digital asset management"]],
    netBar: "We bring in specialists for each mandate.", netBadge: "Advisory & delivery",
    pLabel: "Process", pTitle: "How a mandate runs.",
    proc: [{ t: "Brief", sub: "Week 1", d: "Mandate, goals, timeline" }, { t: "Analysis", sub: "Week 2–3", d: "Market, legal, risk" }, { t: "Structure", sub: "Week 3–5", d: "Deal, financing, strategy" }, { t: "Negotiation", sub: "Month 2–4", d: "Deal management, authorities" }, { t: "Closing", sub: "Month 3–6", d: "Signing, completion, handover" }],
    pBar: ["Typical:", "3–6 months", "from mandate to closing"], pBadge: "Hands-on execution",
  },
},

// ─────────────────────────────────────────────────────────────── DE
de: {
  meta: { home: "InVentures – Ventures in regulierten Märkten", tech: "Tech & AI — InVentures", re: "Real Estate & Hospitality — InVentures", insights: "Insights — InVentures", impressum: "Impressum — InVentures", datenschutz: "Datenschutz — InVentures", notFound: "Seite nicht gefunden — InVentures",
    desc: { home: "Beratung, Umsetzung und Venture Building in Tech & AI sowie Real Estate & Hospitality, mit Fokus auf regulierte Märkte. Aus Wien.", tech: "AI-Strategie, Umsetzung und Plattformen für regulierte Märkte – DSGVO und AI Act von Beginn an berücksichtigt. InVentures, Wien.", re: "Transaktionsberatung, Projekt- und Entwicklungsmanagement und Hospitality: über 600 Mio. € Transaktionsvolumen. InVentures, Wien.", insights: "Eigene Analysen und ausgewählte Marktberichte zu AI, Regulierung und Immobilien.", impressum: "Impressum von InVentures, einem Joint Venture unter dem Rechtsträger Inside Holding & Real Estate GmbH.", datenschutz: "Datenschutzerklärung von InVentures: keine Cookies, kein Tracking, selbst gehostete Schriften und Bilder." } },
  ui: {
    entity: "Ein Projekt der Inside Holding & Real Estate GmbH", entityLong: "Ein Joint Venture von Mag.^iur David Brainin und Philip Kügler, MSc. Rechtsträger: Inside Holding & Real Estate GmbH.",
    back: "Zur Übersicht", menu: "Menü", since06: "Seit 2006", since15: "Seit 2015",
    imprint: "Impressum", privacy: "Datenschutz", cookies: "Cookie-Einstellungen", trackTech: "Tech & AI", trackRe: "Real Estate", switchTrack: "Zur Übersicht",
    discuss: "Projekt besprechen", allInsights: "Alle Insights", refNote: "Organisationen aus der Projekterfahrung unserer Partner – auch vor Gründung von InVentures.", refLink: "Hinweis zu Referenzen", langHint: { de: "Artikel auf Deutsch", en: "Artikel auf Englisch" },
    notFoundTitle: "Seite nicht gefunden.", notFoundText: "Diese Seite existiert nicht oder wurde verschoben.",
    readArticle: "Ganzen Artikel lesen", closeArticle: "Artikel einklappen", showRefs: "Auswahl an Branchen & Kunden anzeigen", hideRefs: "Auswahl an Branchen & Kunden ausblenden",
  },
  homeNav: [["/tech", "Tech & AI"], ["/real-estate", "Real Estate & Hospitality"], ["referenzen", "Referenzen"], ["team", "Team"], ["kontakt", "Kontakt"]],
  home: {
    brandSub: "Venture Building in Tech & Real Estate",
    h1: "Wir bauen Ventures in den am stärksten regulierten Märkten.",
    brandP: "Recht, Kapital und Technologie aus einem Team – für Unternehmen, Investoren und Gründer im Tech- und Immobilienbereich.",
    chapters: ["Bereiche", "Erfahrung", "Team", "Kompetenz", "Referenzen", "Track Record", "Kontakt"],
    claim: ["Analysis.", "Execution.", "Impact."],
    hero: { h1: "Ventures in regulierten Märkten.", sub: "Technologie und Immobilien. Juristische Präzision, unternehmerische Umsetzung." },
    selectTitle: "Zwei Bereiche, ein Team.", selectSub: "Bereich wählen",
    tracks: {
      tech: { label: "Tech & AI", sub: "AI-Transformation, regulierte Plattformen, Company Building", tags: ["AI-Transformation", "DSGVO & AI Act", "Gesundheit & Bildung", "Company Building"], cta: "Tech & AI entdecken" },
      re: { label: "Real Estate &\nHospitality", sub: "Ankauf & Verkauf, Transaktionen, Projektmanagement", tags: ["Ankauf & Verkauf", "Transaktionen", "Projektmanagement", "Hospitality"], cta: "Real Estate entdecken" },
    },
    waysLabel: "So arbeiten wir mit Ihnen",
    ways: [
      { t: "Beratung", d: "Analyse, Strategie und Strukturierung als belastbare Grundlage für Entscheidungen." },
      { t: "Umsetzung", d: "Implementierung und Projektmanagement, bis das System läuft oder die Transaktion abgeschlossen ist." },
      { t: "Venture Building & Beteiligungen", d: "Eigene Ventures in regulierten Märkten, Co-Investments mit Partnern und Family Offices, strukturierte Finanzierungen." },
    ],
  },
  team: {
    label: "Team", title: "Zwei Partner. Über 50 Jahre Erfahrung.",
    intro: "Seit 2016 arbeiten die beiden an gemeinsamen Projekten, zuletzt an prax.net.",
    people: [
      { ...PEOPLE_DE.david, role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        bio: "Jurist, Gründer der geolad und CEO mehrerer Unternehmen. Über 25 Jahre operative Verantwortung, DSGVO und EU AI Act aus der Praxis.",
        facts: [{ v: "600+", l: "Mio. € Transaktions\u00advolumen" }, { v: "45+", l: "Mio. € Kapital mobilisiert" }, { v: "12+", l: "Mio. € Forschungs\u00adförderung" }] },
      { ...PEOPLE_DE.philip, role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Umsetzung",
        bio: "Enterprise-Architekt und CTO. 25+ Jahre IT-Großprojekte für Verwaltung, Gesundheit, Bildung und Telekom, vom Zoll bis zur Krankenversicherung.",
        facts: [{ v: "4", l: "Staatliche IT-Programme" }, { v: "10+", l: "Mio. € Verantwortung im Zollprogramm" }, { v: "5", l: "Jahre Identity-Management für Behörden und Schulen" }] },
    ],
    bondsLabel: "Was wir verbinden",
    bonds: [
      { t: "Regulierte Märkte", d: "Gesundheit, Bildung, Behörden, Finanz, Immobilien." },
      { t: "Sensible Daten", d: "DSGVO, AI Act, ISO 27001 – ab Tag eins." },
      { t: "Konzept bis Betrieb", d: "Gründung, Finanzierung, Architektur, Rollout. Ein Team." },
    ],
    cta: "Projekt besprechen",
  },
  regulated: {
    label: "Regulierte Märkte", title: "Sensible Daten brauchen mehr als Software.",
    focus: "DSGVO in den sensibelsten Bereichen: personenbezogene Telekom-, Gesundheits- und Bildungsdaten.",
    intro: "Rechtsgrundlage, sichere Architektur und Finanzierung bringen wir mit.",
    pillars: [
      { t: "Security by Design", who: "Philip Kügler", d: "Sicherheitsanforderungen nach ISO 27001 und BSI, Identity- & Access-Management." },
      { t: "Architektur & Betrieb", who: "Philip Kügler", d: "Hochverfügbare nationale Register und Plattformen, bis in den laufenden Betrieb." },
      { t: "Company Building & Kapital", who: "David Brainin", d: "Gründung, Governance, Go-to-Market. Über 45 Mio. € Kapital, über 12 Mio. € Förderungen." },
      { t: "Recht & Compliance", who: "David Brainin", d: "Art. 9 DSGVO, Folgenabschätzung, AI-Act-Klassifizierung." },
    ],
    telecom: { label: "Telekommunikationsrecht", claim: "In der Telekommunikation ist die DSGVO erst der Anfang.", p: "Beide Partner arbeiten seit Jahren mit Telekom-Daten in mehreren Ländern – unter Kommunikationsgeheimnis, strenger Zweckbindung und Löschpflichten, die über die DSGVO hinausgehen." },
    fieldsLabel: "Referenzen",
    fields: [
      { t: "Gesundheit & Wissenschaft", items: ["Nationale Krankenversicherung Katar (mit McKinsey)", "European Stroke Organisation", "World Stroke Organization"] },
      { t: "Bildung", items: ["Untis – Identity- & Access-Management für Bund, Länder und Schulen", "Donau-Universität Krems", "TU Wien"] },
      { t: "Öffentliche Hand", items: ["BMF / Zoll – Unionszollkodex", "ePassport & Grenzkontrolle", "Stadt Wien"] },
      { t: "Gesellschaft", items: ["Integrationshaus Wien", "Verein vidid", "ORF"] },
    ],
    refLabel: "Referenzen", refTitle: "Ausgewählte Projekte in Gesundheit, Bildung und Verwaltung.", refIntro: "Systeme, auf die sich Menschen jeden Tag verlassen.",
  },
  timeline: { label: "Track Record", title: "Zwei Wege. Gemeinsame Projekte seit 2016.", sub: "Immobilien, Telekom-Daten, Regierungsplattformen und unsere gemeinsamen Ventures.", joint: "Gemeinsam", more: "Gesamten Track Record anzeigen", less: "Nur Highlights anzeigen" },
  clients: { label: "Projekterfahrung", title: "Mit wem wir zusammengearbeitet haben.", fo: "+ nicht genannte Family Offices" },
  groups: { telecom: "Telekom & Data", public: "Öffentliche Hand & Gesundheit", edu: "Bildung & Wissenschaft", finance: "Finanz & Payments", industry: "Industrie & Technologie", re: "Immobilien & Hospitality", legal: "Recht, Medien & Gesellschaft" },
  contact: {
    label: "Kontakt", title: "Sprechen wir.", p: "Erzählen Sie uns von Ihrem Vorhaben.",
    first: "Im ersten Gespräch klären wir Ziel, Ausgangslage und Zeitrahmen und ob Beratung, Umsetzung oder ein Joint Venture am besten passt.",
    web: "Web", mail: "E-Mail", loc: "Standort", locV: "Wien, Österreich", entity: "Rechtsträger",
    people: "Ansprechpartner", peopleV: ["Mag.^iur David Brainin – Recht, Kapital, Immobilien", "Philip Kügler, MSc – Technologie, Sicherheit, Produkt"],
    form: {
      name: "Name", company: "Unternehmen", email: "E-Mail", topic: "Thema", message: "Nachricht",
      topics: ["Tech & AI", "Real Estate & Hospitality", "Regulierte Märkte / Joint Venture", "Sonstiges"],
      namePh: "Ihr Name", companyPh: "Optional", emailPh: "sie@unternehmen.at", messagePh: "Ihr Anliegen in wenigen Zeilen",
      submit: "Projektanfrage senden", sending: "Wird gesendet …",
      privacy: "Wir verarbeiten Ihre Daten gemäß unserer", privacyLink: "Datenschutzerklärung",
      success: "Danke, wir melden uns in Kürze.",
      fallbackTitle: "Noch nicht versendet.", fallbackText: "Ein Klick öffnet sie fertig vorbereitet in Ihrem E-Mail-Programm.",
      fallbackBtn: "E-Mail öffnen", fallbackOr: "oder direkt an", required: "Bitte Name und gültige E-Mail-Adresse angeben.",
    },
  },
  insights: { label: "Insights", title: "Was den Markt bewegt.", sub: "Ausgewählte Analysen seit Februar 2026.", all: "Alle", more: "Mehr anzeigen", read: "Lesen", view: "InVentures View", viewSub: "Unsere eigenen Analysen.", pageTitle: "Insights", pageSub: "Eigene Analysen und ausgewählte Marktberichte zu AI, Regulierung und Immobilien.", back: "Alle Insights" },
  tech: {
    nav: [["team", "Team"], ["compliance", "Compliance"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    chapters: ["Team", "Compliance", "Transformation", "Leistungen", "Netzwerk", "Prozess", "Kontakt", "Insights"],
    h1: ["AI und Plattformen", "für regulierte", "Märkte."],
    heroP: "AI für Unternehmen und Behörden, die mit sensiblen Daten arbeiten. Klar abgegrenzte Projekte.",
    ctaA: "Leistungen", ctaB: "Team",
    contactP: "AI-Projekt, Plattform oder Venture in einem regulierten Markt: Besprechen wir Ihr Vorhaben.",
    visual: { label: "Compliance by Design", layers: [["Anwendungsfälle", "AI-Agenten, Automatisierung, neue Services"], ["Integration & Betrieb", "Schnittstellen, Identity, Monitoring"], ["Daten & Systeme", "Register, ERP, Datenplattformen"]], chips: ["DSGVO", "AI Act", "ISO 27001", "BSI"], caption: "Recht, Sicherheit und Technik in einer Architektur." },
    stats: [{ v: "45+", l: "Mio. € Kapital mobilisiert" }, { v: "12+", l: "Mio. € Forschungs\u00adförderung" }, { v: "4", l: "Staatliche IT-Programme" }, { v: "10+", l: "Mio. € Verantwortung im Zollprogramm" }, { v: "40+", l: "Projekte DACH & MENA" }, { v: "50+", l: "Jahre Erfahrung, zusammen\u00adgerechnet" }],
    partnerTitle: "Projekterfahrung",
    teamLabel: "Team", teamTitle: "Recht und Technologie in einem Team.", teamIntro: "",
    profiles: [
      { ...PEOPLE_DE.david, role: "Founder & Managing Partner", focus: "Recht · Kapital · Company Building",
        paras: ["Jurist und CEO mehrerer Unternehmen. 25+ Jahre operative Erfahrung und Transaktionen von über 600 Mio. €.",
          "2015 Pionierauftrag von Deutscher Telekom und A1. Gründer und CEO der geolad (30+ Mitarbeiter, EU & Asien). DSGVO und EU AI Act in der Praxis."],
        quote: "Juristisch denken, unternehmerisch handeln.",
        cards: [["Telekom & Daten", "Deutsche Telekom, A1, Orange, Zain, Viettel, Huawei, Ericsson"], ["Wissenschaft & Bildung", "European Stroke Organisation, World Stroke Organization, Donau-Universität Krems, Sigmund Freud PrivatUniversität (in Vorbereitung)"], ["Immobilien", "Wiener Privatbank, EPI Immobilien, UNIQA"], ["Kanzleien", "Lansky, Ganzger & Partner, Herbst Kinsky"], ["Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Gesellschaft", "Integrationshaus Wien, ORF, Red Bull, vidid"]] },
      { ...PEOPLE_DE.philip, role: "Managing Partner, Technology", focus: "Architektur · Sicherheit · Umsetzung",
        paras: ["Enterprise-Architekt, Programmmanager und CTO. 25+ Jahre IT-Großprojekte für öffentliche Hand, Finanzen und Bildung.",
          "Nationale Krankenversicherung Katar (mit McKinsey), Zoll im Finanzministerium, ePassport und Grenzkontrolle. CTO & Mitgründer OptInk, GF Merkit Consulting. MSc TU Wien, IPMA Level C."],
        quote: "Pragmatisch bauen, verlässlich betreiben.",
        cards: [["Öffentliche Hand", "BMF / Zoll, ePassport, Grenzkontrolle"], ["Gesundheit", "Nationale Krankenversicherung Katar (McKinsey)"], ["Bildung", "Untis – IAM & SSO für Schulen; TU Wien"], ["Finanzen & Payments", "Global Blue, Arthur D. Little, Core Banking"], ["Telekom", "Telekom Austria, VeriSign / 3united"], ["Ventures", "OptInk, Merkit Consulting, Porsche Informatik, RISE"]] },
    ],
    comp: {
      label: "Datenschutz & Sicherheit", title: "DSGVO, AI Act und ISO 27001 von Anfang an mitgedacht.",
      p: "Rechtliche Bewertung und technische Umsetzung aus einem Team, geschult am Telekommunikationsrecht mehrerer Länder.",
      cols: [
        { t: "Sicherheit & Architektur", who: "Philip Kügler", items: ["Sicherheitsanforderungen nach ISO 27001 und BSI sowie ITIL-Prozesse in Projekten umgesetzt", "IAM & SSO: Keycloak, OIDC/SAML", "Sichere internationale Datenübertragung", "Hochverfügbarkeit, Backup, Failover", "Privacy by Design und AI-Governance"] },
        { t: "Recht & Regulierung", who: "David Brainin", items: ["Telekommunikationsrecht mehrerer Länder, u. a. TKG", "8 Jahre DSGVO-Praxis in vier Branchen", "Art. 9 DSGVO: Gesundheitsdaten und Einwilligung", "Folgenabschätzung für AI-Systeme", "AI Act: Risikoklassen, Konformität, Dokumentation", "Datentransfers EU, MENA, ASEAN (Schrems II)"] },
      ],
    },
    tLabel: "AI-Transformation", tTitle: "Weniger Kosten. Neue Umsätze.",
    tP: "Automatisierung, neue Umsatzquellen und Agentic AI, jeweils mit messbaren Zielen.",
    opexT: "OPEX-Reduktion", opex: ["Automatisierung repetitiver Prozesse", "AI-gestützte Qualitätssicherung", "Intelligente Dokumenten- und Vertragsanalyse", "Konsolidierte Datenquellen"],
    revT: "Neue Umsätze", rev: ["Datenmonetarisierung", "AI-gestützte Produkte und Services", "Plattform- und Marktplatzmodelle", "SaaS aus internen Lösungen"],
    kpis: [{ v: "6–9", u: " Monate", l: "typische Laufzeit eines klar abgegrenzten Projekts" }, { v: "30 %", l: "Einsparziel je automatisiertem Prozess, projektspezifisch vereinbart" }, { v: "Neu", l: "Umsatzquellen aus vorhandenen Daten und Assets", gold: true }],
    sLabel: "Leistungen", sTitle: "Von der Strategie bis zum Betrieb.",
    serv: [
      { t: "AI-Strategie & Entscheidungsgrundlage", d: "Für Geschäftsführung und Vorstand: priorisierte Anwendungsfälle, Wirtschaftlichkeitsbewertung, Daten- und Risikoprüfung nach DSGVO und AI Act, Umsetzungsplan.", tags: ["Anwendungsfälle", "Business Case", "DSGVO & AI Act"] },
      { t: "AI-Implementierung & Automatisierung", d: "Klar abgegrenzter Pilot, Integration in bestehende Systeme, Evaluation und menschliche Freigaben bis in den laufenden Betrieb, auch mit Agentic AI.", tags: ["Pilot", "Integration", "Agentic AI"] },
      { t: "Plattformen & Venture Building", d: "Für Vorhaben in regulierten Märkten wie Gesundheit, Bildung und Verwaltung: Produkt, Governance, Finanzierung, Architektur und Markteinführung, bis hin zum Joint Venture.", tags: ["Gesundheit & Bildung", "Governance", "Joint Ventures"] },
      { t: "Executive Advisory & Strategic Support", d: "Strategische Begleitung von Geschäftsführung und Vorstand, Transaktionsbegleitung, Interim Management.", tags: ["Geschäftsführung", "Transaktionen", "Interim"] },
    ],
    netLabel: "Netzwerk", netTitle: "Das richtige Team für jede Aufgabe.", netP: "Spezialisten aus Recht, Technologie, Finanzen und Industrie.",
    clusters: [["Recht", "Gesellschafts-, IP- und Regulierungsrecht – Lansky, Ganzger & Partner, Herbst Kinsky"], ["Tech & AI", "Architekten, Security & IAM, AI- und Data-Engineers"], ["Öffentliche Hand & Gesundheit", "Ministerien, Register, Versicherer, Universitäten"], ["Finanzen", "RBI, Wiener Privatbank, VCs, Family Offices"], ["Industrie", "Telekom-Netzbetreiber, Transformationsexperten, UNIQA"]],
    netBar: "Das Team stellen wir je Projekt zusammen.", netBadge: "Beratung & Umsetzung",
    pLabel: "Prozess", pTitle: "So läuft ein Projekt ab.",
    proc: [{ t: "Kick-off", sub: "Woche 1", d: "Umfang und erste Hebel" }, { t: "Analyse", sub: "Woche 2–3", d: "Prozesse, Daten, Potenziale" }, { t: "Plan", sub: "Woche 4–5", d: "Maßnahmen, Kennzahlen, Meilensteine" }, { t: "Umsetzung", sub: "Monat 2–6", d: "Implementierung, AI-Integration" }, { t: "Wirkung", sub: "Monat 6–9", d: "Geringere Kosten, neue Umsätze" }],
    pBar: ["Typisch:", "6–9 Monate", "bei vereinbartem Umfang"], pBadge: "Zeitplan je Projekt vereinbart",
  },
  re: {
    nav: [["profil", "Profil"], ["expertise", "Expertise"], ["leistungen", "Leistungen"], ["netzwerk", "Netzwerk"], ["prozess", "Prozess"], ["kontakt", "Kontakt"]],
    chapters: ["Profil", "Expertise", "Leistungen", "Netzwerk", "Prozess", "Kontakt", "Insights"],
    profileTitle: "Jurist mit 25 Jahren in Immobilien und Hotellerie.",
    h1: ["Ankauf, Verkauf", "und Entwicklung", "von Immobilien."],
    heroP: "Über 600 Mio. € Transaktionsvolumen in Wohnen, Gewerbe und Hotel, von der Struktur bis zum Closing.",
    ctaA: "Leistungen", ctaB: "Profil",
    contactP: "Ankauf, Verkauf, Entwicklung oder Hotel-Repositionierung: Besprechen wir Ihr Vorhaben.",
    stats: [{ v: "600+", l: "Mio. € Transaktions\u00advolumen" }, { v: "25+", l: "Jahre Erfahrung in Immobilien & Hospitality" }, { v: "3", l: "Asset-Klassen" }, { v: "AT · CEE · ES", l: "Märkte" }],
    partnerTitle: "Projekterfahrung",
    profileLabel: "Profil",
    profile: { ...PEOPLE_DE.david, role: "Founder & Managing Partner", focus: "Recht · Transaktionen · Immobilien",
      paras: ["CEO mehrerer Unternehmen, Transaktionen von über 600 Mio. €.", "Partner für institutionelle Investoren, Family Offices und Projektentwickler in Österreich, CEE und Spanien."],
      quote: "Juristisch denken, unternehmerisch handeln.",
      cards: [["Wohnen", "EPI Immobilien, Trimmobilien, Conwert, Akkadia"], ["Gewerbe & Büro", "An- und Verkäufe"], ["Hotel & Hospitality", "EPI Hospitality, Ibis, Arcotel"], ["Retail & Mixed Use", "Beratung und Strukturierung"], ["Entwicklung", "Machbarkeit, Behörden, Projektmanagement"], ["Verkauf & Ankauf", "Buy-Side- und Sell-Side-Mandate"]] },
    tLabel: "Real Estate Expertise", tTitle: "Von der Analyse zum Closing.", tP: "Marktwissen, rechtliche Präzision, operative Umsetzung.",
    opexT: "Transaktion & Beratung", opex: ["Markt- und Machbarkeitsanalyse", "Due Diligence: rechtlich, finanziell, technisch", "Finanzierungs- und Eigenkapitalstruktur", "Verhandlung und Behördenkoordination"],
    revT: "Verkauf, Ankauf & Projekte", rev: ["Buy-Side- und Sell-Side-Mandate", "Entwicklung bis zur Übergabe", "Hotel-Repositionierung", "Deal-Sourcing CEE & Spanien"],
    kpis: [{ v: "600+", l: "Mio. € Transaktions\u00advolumen" }, { v: "25+", l: "Jahre Umsetzungserfahrung" }, { v: "CEE & Spanien", l: "Märkte" }],
    sLabel: "Leistungen", sTitle: "Was wir übernehmen.",
    serv: [
      { t: "Transaktionsberatung", d: "Buy-Side und Sell-Side: Marktanalyse, Due Diligence, Struktur und Verhandlung bis zu Signing und Closing. Rechtliche Leistungen erbringen unsere Partnerkanzleien.", tags: ["Ankauf & Verkauf", "Due Diligence", "Closing"] },
      { t: "Projekt- und Entwicklungsmanagement", d: "Entwicklung, Sanierung und Repositionierung: Budget, Termine und Behörden, von der Machbarkeit bis zur Übergabe.", tags: ["Entwicklung", "Sanierung", "Behörden"] },
      { t: "Hospitality", d: "Repositionierung, Markenwahl und Betreiberverhandlungen für Hotelimmobilien.", tags: ["Hotels", "Betreiber", "Repositionierung"] },
    ],
    netLabel: "Netzwerk", netTitle: "Das richtige Team für jeden Deal.", netP: "Partner aus Recht, Immobilien, Finanzen und Industrie.",
    clusters: [["Recht", "DSC Rechtsanwälte, Herbst Kinsky – Immobilien-, Gesellschafts- und Transaktionsrecht"], ["Immobilien", "EPI Immobilien, Akkadia, Arcotel, Plaza"], ["Finanzen", "RBI, Wiener Privatbank, Family Offices"], ["Industrie", "UNIQA, Stadt Wien, Baupartner"], ["Tech & AI", "PropTech, digitales Asset-Management"]],
    netBar: "Spezialisten ziehen wir je Mandat bei.", netBadge: "Beratung & Umsetzung",
    pLabel: "Prozess", pTitle: "So läuft ein Mandat ab.",
    proc: [{ t: "Briefing", sub: "Woche 1", d: "Mandat, Ziele, Zeitplan" }, { t: "Analyse", sub: "Woche 2–3", d: "Markt, Recht, Risiko" }, { t: "Struktur", sub: "Woche 3–5", d: "Deal, Finanzierung, Strategie" }, { t: "Verhandlung", sub: "Monat 2–4", d: "Deal-Management, Behörden" }, { t: "Closing", sub: "Monat 3–6", d: "Signing, Vollzug, Übergabe" }],
    pBar: ["Typisch:", "3–6 Monate", "vom Mandat zum Closing"], pBadge: "Operative Umsetzung",
  },
},
};
