// Curated insights for the /new site — published Feb–Sep 2026, URLs and dates verified on 2026-09-23.
// (The live site keeps using src/newsData.js.) `lang` = language of the source article; summaries in EN/DE.

export const techNews = [
  { id: "t1", date: "2026-09", source: "EY", title: "EY survey finds that autonomous AI implementation outpaces oversight, yielding an AI governance gap", url: "https://www.ey.com/en_us/newsroom/2026/09/ey-survey-finds-that-autonomous-ai-implementation-outpaces-oversight-yielding-an-ai-governance-gap", summary: "98% of large firms have AI governance policies, yet nearly half bypassed them for urgent deployments.", lang: "en", summary_de: "98 % der großen Unternehmen haben AI-Governance-Richtlinien – fast die Hälfte hat sie für dringende Einführungen umgangen." },
  { id: "t2", date: "2026-08", source: "Harvard Business Review", title: "Why Agentic AI Could Transform Procurement", url: "https://hbr.org/2026/08/why-agentic-ai-could-transform-procurement", summary: "Procurement may benefit from agentic AI more than almost any other function.", lang: "en", summary_de: "Der Einkauf könnte von Agentic AI stärker profitieren als fast jede andere Unternehmensfunktion." },
  { id: "t3", date: "2026-07", source: "European Commission", title: "Commission starts enforcing AI Act rules and new transparency requirements on 2 August", url: "https://digital-strategy.ec.europa.eu/en/news/commission-starts-enforcing-ai-act-rules-and-new-transparency-requirements-2-august", summary: "From 2 August 2026 the AI Office and national authorities begin enforcing the AI Act; new transparency rules apply from the same date.", lang: "en", summary_de: "Ab 2. August 2026 beginnen das AI Office und die nationalen Behörden mit der Durchsetzung des AI Act; zugleich gelten neue Transparenzregeln." },
  { id: "t4", date: "2026-07", source: "IBM", title: "IBM Study: One in Four Malicious Breaches are AI-Enabled, Costing Companies $6 Million on Average", url: "https://newsroom.ibm.com/2026-07-29-ibm-study-one-in-four-malicious-breaches-are-ai-enabled,-costing-companies-6-million-on-average", summary: "One in four malicious breaches were AI-enabled, up 56% year on year.", lang: "en", summary_de: "Jeder vierte Hackerangriff war AI-gestützt – 56 % mehr als im Vorjahr." },
  { id: "t5", date: "2026-06", source: "Capgemini / European Commission", title: "eGovernment Benchmark Report 2026: Slow but steady growth in online services provision across the EU", url: "https://www.capgemini.com/insights/research-library/egovernment-benchmark-report-towards-digital-government/", summary: "Digital public services score 84.6/100 for citizens and 88.6/100 for businesses — short of the 2030 target.", lang: "en", summary_de: "Digitale Verwaltungsleistungen erreichen 84,6/100 für Bürger und 88,6/100 für Unternehmen – noch unter dem Ziel für 2030." },
  { id: "t6", date: "2026-05", source: "European Parliament", title: "AI Act: deal on simplification measures, ban on “nudifier” apps", url: "https://www.europarl.europa.eu/news/en/press-room/20260427IPR42011/ai-act-deal-on-simplification-measures-ban-on-nudifier-apps", summary: "High-risk AI obligations move to 2 December 2027 and 2 August 2028.", lang: "en", summary_de: "Pflichten für Hochrisiko-AI verschieben sich auf 2. Dezember 2027 und 2. August 2028." },
  { id: "t7", date: "2026-04", source: "WHO/Europe", title: "New WHO/Europe report provides first-ever snapshot of AI in health care across European Union Member States", url: "https://www.who.int/europe/news/item/20-04-2026-new-who-europe-report-provides-first-ever-snapshot-of-ai-in-health-care-across-european-union-member-states", summary: "Nearly three quarters of EU countries already use AI-assisted diagnostics.", lang: "en", summary_de: "Fast drei Viertel der EU-Staaten setzen bereits AI-gestützte Diagnostik ein." },
  { id: "t8", date: "2026-04", source: "EDPB", title: "EDPB brings clarity to data processing for scientific research, speeds up the finalisation of the anonymisation guidelines", url: "https://www.edpb.europa.eu/news/news/2026/edpb-brings-clarity-data-processing-scientific-research-speeds-finalisation_en", summary: "New guidelines on personal data in research; first European data protection seal for transfers.", lang: "en", summary_de: "Neue Leitlinien zu personenbezogenen Daten in der Forschung; erstes europäisches Datenschutzsiegel für Übermittlungen." },
  { id: "t9", date: "2026-03", source: "KPMG", title: "Three out of four global leaders will prioritize AI investment despite economic uncertainty", url: "https://kpmg.com/xx/en/media/press-releases/2026/03/kpmg-global-ai-pulse-survey.html", summary: "32% are deploying and scaling AI agents; 27% orchestrate multiple agents.", lang: "en", summary_de: "32 % setzen AI-Agenten bereits ein und skalieren sie; 27 % steuern mehrere Agenten im Verbund." },
  { id: "t10", date: "2026-02", source: "International AI Safety Report", title: "International AI Safety Report 2026", url: "https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026", summary: "100+ experts led by Yoshua Bengio review capabilities, risks and risk management of general-purpose AI.", lang: "en", summary_de: "Über 100 Fachleute unter Leitung von Yoshua Bengio bewerten Fähigkeiten, Risiken und Risikomanagement von General-Purpose-AI." },
];

export const reNews = [
  { id: "r1", date: "2026-09", source: "European Central Bank", title: "Our monetary policy statement at a glance — September 2026", url: "https://www.ecb.europa.eu/press/press_conference/visual-mps/2026/html/mopo_statement_explained_september.en.html", summary: "The ECB raised key rates by 25 basis points; inflation expected above 2% for longer.", lang: "en", summary_de: "Die EZB hob die Leitzinsen um 25 Basispunkte an; die Inflation dürfte länger über 2 % bleiben." },
  { id: "r2", date: "2026-08", source: "RICS", title: "AI in commercial property and construction report 2026", url: "https://www.rics.org/news-insights/ai-in-commercial-property-and-construction-report-2026", summary: "Over three quarters of commercial property respondents use AI — most still at pilot stage.", lang: "en", summary_de: "Über drei Viertel der Befragten aus der Gewerbeimmobilienbranche nutzen AI – meist noch im Pilotstadium." },
  { id: "r3", date: "2026-08", source: "JLL", title: "EMEA living investment jumps 49% in second quarter", url: "https://www.jll.com/en-ae/newsroom/emea-living-investment-jumps-in-second-quarter", summary: "€17.4bn in Q2 2026, the highest quarterly volume since 2022.", lang: "en", summary_de: "17,4 Mrd. € im 2. Quartal 2026 – das höchste Quartalsvolumen seit 2022." },
  { id: "r4", date: "2026-07", source: "CBRE", title: "European Real Estate Investment Figures Q2 2026", url: "https://www.cbre.com/insights/figures/european-real-estate-investment-figures-q2-2026", summary: "€59.1bn invested in Q2 2026, up 10% year on year.", lang: "en", summary_de: "59,1 Mrd. € Investitionen im 2. Quartal 2026, ein Plus von 10 % gegenüber dem Vorjahr." },
  { id: "r5", date: "2026-07", source: "European Commission", title: "The Commission calls for progress on the transposition of the Energy Performance of Buildings Directive", url: "https://build-up.ec.europa.eu/en/news-and-events/news/commission-calls-progress-transposition-energy-performance-buildings-directive", summary: "Infringement procedures against all 27 Member States over the recast EPBD.", lang: "en", summary_de: "Vertragsverletzungsverfahren gegen alle 27 Mitgliedstaaten wegen der Umsetzung der neugefassten Gebäuderichtlinie." },
  { id: "r6", date: "2026-05", source: "CBRE", title: "European Hotel Investor Intentions Survey 2026", url: "https://www.cbre.com/insights/reports/european-hotel-investor-intentions-survey-2026", summary: "Over 90% of investors plan to hold or raise their allocation to European hotels.", lang: "en", summary_de: "Über 90 % der Investoren wollen ihre Allokation in europäische Hotels halten oder erhöhen." },
  { id: "r7", date: "2026-04", source: "EHL Immobilien", title: "EHL Büromarktbericht Frühjahr 2026", url: "https://www.ehl.at/blog/ehl-bueromarktbericht-fruehjahr-2026", summary: "Vienna office vacancy around 3.8%, prime rents up to about €29.50/m².", lang: "de", summary_de: "Büroleerstand in Wien rund 3,8 %, Spitzenmieten bis etwa 29,50 €/m²." },
  { id: "r8", date: "2026-04", source: "OeNB", title: "Kapitalisierung verbessert, Kosten-Ertrags-Verhältnis schlechter, Finanzstabilität gut", url: "https://www.oenb.at/Presse/Pressearchiv/2026/20260422.html", summary: "Commercial real estate in focus: 43% of Austrian banks' corporate loans, NPL ratio 8.3%.", lang: "de", summary_de: "Gewerbeimmobilien im Fokus: 43 % der Unternehmenskredite österreichischer Banken, NPL-Quote 8,3 %." },
  { id: "r9", date: "2026-03", source: "Cushman & Wakefield", title: "Investors Return to Europe's Hotel Sector as Transactions Exceed €27 Billion", url: "https://www.cushmanwakefield.com/en/germany/news/2026/03/hotel-investment-emea", summary: "Strongest year for European hotel investment since 2019.", lang: "en", summary_de: "Stärkstes Jahr für Hotelinvestments in Europa seit 2019." },
  { id: "r10", date: "2026-02", source: "EHL Immobilien", title: "Der Wohnungsmarkt Wien 2026", url: "https://www.ehl.at/blog/der-wohnungsmarkt-wien-2026", summary: "Completions at about 60% of 2023 levels; rents up around 7–8%.", lang: "de", summary_de: "Fertigstellungen bei rund 60 % des Niveaus von 2023; Mieten steigen um etwa 7–8 %." },
];

// Own articles (InVentures View), each on its own page under /insights/<slug>.
export const articles = [
  { slug: "agentic-ai", track: "tech", date: "2026-09",
    title: { de: "Vom Assistenten zum Agenten: Was die Forschung für die nächsten 24 Monate erwarten lässt", en: "From assistant to agent: what research suggests for the next 24 months" },
    teaser: { de: "Fähigkeiten, Kosten, Verbreitung, Arbeit und Vertrauen – ein forschungsbasierter Ausblick auf AI-Agenten in Unternehmen für die nächsten sechs bis 24 Monate.", en: "Capabilities, costs, adoption, work and trust — a research-based outlook on AI agents in companies over the next six to 24 months." } },
  { slug: "real-estate-after-the-correction", track: "re", date: "2026-09",
    title: { de: "Nach der Korrektur: Wo der Immobilienmarkt in den nächsten 24 Monaten Chancen bietet", en: "After the correction: where real estate offers opportunities over the next 24 months" },
    teaser: { de: "Finanzierung, Wohnen, Büro, Energie, Hotels und AI – ein faktenbasierter Ausblick auf den Immobilienmarkt in Österreich und Europa für die nächsten sechs bis 24 Monate.", en: "Financing, residential, office, energy, hotels and AI — a fact-based outlook on real estate in Austria and Europe over the next six to 24 months." } },
];
