// Curated news & research articles for Inventures.at
// Tech & AI track + Real Estate track — 2020 to 2026

export const techNews = [
  {
    id: 1,
    title: "The State of AI: Global Survey 2025",
    source: "McKinsey Global Institute",
    date: "2025-03",
    url: "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai",
    summary:
      "88% of organisations now use AI in at least one business function — up from 78% a year ago. Yet most remain in the piloting phase, with only one-third reporting enterprise-wide scaling.",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 11,
    title: "Agentic AI: The Next Wave of Enterprise Automation",
    source: "Deloitte Insights",
    date: "2025-01",
    url: "https://www2.deloitte.com/us/en/insights/focus/tech-trends.html",
    summary:
      "Agentic AI systems capable of autonomous decision-making and multi-step execution are moving from research to production. Enterprises in finance, legal and operations are piloting AI agents as 'virtual employees'.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 8,
    title: "5 AI-Driven B2B Sales Trends Reshaping Revenue in 2025",
    source: "Forrester Research / Gartner",
    date: "2025-10",
    url: "https://optif.ai/media/articles/b2b-sales-trends-2025",
    summary:
      "89% of revenue organisations now use AI-powered tools. Predictive lead scoring delivers 89% accuracy, conversational AI cuts response times from 38 hours to 30 seconds, and revenue intelligence platforms improve forecast accuracy to ±5%.",
    image: "https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 4,
    title: "EU AI Act Enters into Force: What Businesses Need to Know",
    source: "European Commission",
    date: "2024-08",
    url: "https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence",
    summary:
      "The EU AI Act — the world's first comprehensive AI regulation — establishes risk-based obligations for AI developers and deployers. High-risk applications require conformity assessments, DPIAs and ongoing monitoring.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 2,
    title: "McKinsey Technology Trends Outlook 2025: Agentic AI Takes Centre Stage",
    source: "McKinsey & Company",
    date: "2025-07",
    url: "https://www.mckinsey.com/capabilities/tech-and-ai/our-insights/the-top-trends-in-tech",
    summary:
      "Agentic AI — systems capable of autonomously planning and executing multi-step workflows — has emerged as one of the fastest-growing enterprise technology trends, with applications in IT, knowledge management and sales.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 3,
    title: "Harnessing Generative AI for B2B Sales",
    source: "McKinsey & Company",
    date: "2024-09",
    url: "https://www.mckinsey.com/capabilities/growth-marketing-and-sales/our-insights/an-unconstrained-future-how-generative-ai-could-reshape-b2b-sales",
    summary:
      "Gen AI could unlock $0.8–1.2 trillion in additional productivity across sales and marketing. The technology is moving from automating tasks to enabling entirely new growth pathways for B2B organisations.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 5,
    title: "Gartner Top Strategic Technology Trends 2024",
    source: "Gartner",
    date: "2024-10",
    url: "https://www.gartner.com/en/articles/gartner-top-10-strategic-technology-trends-for-2024",
    summary:
      "AI Trust, Risk and Security Management (AI TRiSM) and Continuous Threat Exposure Management headline Gartner's top trends, alongside AI-augmented development and intelligent applications reshaping enterprise software.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 6,
    title: "Generative AI: The Next Productivity Frontier",
    source: "McKinsey Global Institute",
    date: "2023-06",
    url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai",
    summary:
      "Generative AI could add $2.6–4.4 trillion annually to the global economy. Knowledge workers face the greatest transformation, with 60–70% of current work activities potentially automated.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 7,
    title: "Vienna as a DACH AI Hub: Startup Ecosystem Report 2024",
    source: "Austrian Startup Monitor",
    date: "2024-06",
    url: "https://austrianstartupmonitor.at",
    summary:
      "Vienna continues to attract AI and deep-tech founders from across the DACH region, with B2B SaaS and AI-driven automation companies leading a record year for Austrian startup investment.",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 9,
    title: "GDPR at Six Years: Lessons for AI Compliance",
    source: "European Data Protection Board",
    date: "2024-05",
    url: "https://www.edpb.europa.eu/our-work-tools/our-documents/recommendations/recommendations-012020-measures-supplement-transfer_en",
    summary:
      "Six years of GDPR enforcement offer a roadmap for AI Act implementation. Organisations that embedded privacy-by-design early now face far lower compliance costs as they transition to EU AI Act obligations.",
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 10,
    title: "Deutsche Telekom & A1 Group: AI-Driven Revenue Streams in Telecom",
    source: "GSMA Intelligence",
    date: "2023-09",
    url: "https://www.gsma.com/solutions-and-impact/technologies/networks/gsma_resources/ai-telecom-report/",
    summary:
      "European telcos are leveraging AI for customer churn prediction, network optimisation and new B2B data products. Early movers report OPEX reductions of 15–25% and incremental revenues from anonymised mobility analytics.",
    image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 12,
    title: "State of AI+BI Analytics 2025: Enterprise Adoption Benchmark",
    source: "Strategy Analytics",
    date: "2025-07",
    url: "https://www.gartner.com/en/articles/gartner-top-10-strategic-technology-trends-for-2025",
    summary:
      "43% of organisations now use AI-powered analytics in production. Decision-making improvement is cited as the top goal by 56% of data leaders — closely followed by cost savings and workflow efficiency.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 13,
    title: "AI and the Future of Work: Automation's Impact on European Labour Markets",
    source: "OECD",
    date: "2023-07",
    url: "https://www.oecd.org/en/publications/2023/07/generative-ai-and-the-future-of-work_c2ab1b21.html",
    summary:
      "The OECD estimates 27% of jobs in OECD countries are at high risk of automation. Knowledge-intensive roles in finance, legal and consulting face significant AI augmentation, while new tech roles are being created in parallel.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 14,
    title: "Responsible AI: Building Trust in Enterprise AI Systems",
    source: "IBM Institute for Business Value",
    date: "2024-04",
    url: "https://www.ibm.com/thought-leadership/institute-business-value/report/ai-ethics",
    summary:
      "Only 35% of global consumers trust how companies use AI. Organisations that prioritise explainability and bias testing see 2.5x higher customer satisfaction scores and significantly lower regulatory risk.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 15,
    title: "Rewired: The McKinsey Guide to Outcompeting in the Age of Digital and AI",
    source: "McKinsey & Company",
    date: "2023-05",
    url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/rewired-the-mckinsey-guide-to-outcompeting-in-the-age-of-digital-and-ai",
    summary:
      "Deep-dive into six dimensions required for successful AI transformation at scale: strategy, talent, operating model, technology, data, and adoption. Companies that get all six right report 3x higher EBIT impact.",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 16,
    title: "AI in Professional Services: Law, Finance & Consulting Transformation",
    source: "PwC Global",
    date: "2024-11",
    url: "https://www.pwc.com/gx/en/issues/artificial-intelligence.html",
    summary:
      "73% of professional services firms have deployed AI tools in at least one practice area. Legal research, financial analysis and management consulting show the fastest adoption, with measurable productivity gains of 20–40%.",
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 17,
    title: "The Rise of Digital Platforms in DACH Telecom: Lessons for B2B",
    source: "Roland Berger",
    date: "2022-09",
    url: "https://www.rolandberger.com/en/Insights/Global-Topics/Artificial-Intelligence/",
    summary:
      "DACH telecom operators are pivoting from connectivity providers to digital platform companies. Data monetisation and enterprise B2B services now represent the fastest-growing revenue streams for A1, Deutsche Telekom and Swisscom.",
    image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400&h=250&fit=crop",
    year: 2022,
  },
  {
    id: 18,
    title: "AI Regulation: Global Tracker — EU, US and Asia Compared",
    source: "Stanford HAI",
    date: "2024-03",
    url: "https://hai.stanford.edu/news/ai-index-report-2024",
    summary:
      "The Stanford AI Index 2024 documents an explosion in AI legislation globally — from 1 bill in 2016 to 25 passed in 2023. The EU AI Act sets the most comprehensive framework, influencing regulation in 40+ countries.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 19,
    title: "Measuring the ROI of AI Implementation: Enterprise Benchmarks",
    source: "Boston Consulting Group",
    date: "2023-11",
    url: "https://www.bcg.com/publications/2023/measuring-the-business-impact-of-ai",
    summary:
      "BCG analysed 230 AI implementations and found that companies achieving ROI follow a consistent pattern: start with high-frequency, data-rich use cases, establish feedback loops, and redesign workflows rather than just automating existing ones.",
    image: "https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 20,
    title: "AI-First Organisations: From Pilot to Scale in 9 Months",
    source: "Harvard Business Review",
    date: "2024-07",
    url: "https://hbr.org/topic/subject/ai-and-machine-learning",
    summary:
      "A study of 500 organisations found that those treating AI as an organisational transformation — not just a technology project — achieved enterprise-wide scaling 3x faster and reported EBIT impact at 40% higher frequency.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 21,
    title: "GDPR Data Transfers Post-Schrems II: Compliance Architecture for Global Platforms",
    source: "Bird & Bird / European Data Protection Board",
    date: "2021-06",
    url: "https://www.edpb.europa.eu/our-work-tools/our-documents/recommendations/recommendations-012020-measures-supplement-transfer_en",
    summary:
      "Following the Schrems II ruling, companies operating data platforms across EU, MENA and ASEAN must implement supplementary measures including encryption, pseudonymisation and Transfer Impact Assessments.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=250&fit=crop",
    year: 2021,
  },
  {
    id: 22,
    title: "Digitalisierung in Österreich: KI-Readiness Report 2024",
    source: "WKO / Wirtschaftskammer Österreich",
    date: "2024-09",
    url: "https://www.wko.at/oe/news/studie-ki-oekosysteme",
    summary:
      "Nur 18% der österreichischen KMU setzen KI produktiv ein, doch die Investitionsbereitschaft steigt stark. Automatisierung von Back-Office-Prozessen und KI-gestützte Kundeninteraktion führen die Prioritätenlisten an.",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 23,
    title: "The Global Startup Ecosystem Report 2023: DACH Rising",
    source: "Startup Genome",
    date: "2023-06",
    url: "https://startupgenome.com/reports/gser2023",
    summary:
      "Berlin, Vienna and Zurich rank among Europe's top 15 startup ecosystems. Vienna shows exceptional strength in deep tech, life sciences and AI, driven by world-class technical universities and increasing corporate venture activity.",
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 24,
    title: "Machine Learning in Enterprise: From Experimentation to Value Creation",
    source: "MIT Sloan Management Review",
    date: "2022-04",
    url: "https://sloanreview.mit.edu/article/the-machine-learning-race-is-really-a-data-race/",
    summary:
      "MIT research shows that companies capturing value from ML share a common trait: they treat model development as a continuous loop — deploy, measure, retrain — rather than a one-off project with a fixed end date.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=250&fit=crop",
    year: 2022,
  },
  {
    id: 25,
    title: "AI Transformation in Telecom: New Revenue Streams from Data Platforms",
    source: "Analysys Mason",
    date: "2020-11",
    url: "https://www.rolandberger.com/en/Insights/Global-Topics/Artificial-Intelligence/",
    summary:
      "Telecom operators monetising network data through B2B analytics platforms can generate $500M–$2B in incremental annual revenue. Mobility data, location intelligence and network APIs are the most commercially proven use cases.",
    image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400&h=250&fit=crop",
    year: 2020,
  },];

export const reNews = [
  {
    id: 1,
    title: "Austria Real Estate Market Outlook 2026",
    source: "CBRE Austria",
    date: "2026-02",
    url: "https://www.cbre.com/insights/reports/austria-real-estate-market-outlook-2026",
    summary:
      "Austria's investment market has returned to pre-crisis levels. Institutional and international investors are back, prime yields continue to fall, and the Vienna office market recorded a strong leasing year driven by major deals.",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=250&fit=crop",
    year: 2026,
  },
  {
    id: 15,
    title: "Vienna Office Market 2024: Prime Rents Rise Despite Remote Work Headwinds",
    source: "Colliers Austria",
    date: "2024-07",
    url: "https://www.colliers.com/de-at/research/austria-real-estate-market-report",
    summary:
      "Vienna's office vacancy rate edged up slightly in 2024 as remote work reshaped demand, but prime rents in the 1st and 3rd districts continued to rise — reaching EUR 27/sqm/month for best-in-class space.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 13,
    title: "AI in Real Estate Due Diligence: Automation Cuts Transaction Time by 40%",
    source: "Deloitte Real Estate",
    date: "2024-03",
    url: "https://www2.deloitte.com/global/en/pages/real-estate/articles/real-estate-predictions.html",
    summary:
      "AI-powered due diligence tools are slashing the time required for legal, technical and commercial reviews. Platforms like LEVERTON and Structo can process hundreds of lease documents in hours, reducing transaction timelines.",
    image: "https://images.unsplash.com/photo-1486596422571-0ba4a6dbba18?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 12,
    title: "Real Estate Transaction Advisory: Structuring Cross-Border Deals in MENA and EU",
    source: "Knight Frank",
    date: "2023-11",
    url: "https://www.knightfrank.com/research/report-library/",
    summary:
      "Middle Eastern sovereign wealth funds and family offices invested over $8bn in European real estate in 2023. Austria, Germany and the UK were the top destinations for MENA capital deploying into trophy and logistics assets.",
    image: "https://images.unsplash.com/photo-1503389152951-9f343d3ad3b7?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 2,
    title: "Austria Investment Figures Q4 2025: EUR 4.1bn — Strongest Quarter Since 2019",
    source: "CBRE Austria",
    date: "2026-01",
    url: "https://www.cbre.com/insights/reports/austria-real-estate-market-outlook-2026",
    summary:
      "Austria's 2025 investment volume reached EUR 4.1bn — 40% above 2024. Vienna alone recorded EUR 3.1bn, driven by residential (29%), office (25%) and hotel (15%) assets.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=250&fit=crop",
    year: 2026,
  },
  {
    id: 3,
    title: "Living Market Report Austria 2025: Structural Housing Shortage Intensifies",
    source: "CBRE Austria",
    date: "2025-11",
    url: "https://www.cbre.com/insights/reports/austria-real-estate-market-outlook-2026",
    summary:
      "Vienna, Graz, Linz and Salzburg face acute housing shortages as completions fall and demand rises. Rents are rising sharply, with no trend reversal expected in 2026.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa12c98?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 4,
    title: "Austria Real Estate Market Outlook 2025",
    source: "CBRE Austria",
    date: "2025-02",
    url: "https://www.cbre.com/insights/reports/austria-real-estate-market-outlook-2026",
    summary:
      "The price correction cycle is complete. Yields are falling across all asset classes and international players are returning to the Austrian market after two years of domestic investor dominance.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 5,
    title: "European Real Estate Market Outlook 2025: Recovery Gathering Pace",
    source: "CBRE Europe",
    date: "2025-01",
    url: "https://www.cbre.com/insights/reports/european-real-estate-market-outlook-2025",
    summary:
      "After two years of yield expansion and price correction, Europe's real estate markets are moving from adjustment to recovery. Cross-border capital flows are rebounding, led by logistics, living and prime office.",
    image: "https://images.unsplash.com/photo-1560185127-6a9d7e6a9e5e?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 6,
    title: "PropTech in Europe 2024: AI, Data and the Race to Digitise Real Estate",
    source: "PriceHubble / PwC",
    date: "2024-09",
    url: "https://www.pricehubble.com/blog/proptech-europe-trends",
    summary:
      "The European PropTech Map 2024 identifies five categories reshaping real estate: investment platforms, building operations, asset management, market analytics and smart city. AI-driven valuation and analytics are the fastest growing.",
    image: "https://images.unsplash.com/photo-1486596422571-0ba4a6dbba18?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 7,
    title: "PropTech Investment Hits $3.2bn in 2024: AI-Powered Leasing and Management Lead",
    source: "Landbase / CRETI",
    date: "2024-12",
    url: "https://www.landbase.com/blog/fastest-growing-proptech-companies",
    summary:
      "The global PropTech market reached $36.55bn in 2024, with $3.2bn invested in AI-powered startups. AI leasing automation, CRM platforms and predictive analytics dominate the investment landscape.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 8,
    title: "Vienna Hotel Market 2025: Record Tourism and Reviving Investor Interest",
    source: "CBRE Austria",
    date: "2025-06",
    url: "https://www.cbre.com/insights/reports/austria-real-estate-market-outlook-2025",
    summary:
      "Vienna's hotel market benefited from record overnight stays in 2024 and 2025, with hotel transactions reaching nearly EUR 600m. Arcotel, Plaza Group and international operators are actively repositioning assets.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 9,
    title: "European Investor Intentions Survey 2025: Cautious Optimism Returns",
    source: "CBRE Europe",
    date: "2025-02",
    url: "https://www.cbre.com/insights/reports/european-real-estate-outlook",
    summary:
      "CBRE's 2025 European Investor Intentions Survey reveals markedly more optimism versus recent years. Logistics and residential lead preferred asset classes, while ESG compliance is now a table-stakes requirement.",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 10,
    title: "German Residential Real Estate: Market Stabilisation After 30% Price Correction",
    source: "JLL Germany",
    date: "2024-06",
    url: "https://www.jll.com/en-de/insights/housing-market-overview",
    summary:
      "Germany's residential market shows early signs of stabilisation after a peak-to-trough correction of up to 30% in major cities. Transaction volumes are recovering in Munich, Berlin and Hamburg as financing conditions ease.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 11,
    title: "ESG in Real Estate: Green Building Certifications Drive 8–12% Rent Premium in Vienna",
    source: "CBRE Austria / OIB",
    date: "2024-10",
    url: "https://www.cbre.com/insights/reports/european-real-estate-outlook",
    summary:
      "ESG-certified office and residential buildings in Vienna command rent premiums of 8–12% over conventional stock. Tenants and investors increasingly use ÖGNI/BREEAM certification as a baseline requirement.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa12c98?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 14,
    title: "European PropTech Startups Bridging Real Estate and Finance",
    source: "Bebeez / European PropTech Association",
    date: "2025-11",
    url: "https://bebeez.eu/2025/11/04/beyond-the-lease-10-european-startups-bridging-real-estate-and-finance/",
    summary:
      "Tokenised ownership, rent-to-own models, AI-powered asset management and blockchain-backed investment platforms are redefining how money moves through property across Europe.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 16,
    title: "Distressed Real Estate Assets in Europe: Opportunity or Risk?",
    source: "PwC / ULI Real Estate",
    date: "2023-10",
    url: "https://www.pwc.com/gx/en/industries/financial-services/real-estate/emerging-trends-real-estate.html",
    summary:
      "Emerging Trends in Real Estate Europe 2024 highlights a wave of distressed and repriced assets creating selective buying opportunities — particularly in German and UK commercial real estate.",
    image: "https://images.unsplash.com/photo-1560185127-6a9d7e6a9e5e?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 17,
    title: "Austrian Hospitality Real Estate: Investment Momentum After Post-Pandemic Recovery",
    source: "Christie & Co / CBRE",
    date: "2023-06",
    url: "https://www.inrev.org/news/press/strong-appetite-real-estate-despite-covid-19-pandemic",
    summary:
      "Austria's hotel transaction market rebounded strongly in 2023 as tourism numbers exceeded 2019 levels. Investors focus on repositioning opportunities in city-centre and alpine destinations.",
    image: "https://images.unsplash.com/photo-1503389152951-9f343d3ad3b7?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 18,
    title: "Real Estate Development in Austria: Regulatory Landscape and Construction Cost Pressures",
    source: "EHL Immobilien / WKO",
    date: "2023-04",
    url: "https://www.wohnungsmarktbericht.at",
    summary:
      "Rising construction costs (+25–35% since 2020), supply chain disruptions and tighter zoning regulations in Vienna are slowing new residential completions and driving up values of existing stock.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa12c98?w=400&h=250&fit=crop",
    year: 2023,
  },
  {
    id: 19,
    title: "MENA Capital Flows into European Real Estate: Structuring Gulf Investment",
    source: "Savills International",
    date: "2022-09",
    url: "https://www.savills.com/research_articles/255800/330756-0",
    summary:
      "Gulf Cooperation Council sovereign funds and UHNW family offices are directing record capital into European real estate. Austria, with its legal stability and AAA-rated economy, is increasingly attractive to MENA investors.",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=250&fit=crop",
    year: 2022,
  },
  {
    id: 20,
    title: "Conwert AG Privatisation and Portfolio Rationalisation: A Case Study",
    source: "Börsen-Zeitung / Real Estate Capital",
    date: "2021-03",
    url: "https://www.inrev.org/news/press/capital-raised-european-non-listed-real-estate-recovers-pre-pandemic-record-high",
    summary:
      "The integration of Conwert AG into Vonovia marked a pivotal moment in Austrian residential consolidation. The EUR 2bn+ transaction reshaped the Vienna rental market and established new benchmarks for residential M&A.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=250&fit=crop",
    year: 2021,
  },
  {
    id: 21,
    title: "PropTech Has a Bright Future: AI Property Management Reshapes European Rental Markets",
    source: "International Banker",
    date: "2025-11",
    url: "https://internationalbanker.com/technology/proptech-has-a-bright-future-ahead/",
    summary:
      "AI-first property management platforms like Arbio (EUR 45m funding) are disrupting European short-term rental markets. AI building management, predictive maintenance and digital tenant experience are the next frontier.",
    image: "https://images.unsplash.com/photo-1486596422571-0ba4a6dbba18?w=400&h=250&fit=crop",
    year: 2025,
  },
  {
    id: 22,
    title: "Real Estate and the Interest Rate Cycle: What Falling Rates Mean for Valuations",
    source: "JLL EMEA Research",
    date: "2024-12",
    url: "https://www.jll.com/en/trends-and-insights/research/global-real-estate-perspective",
    summary:
      "As the ECB cuts rates for the first time since 2019, JLL projects 5–15% value uplifts for core real estate across Europe by 2026. Office and logistics in gateway cities are expected to benefit most.",
    image: "https://images.unsplash.com/photo-1560185127-6a9d7e6a9e5e?w=400&h=250&fit=crop",
    year: 2024,
  },
  {
    id: 23,
    title: "Urban Residential Real Estate in Central Europe: Supply Squeeze and Rent Dynamics",
    source: "EHL Immobilien Research",
    date: "2022-06",
    url: "https://publikationen.ehl.at/view/1054655877",
    summary:
      "Vienna, Prague and Warsaw face a structural supply-demand imbalance. New-build activity is 30% below historical averages while household formation continues at a record pace, driving rents to all-time highs.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa12c98?w=400&h=250&fit=crop",
    year: 2022,
  },
  {
    id: 24,
    title: "COVID-19's Long-Term Impact on Commercial Real Estate: EMEA Perspectives",
    source: "CBRE / Savills Research",
    date: "2021-09",
    url: "https://www.cbre.com/insights/reports/european-office-market-report-2021",
    summary:
      "Hybrid work has permanently reduced office footprints by 10–20%, but prime office in central locations remained resilient. The pandemic accelerated flight-to-quality trends and repositioning of secondary stock.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
    year: 2021,
  },
  {
    id: 25,
    title: "Austrian Real Estate Market 2020: Resilience Amid Global Uncertainty",
    source: "Erste Bank / EHL Immobilien",
    date: "2020-11",
    url: "https://www.wohnungsmarktbericht.at",
    summary:
      "Austria's real estate market demonstrated exceptional resilience in 2020. Residential demand accelerated on the back of historically low interest rates, while logistics emerged as the standout commercial asset class.",
    image: "https://images.unsplash.com/photo-1503389152951-9f343d3ad3b7?w=400&h=250&fit=crop",
    year: 2020,
  },];
